### ISSUE TITLE
bug?/not passing selected field after search

### ISSUE THREAD

**Issue by Gizmo1337** [salim-lachdhaf/searchable_dropdown#1]
How to reproduce :
 Using the basic example / Simple implementation from the docs. Or any of the docs implementations.
 
Using the drop-down and selecting any element will work, and the new selected item will be displayed correctly, while the search field was not tap-ed and nothing was searched. 

However if you happen to search something and tap it, value will not pass and the selected Item will reset to default.

A Simple workaround for me was to update the selectedItem onChange. 
  ` onChanged: (data) {
                        setState(
                          () {
                            newSelectedValue = data;
                          },
                        );
                      },`

However it doesn't feel as intended.

**Comment by salim-lachdhaf** [comment]
please make sure that you are using version 0.2.9. this issue should be corrected

**Comment by lambasoft** [comment]
I'm using version 0.4.4 and this problem is still existing.

**Comment by midas-phoenix** [comment]
Currently experiencing the same issue

**Comment by salim-lachdhaf** [comment]
Thank you for re reporting that, this will be fixed in the next version 0.4.6
