### ISSUE TITLE
Customize the font size of the selected item

### ISSUE THREAD

**Issue by fabiojansenbr** [salim-lachdhaf/searchable_dropdown#10]
Hi, is there any way to customize the font size of the selected item?

**Comment by salim-lachdhaf** [comment]
on the popUp or on the dropDownSearch ?

**Comment by fabiojansenbr** [comment]
Hi Salim. On the dropdown field where the selected item is presented.

![image](https://user-images.githubusercontent.com/18349848/83178613-279a2080-a0f7-11ea-9bb0-8ab1e0cb7946.png)

**Comment by salim-lachdhaf** [comment]
You can customize `dropdownBuilder` example:

```
DropdownSearch<String>(
                .......,
                DropdownBuilder:(BuildContext context, UserModel item, String itemAsString) {
       return Text(itemAsString, style: 
      TextStyle(
      fontSize: 20.0,
      color: Colors.yellow,
    ),
);
}
              )
```
