### ISSUE TITLE
How to change borderRadius ?  

### ISSUE THREAD

**Issue by nataliafurtado** [salim-lachdhaf/searchable_dropdown#100]

**Comment by vasilich6107** [comment]
Border radius of what?

**Comment by salim-lachdhaf** [comment]
waiting for more details

**Comment by nataliafurtado** [comment]
dropdownSearchDecoration: InputDecoration(
            contentPadding: EdgeInsets.only(left: 10),
            border: OutlineInputBorder(
              borderSide: BorderSide(
                color: StylesCore.detailGreyColors,
                width: 1.0,
              ),
              borderRadius: new BorderRadius.all(
                new Radius.circular(10),
              ),
            ),
            
            that is what i wanted ! 
             i did not  find this dropdownSearchDecoration at first
