### ISSUE TITLE
How can I clean the selection?

### ISSUE THREAD

**Issue by guilherme-faht** [salim-lachdhaf/searchable_dropdown#103]
Hello! I trying to clean the selection by "_form.currentState.reset()", but not works. Pease, how can I clean the selection?

**Comment by vasilich6107** [comment]
changeCurrentItem(null)

https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart#L179

**Comment by guilherme-faht** [comment]
Thank you! Works!

**Comment by vasilich6107** [comment]
@guilherme-faht do not forget to close the issue

**Comment by developerflutter** [comment]
_key.currentState is null!

**Comment by salim-lachdhaf** [comment]
could you past a part of your code
