### ISSUE TITLE
custom messages support required #recommandation #suggestion

### ISSUE THREAD

**Issue by micodev** [salim-lachdhaf/searchable_dropdown#104]
I am really glad for using your package it would be better if you add optional parameter for custom replies it would be very helpful thanks in advance

**Comment by salim-lachdhaf** [comment]
please could you be more specific

**Comment by micodev** [comment]
I mean there are messages that appear like "no data found" etc.... those are constant not dynamic for example I want to change my locale then I can't control those text cause there is no way that I could use to translate it or even use custom one.

**Comment by micodev** [comment]
![image](https://user-images.githubusercontent.com/17555698/104856417-9c8ac680-5923-11eb-9890-3f18f66518ad.png)

**Comment by micodev** [comment]
![err](https://user-images.githubusercontent.com/17555698/104856434-add3d300-5923-11eb-83d4-716aa93276ce.png)

**Comment by salim-lachdhaf** [comment]
no they are not constant, there is `emptyBuilder,` `errorBuilder,` .... , you can customize your widget as you want

**Comment by micodev** [comment]
oh thanks I miss that
