### ISSUE TITLE
Find itemSelected index on item changed

### ISSUE THREAD

**Issue by prooshani** [salim-lachdhaf/searchable_dropdown#105]
Hi everyone,

I have a list of data which returns a value based on my selected item index on changed selected item event.

at onChanged: I need to pass the selected item index to a function to extract some info. but, I can't manage to find the selected item index to pass it to the function.

Any suggestion highly appreciated.

Thanks

**Comment by vasilich6107** [comment]
Scan through the initial list with `yourList.indexWhere((element) => element== onChangedElement)`

**Comment by prooshani** [comment]
> Scan through the initial list with `yourList.indexWhere((element) => element== onChangedElement)`

Thank you @vasilich6107 ,
That piece of code saved my day but, Don't you think when we talk about lists and dropdowns it would be much better if we could get the item's indexes?

Thanks a lot anyway,

**Comment by vasilich6107** [comment]
Technically we could add the selected items need to the onchange callback.
What do you think @salim-lachdhaf ?

**Comment by salim-lachdhaf** [comment]
thank you @vasilich6107 for your response, yes , but this will cause a breaking change !
