### ISSUE TITLE
Cannot search.

### ISSUE THREAD

**Issue by ufukhawk** [salim-lachdhaf/searchable_dropdown#107]
I wanted to use this service in the search for currencies, but cannot be searched. Although there are products in the list, the search result fails.

     `DropdownSearch<Rate>(
                                    mode: Mode.DIALOG,
                                    isFilteredOnline: true,
                                    showClearButton: false,
                                    showSearchBox: true,
                                    label: 'Currency',
                                    dropdownSearchDecoration: InputDecoration(),
                                    autoValidateMode:
                                        AutovalidateMode.onUserInteraction,
                                    validator: (Rate u) {
                                      if (u == null) return "error";
                                      return null;
                                    },
                                    emptyBuilder: (_, __) {
                                      return Center(
                                        child: NormalText(
                                          text: "Empty",
                                        ),
                                      );
                                    },
                                    onFind: (String filter) => getData(filter),
                                    onChanged: (Rate value) {
                                      print(value.currency);
                                    },
                                    dropdownBuilder: _customDropDownExample,
                                    popupItemBuilder:
                                        _customPopupItemBuilderExample,
                                  )
                                  Widget _customPopupItemBuilderExample(
                                      BuildContext context, Rate item, bool isSelected) {
                                    return Container(
                                      margin: EdgeInsets.symmetric(horizontal: 8),
                                      decoration: !isSelected
                                          ? null
                                          : BoxDecoration(
                                              border: Border.all(color: Theme.of(context).primaryColor),
                                              borderRadius: BorderRadius.circular(5),
                                              color: Colors.white,
                                            ),
                                      child: ListTile(
                                        selected: isSelected,
                                        title: Text(item.currency),
                                      ),
                                    );
                                  }
                                
                                  Widget _customDropDownExample(
                                      BuildContext context, Rate item, String itemDesignation) {
                                    return Container(
                                      child: ListTile(
                                        contentPadding: EdgeInsets.all(0),
                                        title: Text(item != null ? item.currency : _selectAllExchange.currency),
                                      ),
                                    );
                                  }
                                
                                  Future<List<Rate>> getData(String filter) async {
                                    print(filter);
                                    if (filter.isNotEmpty) {
                                      var list = toExchangeRateList.currencyQuery.currencyRates.rates
                                          .where((element) => element.currency
                                              .trim()
                                              .toLowerCase()
                                              .contains(filter.trim().toLowerCase()))
                                          .toList();
                                      return list;
                                    } else
                                      return toExchangeRateList.currencyQuery.currencyRates.rates;
                                  }`

**Comment by ufukhawk** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.1 20C69 darwin-x64, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by ufukhawk** [comment]
i solved.

**Comment by RodrigoScott** [comment]
how can you solved?

**Comment by faisalmushtaq007** [comment]
@ufukhawk  how did you do it???

**Comment by AliRezaBeitari** [comment]
@ufukhawk How did you fix this problem?!
