### ISSUE TITLE
add focus

### ISSUE THREAD

**Issue by BangPei** [salim-lachdhaf/searchable_dropdown#108]
hi, can we set autofocus or requestFocus?

**Comment by salim-lachdhaf** [comment]
on what ?

**Comment by BangPei** [comment]
i'm developing web using flutter, i want to set dropdown search as first focus in initState

**Comment by salim-lachdhaf** [comment]
for now you can only check whatevee it is checked or not.
i will add a parameter for that in the next version v 0.5.0

**Comment by kateile** [comment]
@salim-lachdhaf hi, can I use autofocus with `DropDownDecoratorProps`? 
I need it to open as soon as widget is viewed
