### ISSUE TITLE
Gap between dropdown and input if validation error displayed

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/searchable_dropdown#11]
![01667c21cb6db8f78de4261d2edbee8f](https://user-images.githubusercontent.com/6721286/83749223-0c399300-a66c-11ea-846b-81ef6bd49e07.jpg)

**Comment by salim-lachdhaf** [comment]
This is not a bug, it's a normal behavior, the validation error message should be shown to the user 
to help him in his selection.

**Comment by vasilich6107** [comment]
It would be great to make it configurable)

**Comment by salim-lachdhaf** [comment]
the error text if exist it's a part of the `dropdownSearch` and dhould be always visible to user, so i will keep the current behavior.
