### ISSUE TITLE
Validator call

### ISSUE THREAD

**Issue by cladvd** [salim-lachdhaf/searchable_dropdown#110]
Is correct the call to 'validator' function during the first show or am I setting up the 'SearchableDropdown.single' inwrong way? Follows the current declaration:

`
SearchableDropdown.single(
            items: items,
            value: type,
            hint: "Select",
            onChanged: (value) {
              setState(() {
                changedValue = value;
              });
            },
            validator: (String item) {
              if (item == null)
                return "Select a valid item";
              else
                return null;
            },
            isExpanded: true,
          ),
`

With this, I see the error at the init of the component

**Comment by salim-lachdhaf** [comment]
`SearchableDropdown.single` the plugin does not contains this
