### ISSUE TITLE
support rtl 

### ISSUE THREAD

**Issue by ajnaf** [salim-lachdhaf/searchable_dropdown#114]
content padding doesn't support  rtl

**Comment by salim-lachdhaf** [comment]
not clear

**Comment by salim-lachdhaf** [comment]
waiting for more details

**Comment by salim-lachdhaf** [comment]
no response.

**Comment by ronytesler** [comment]
@salim-lachdhaf This is an rtl example:
![image](https://user-images.githubusercontent.com/9344207/112654658-aae3ea00-8e60-11eb-8c4a-f1c343e209dd.png)
How do I add padding to the text?

**Comment by ajnaf** [comment]
> @salim-lachdhaf This is an rtl example:
> ![image](https://user-images.githubusercontent.com/9344207/112654658-aae3ea00-8e60-11eb-8c4a-f1c343e209dd.png)
> How do I add padding to the text?

I just changed it directly in the plugin 😅😅😅
