### ISSUE TITLE
Support lazy loading api on line

### ISSUE THREAD

**Issue by Williamredondo** [salim-lachdhaf/searchable_dropdown#115]
Support lazy loading api on line

**Comment by salim-lachdhaf** [comment]
ok nice feature. we will try to add it in the next release

**Comment by sunny285** [comment]
pl

> ok nice feature. we will try to add it in the next release

please release it.

**Comment by sunny285** [comment]
> ok nice feature. we will try to add it in the next release

also, can we use pagination in this package?
if we can then please really and
 if we can not 
then still please still reply :)

**Comment by salim-lachdhaf** [comment]
both pagination and lazy load are not available feature for now

**Comment by salim-lachdhaf** [comment]
for now limit your query in the API result.., and use `FiltredOnline : true`

**Comment by sunny285** [comment]
Ok
