### ISSUE TITLE
Error: 'onlineItems.addAawait' can't be used as a type because 'onlineItems' doesn't refer to an import prefix.

### ISSUE THREAD

**Issue by Komche** [salim-lachdhaf/searchable_dropdown#119]
I recently found out about this plugin and it was only working two days ago I got this error when compiling an apk Error: 'onlineItems.addAawait' can't be used as a type because 'onlineItems' doesn't refer to an import prefix.

**Comment by Komche** [comment]
`flutter doctor -v`

`[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.6 19G73 darwin-x64, locale fr-FR)
    • Flutter version 1.22.5 at /Users/mac/development/flutter
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • LM V350 (mobile) • LMV350AWM4cd3e441 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!`

**Comment by salim-lachdhaf** [comment]
there is no fn named `onlineItems.addAawait`. please clean your cache ...
