### ISSUE TITLE
cannot able to add focusNode which can be very useful

### ISSUE THREAD

**Issue by Mehedi50200** [salim-lachdhaf/searchable_dropdown#123]

**Comment by salim-lachdhaf** [comment]
how ?

**Comment by afuentes-rjb** [comment]
Same thing. Adding Focus node will be very useful. I am using this on my project and would be useful to have this feature for validation.

I have this sample code of what usage would like 

class _FormBuilderCountryFieldState extends State<FormBuilderDatePickerField> {

  Country? selectedCountry;
  FocusNode countryFocusNode = new FocusNode();
  FocusNode textFormFieldFocusNode = new FocusNode();

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        DropdownSearch<Country>(
          focusNode: selectedCountry,
          showSelectedItem: false,
          items: countryList,
          showSearchBox: true,
          dropdownSearchDecoration: InputDecoration(
            labelText: widget.labelText,
            border: InputBorder.none,
            enabledBorder: InputBorder.none,
            disabledBorder: InputBorder.none,
            contentPadding: EdgeInsets.only(left: 3, bottom: 0, top: 0, right: 5)
          ),
          onChanged: (country) {
           
          },
          selectedItem: selectedCountry,
          dropdownBuilder: (BuildContext context, Country? item, String itemDesignation) {
            return Container(
              child: (item == null)
                  ? ListTile(
                      contentPadding: EdgeInsets.all(0),
                      title: Text("Country"),
                    )
                  : ListTile(
                      leading: CountryPickerUtils.getDefaultFlagImage(selectedCountry ?? item),
                      contentPadding: EdgeInsets.all(0),
                      title: Text(selectedCountry?.name.toString() ?? item.name.toString()),
                    ),
            );
          },
          popupItemBuilder: _customPopupItemBuilderExample,
        ),
        TextFormField(
          decoration: InputDecoration(
            border: UnderlineInputBorder(),
            labelText: 'First Text Box'
          ),
          focusNode: textFormFieldFocusNode,
        ),   
        SizedBox(height: 300),
        TextFormField(
          decoration: InputDecoration(
            border: UnderlineInputBorder(),
            labelText: 'Last Text Box'
          ),
        ),       
        RaisedButton(
          child: Text('Focus to DateTimePicker'),
          onPressed: () {
            countryFocusNode.requestFocus();
          },
        ),
        RaisedButton(
          child: Text('Focus to TextFormfield'),
          onPressed: () {
            textFormFieldFocusNode.requestFocus();
          },
        ),
      ],
    );
  }

  Widget _customDropDownExample(BuildContext context, Country? item, String itemDesignation) {
    return Container(
      child: (item == null)
          ? ListTile(
              contentPadding: EdgeInsets.all(0),
              title: Text("Select Country"),
            )
          : ListTile(
              leading: CountryPickerUtils.getDefaultFlagImage(item),
              contentPadding: EdgeInsets.all(0),
              title: Text(item.name.toString()),
            ),
    );
  }

  Widget _customPopupItemBuilderExample(BuildContext context, Country? item, bool isSelected) {
    return Container(
      child: ListTile(
        selected: isSelected,
        title: Text(item!.name),
        leading: CountryPickerUtils.getDefaultFlagImage(item)
      ),
    );
  }
}
