### ISSUE TITLE
default height works as if the items length = 4

### ISSUE THREAD

**Issue by kareemX** [salim-lachdhaf/searchable_dropdown#125]
hey, first I wanna say it's an incredible package
I have an weird bug
default height works as if the items length = 4, so in order to get it right I have to edit 'maxheight' manually, I think it should get the height dynamically depending on the items length so I don't know what is wrong?

**Comment by salim-lachdhaf** [comment]
it is not a bug , we make for now a default height that you can edit it if you want depending on your data.
we will try in the next versions to make it dynamically.

**Comment by kareemX** [comment]
Thanks for responding 
Ya dynamically will be great
