### ISSUE TITLE
Value Instead Of Object 

### ISSUE THREAD

**Issue by maanhaider** [salim-lachdhaf/searchable_dropdown#128]
how to get just value instead of object after selection?

**Comment by salim-lachdhaf** [comment]
not clear, please give us an example

**Comment by maanhaider** [comment]
> not clear, please give us an example

I am using a list of objects having id and label. What i want is that when i select it gives only id on selection instead of whole object how i can do that in it because in edit form i only get the id from server and in this scenario  i have to search that specific object in the list and then pass it as selected value ?

**Comment by vasilich6107** [comment]
You can pass a list of id’s in dropdown.
Make a map Id=>value and display a value through the builder accessing the map via closure

**Comment by robman70** [comment]
Hi, I have the same problem but I don't understand how I can choose what to show.
My dropdown receives a list of object so I can search in this list usinf DropdownSearch but, when I select an item from this list, my dropdowns shows an object ... which property do I need to change to display a particular property of the selected object and not the object itself?
