### ISSUE TITLE
Exceptions in onFind are suppressed

### ISSUE THREAD

**Issue by oTree-org** [salim-lachdhaf/searchable_dropdown#133]
I have an onFind function as described in the docs:

```
onFind: (String filter) => getData(filter),
```

It works fine, except when an exception occurs in `getData` (such as 1/0), no error is raised. I just get this when I tap on the menu:

> "NoSuchMethodError: the getter 'iterator' was called on null"

Is this the expected behavior?

**Comment by salim-lachdhaf** [comment]
ah ok, you mean if a error raised in `getData()` it will not be handled by the plugin and it makes it crashes ?

**Comment by oTree-org** [comment]
Hi, thanks for the reply. I'm using version 0.5.0.

The problem is that when an error occurs, I don't get any traceback in the console. It seems the plugin is catching the error and outputting it as a string into the dropdown menu window, but this just shows the error string, not the stack trace and line numbers, which have the info I need to debug my issue. 

I would prefer if the plugin didn't handle the exception.

**Comment by salim-lachdhaf** [comment]
here you are talking as developer , however, the final destination of the plugin is the user, here we have to show something to user to make him understand the issue. simple example ; what if there is no internet connexion !? is it better to inform the user in the UI or crash the app !? whithout given him any information ?

maybe i will add a `print(error)` to print the stack in the console, not other then that

**Comment by salim-lachdhaf** [comment]
check the next version 0.5.1 in the next days.
