### ISSUE TITLE
showSearchBox defaults to false?

### ISSUE THREAD

**Issue by oTree-org** [salim-lachdhaf/searchable_dropdown#134]
Hi, I just wonder why showSearchBox defaults to false? If the addon is called searchable_dropdown, it seems that having a search box is the main point, right? :) (I was confused at first why no keyboard popped up when I tap the menu.)

**Comment by ronytesler** [comment]
Same here

**Comment by salim-lachdhaf** [comment]
because it's depend on the size of your data.
if you need it it is simple just set it to true.

searchable is a feature, this is not meaning that searchBox will be visible by default !
