### ISSUE TITLE
docs are not clear

### ISSUE THREAD

**Issue by ronytesler** [salim-lachdhaf/searchable_dropdown#136]
I'd expect 'items' to be the list with all options and 'onFind' to filter them.
I see that I don't need both, I just need one of them. I see that 'onFind' is for api calls and 'items' is for offline items.
Am I correct? And I guess 'isFilteredOnline' also has some affect on these.

**Comment by salim-lachdhaf** [comment]
both items and onFind are already used on the plugin example and well described on github docs ! just scroll down ! ....
and yes , isFilteredOnline also described on the plugin and on the docs on github !

> true if the filter on items is applied onlie (via API)
