### ISSUE TITLE
Search hint appears on the dropdown box and not the in the search text

### ISSUE THREAD

**Issue by ronytesler** [salim-lachdhaf/searchable_dropdown#138]
Shouldn't the search hint appear where the user types?
like here:
![image](https://user-images.githubusercontent.com/9344207/112681892-5fd9cf00-8e80-11eb-9966-291eeeebbdc0.png)

**Comment by salim-lachdhaf** [comment]
not clear

**Comment by ronytesler** [comment]
Sure:
![image](https://user-images.githubusercontent.com/9344207/112703853-76e0e700-8ea9-11eb-86ad-b1ab0dce4ba3.png)

I'd want the 'hint' to be in the search box.

**Comment by salim-lachdhaf** [comment]
````
searchBoxDecoration: InputDecoration(
                  border: OutlineInputBorder(),
                  contentPadding: EdgeInsets.fromLTRB(12, 12, 8, 0),
                  hintText: "hint goes here",
                )

````

**Comment by girjesXencov** [comment]
how to give hint text to dropdown , search hint is working but dropdown hint is not working?
