### ISSUE TITLE
Keyboard type for dropdown search

### ISSUE THREAD

**Issue by tk512** [salim-lachdhaf/searchable_dropdown#142]
Is it possible to set the keyboard type for dropdown search?
I would like to only be able to show digits when using the dropdown on mobile.  This is possible using a TextField.

**Comment by vasilich6107** [comment]
https://github.com/salim-lachdhaf/searchable_dropdown/issues/113

**Comment by salim-lachdhaf** [comment]
this feature will be added in 0.5.1.

**Comment by tk512** [comment]
Great @salim-lachdhaf . I am available to test if you have a branch you are working in.
