### ISSUE TITLE
how to fix searchable drop down issue in landscape ,

### ISSUE THREAD

**Issue by Veerendra-UI** [salim-lachdhaf/searchable_dropdown#143]
in one of the my project i'm using this package , now facing some issue like pixel overflow  bottom error how to fix?
![Screenshot_1617165747](https://user-images.githubusercontent.com/80522506/113092035-d709bd00-920a-11eb-8108-61b67c5bf766.png)

**Comment by salim-lachdhaf** [comment]
well here i see three solutions:
1- prevent lanscape mode.
2 - make the keyboard shows on top of the dialog
3- make title smaller or remove it.

**Comment by vasilich6107** [comment]
@Veerendra-UI you can also try to use bottom sheet mode.
It seems that currently you are using DIALOG mode which adds additional padding which steals the space without any benefit.
This will give you additional space for you controls.

**Comment by Veerendra-UI** [comment]
@salim-lachdhaf  thank you I chose the third solution.
