### ISSUE TITLE
How to add a Scrollbar to the dropdown list?

### ISSUE THREAD

**Issue by jaimevaqueiro** [salim-lachdhaf/searchable_dropdown#144]
Hi,

What would be the easiest way to add a scrollbar to the list of items? I'm thinking I should define a custom dropdownBuilder function. Is this correct? Any pointers in the right direction will be appreciated.

Thanks

**Comment by cokuscz** [comment]
how to add scrollbar bro?

**Comment by vasilich6107** [comment]
@jaimevaqueiro check #173

**Comment by salim-lachdhaf** [comment]
this feature will be released in the next version
check this PR
https://github.com/salim-lachdhaf/searchable_dropdown/pull/173
