### ISSUE TITLE
Data lost

### ISSUE THREAD

**Issue by joharputr** [salim-lachdhaf/searchable_dropdown#145]
bug data lost after search and tap back button 
version 0.4.9

📎
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /root/snap/flutter/common/flutter
    • Framework revision 1aafb3a8b9 (5 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/johar/Apps/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

https://user-images.githubusercontent.com/32647004/113969801-db178980-985f-11eb-86c6-182ff3ad7add.mp4

**Comment by salim-lachdhaf** [comment]
please use v0.6.1
