### ISSUE TITLE
How To Leave Dropdown Open?

### ISSUE THREAD

**Issue by code-4-bread** [salim-lachdhaf/searchable_dropdown#149]
Is it possible to leave the dropdown open after making a selection?

**Comment by salim-lachdhaf** [comment]
well even on general conception of dropdown , always dropdowns get closed after selecting a item,why this need !

**Comment by code-4-bread** [comment]
> well even on general conception of dropdown , always dropdowns get closed after selecting a item,why this need !

Use the dropdown for Multi-select as well and wanted to know if there is a way.

**Comment by salim-lachdhaf** [comment]
ah ok, sadly for now the plugin did not support the multi selection (we are working on that).
