### ISSUE TITLE
Is it possible to avoid full screen when the keyboard is visible?

### ISSUE THREAD

**Issue by Alyahya-A** [salim-lachdhaf/searchable_dropdown#15]
Hi.. Thank you for this amazing plugin, you developed this plugin as I need for my app, thank you a lot..

I have one question.
Is it possible to avoid full screen when the keyboard is visible?

**Keyboard is visible:**

<img width="384" alt="Screen Shot 2020-06-07 at 07 54 33 AM" src="https://user-images.githubusercontent.com/41841188/83960744-f5c25000-a894-11ea-8c08-9d8193404c7f.png">

When the keyboard is visible I want to be like this:

<img width="383" alt="Screen Shot 2020-06-07 at 07 56 29 AM" src="https://user-images.githubusercontent.com/41841188/83960777-4f2a7f00-a895-11ea-8e0e-13368ebdc601.png">

I tried to detect when the keyboard is visible, if is visible I reduce the height, but the height didn't change (I used StatefulWidget).

**Comment by salim-lachdhaf** [comment]
Hi, are using a dialog or a bottomSheetModal ?

**Comment by Alyahya-A** [comment]
I'm using ```BOTTOM_SHEET```

**Comment by salim-lachdhaf** [comment]
sadly for now i have no solution for that, this problem does not exist if we use `showBottomSheet` but this is not dissmissable as a dialog ...
have you any suggession to resolve that ?

**Comment by Alyahya-A** [comment]
Actually I like it when it's full screen. Can you add padding in the top if the keyboard is visible?
May be by using: [keyboard_visibility](https://pub.dev/packages/keyboard_visibility) and ```showModalBottomSheet<void>()```

**Comment by salim-lachdhaf** [comment]
Any of this solutions want works, because the `bottomSheetModal` takes full screen, even at first launch it seems ok, after scrolling it overcross the title bar ..., maybe the best solution is to customuze `showBottomSheet` to behave like a modal , instead of `showModalBottomSheet`

**Comment by Alyahya-A** [comment]
I developed a test, it's work good for me.
When the keyboard is visible it will be full screen with 40 top padding.  

And I called ```_showSearchBottomSheet()```  in 
```
TextFormField(
    ...
    ...
    onTap :_showSearchBottomSheet,
    ...
    ...
)
```

Full code:
```
...
...

class _SearchSheetState extends State<SearchSheet> {
  bool _keyboardVisible;

  @override
  void initState() {
     _keyboardVisible = false;
    KeyboardVisibilityNotification().addNewListener(
      onChange: (bool visible) {
        setState(() {
          _keyboardVisible = visible;
        });
      },
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return bottomDrawer();
  }

  Widget bottomDrawer() {
    return Container(
      child: Column(
        children: <Widget>[
          SizedBox(height: _keyboardVisible ? 40 : 15), // Top padding
          Center(
            child: Container(
              height: 5,
              width: 50,
              padding: EdgeInsets.only(top: 5),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.all(Radius.circular(100)),
                gradient: LinearGradient(
                  begin: Alignment.centerLeft,
                  end: Alignment.centerRight,
                  colors: [
                    Consts.MAIN_COLOR2,
                    Consts.MAIN_COLOR1,
                  ],
                ),
              ),
            ),
          ),
          SizedBox(height: 15),  
          Text(
            AppLocalizations.of(context).translate('select_city'),
            style: TextStyle(
              color: Consts.MAIN_COLOR3,
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(10.0),
            child: CustomTextField( // Search textfield
              label: 'search_city',
              textInputType: TextInputType.text,
            ),
          ),
          SizedBox(height: 15),
          Container(
            height: !_keyboardVisible
                ? MediaQuery.of(context).size.height * .5
                : MediaQuery.of(context).size.height,
            child: ListView.builder(
              itemCount: 100,
              itemBuilder: (context, i) {
                return ListTile(
                  title: Text("Item $i"),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
```

To show the sheet:
```

void _showSearchBottomSheet() {
    showModalBottomSheet<void>(
        isScrollControlled: true,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(30),
            topRight: Radius.circular(30),
          ),
        ),
        backgroundColor: Colors.white,
        context: context,
        builder: (BuildContext context) {
          return SingleChildScrollView(child: ConfirmSheet());
        }).whenComplete(() {
      ...
      ...
    });
  }
```

The only problem here is all the code depend on keyboard_visibility plugin, and I don't know if it's work fine in all devices or not. I have production app in the store and the plugin work fine.

**Comment by salim-lachdhaf** [comment]
Could you make a pull request to test, because as i see you are working on ios and i'm testing on Android. However i have two opinions:
- remove the keyboard visibility and use always 40 padding , it will not cause problem in any way.
- after my testing , i think even your solution won't work as you wish, because you see what you wanna see only on the first launch, but il you try to scroll (the bottomSheet not the list) you will see that the old behavior still exist and it takes the full screen. I'm pretty sure that this solution will cause problem in some device, try landscape mode on your phone ;)

Let me know about the second point.
