### ISSUE TITLE
Custom Show "No Data Found" on getting empty list from onFind : _someMethod()

### ISSUE THREAD

**Issue by AmbujaAK** [salim-lachdhaf/searchable_dropdown#151]
on clicking dropdown, i wanna show, "type 3 letters to search", on clicking if API is not returning any data, then message should be "No Data Found".

**Comment by salim-lachdhaf** [comment]
you can use `emptyBuilder` paramater for that

**Comment by AmbujaAK** [comment]
I used this, but not working perfectly. can you give me an example for that ??

**Comment by salim-lachdhaf** [comment]
how that ? please past a part of your code
