### ISSUE TITLE
dropdownSearchDecoration contentPadding not working properly

### ISSUE THREAD

**Issue by DhavalRKansara** [salim-lachdhaf/searchable_dropdown#152]
> order: OutlineInputBorder()
@salim-lachdhaf 

**Solution A(Set content padding as 0):**
```
<img width="324" alt="Screen Shot 2021-04-27 at 8 29 34 PM" src="https://user-images.githubusercontent.com/44993081/116264427-e80d0600-a797-11eb-8f9c-1b6c8a25fb27.png">: InputDecoration(
          contentPadding: EdgeInsets.all(0),
          labelStyle: TextStyle(color: Colors.indigo),
          isDense: true,
          enabledBorder: OutlineInputBorder(
              borderSide: BorderSide(
            color: Theme.of(context).primaryColor,
            width: 2.0,
          ))),
```

- Using solution A I am facing the below UI issue with dropdownSearchDecoration:

<img width="362" alt="Screen Shot 2021-04-27 at 8 30 24 PM" src="https://user-images.githubusercontent.com/44993081/116264247-c4e25680-a797-11eb-9195-b6223d5e457d.png">

**Solution B(Removed content padding):**
```
dropdownSearchDecoration: InputDecoration(
          labelStyle: TextStyle(color: Colors.indigo),
          isDense: true,
          enabledBorder: OutlineInputBorder(
              borderSide: BorderSide(
            color: Theme.of(context).primaryColor,
            width: 2.0,
          ))),
```

- Using solution B I am facing the below UI issue with(extra space around the content):

<img width="324" alt="Screen Shot 2021-04-27 at 8 28 58 PM" src="https://user-images.githubusercontent.com/44993081/116264504-f78c4f00-a797-11eb-9ec4-cb76405f038b.png">

- Event if I add some left padding then it will add padding in my value content too.
_Originally posted by @DhavalRKansara in https://github.com/salim-lachdhaf/searchable_dropdown/issues/2#issuecomment-827679029_

**Comment by salim-lachdhaf** [comment]
could you test using `showAsSuffixIcons` to true and lete know of it works for you

**Comment by DhavalRKansara** [comment]
> showAsSuffixIcons

Yes, I tried with `showAsSuffixIcons` to `true` with both solutions and it's not working...

**Comment by salim-lachdhaf** [comment]
if you pass a simple `String` to the plugin is there any issue (without flag and without customization)? 

if there is no issue, please then past your dropDownBuilder

**Comment by DhavalRKansara** [comment]
I have tried by passing simple strings and it's working fine with it, I am sharing the dropDownBuild code here:

```
dropdownBuilder:
          (BuildContext context, Country country, String itemDesignation) {
        return ListTile(
            title: Text(
              "${country.flag}  ${country.name} (${country.dialCode})",
              style: TextStyle(fontSize: 16),
            ),
          );
      },

```

**Comment by salim-lachdhaf** [comment]
first , try without using `listTile,` if it did not work could you pass the content of `contry.flag`

**Comment by DhavalRKansara** [comment]
After Removing Listtile it's working properly... Thanks @salim-lachdhaf
