### ISSUE TITLE
remove border from search box

### ISSUE THREAD

**Issue by alexlovar** [salim-lachdhaf/searchable_dropdown#153]
Hello, i try to remove border from searchbox and add radius with no luck:
i'm applying this decoration.

` searchBoxDecoration: InputDecoration(
                                                        border: InputBorder.none,
                                                        focusedBorder: InputBorder.none,
                                                        enabledBorder: InputBorder.none,
                                                        errorBorder: InputBorder.none,
                                                        disabledBorder: InputBorder.none,
                                                        contentPadding: EdgeInsets.fromLTRB(12, 12, 8, 0),

                                                      ),`

however the border is not removed from the box.

i'm trying to get something like this:
![image](https://user-images.githubusercontent.com/20868783/116498594-b1a2ba00-a86f-11eb-890d-bdd9527f8747.png)

**Comment by salim-lachdhaf** [comment]
some updates comes here which will be released in the next version 
https://github.com/salim-lachdhaf/searchable_dropdown/pull/171
