### ISSUE TITLE
Right-align selected item

### ISSUE THREAD

**Issue by svsno1** [salim-lachdhaf/searchable_dropdown#154]
How can I right-align the selected item?

**Comment by salim-lachdhaf** [comment]
you can use `popupItemBuilder(BuildContext context, T item, bool isSelected)` , see the example page for an example.

**Comment by svsno1** [comment]
I don't mention the popup item.
I want to right-align the current text in the box.

**Comment by salim-lachdhaf** [comment]
in that case you can simply use: `dropdownBuilder`

**Comment by svsno1** [comment]
Thank you very much, Salim.
