### ISSUE TITLE
Menu does not resize with view (Desktop, Web)

### ISSUE THREAD

**Issue by kenthinson** [salim-lachdhaf/searchable_dropdown#159]
The menu does not resize with the app on Web / Desktop. Just drag the window to resize the app and see the result.
![Screen Shot 2021-05-07 at 4 28 17 PM](https://user-images.githubusercontent.com/2245494/117510325-7ed48200-af51-11eb-9c7b-05186cad8968.png)
![Screen Shot 2021-05-07 at 4 28 29 PM](https://user-images.githubusercontent.com/2245494/117510329-7f6d1880-af51-11eb-9013-b1e707ee205f.png)

**Comment by vasilich6107** [comment]
@kenthinson check this sample from flutter docs and try to resize the web browser window
https://api.flutter.dev/flutter/material/DropdownButton-class.html

This package is implemented similar way as `DropdownButton`

**Comment by salim-lachdhaf** [comment]
duplicated https://github.com/salim-lachdhaf/searchable_dropdown/issues/84
