### ISSUE TITLE
How do I change the label color.

### ISSUE THREAD

**Issue by panchalAlpit** [salim-lachdhaf/searchable_dropdown#16]
I'm not able to change label color or label text style,
label: "State",

**Comment by salim-lachdhaf** [comment]
You can customize `dropdownSearchDecoration`

check examples here : https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart

**Comment by panchalAlpit** [comment]
Thank you, bro, for help.
the issue is fixed.
