### ISSUE TITLE
"Multiple widgets used the same GlobalKey" after clicking search box?

### ISSUE THREAD

**Issue by developerflutter** [salim-lachdhaf/searchable_dropdown#160]
I am facing the error "Multiple widgets used the same GlobalKey" when I start searching something and the screen goes to blank! Whats the issue with this?

**Comment by vasilich6107** [comment]
@developerflutter reproduction code please)

**Comment by salim-lachdhaf** [comment]
@developerflutter are you using the same `key` in the `itemBuilder` !?

**Comment by salim-lachdhaf** [comment]
no response.
