### ISSUE TITLE
Keyboard hides the search box ?

### ISSUE THREAD

**Issue by developerflutter** [salim-lachdhaf/searchable_dropdown#162]
I have multiple dropdown_search in a screen and when keyboard opens the search box is hidden!

**Comment by developerflutter** [comment]
mode: Mode.MENU,

**Comment by vasilich6107** [comment]
@developerflutter could you read this comment https://github.com/salim-lachdhaf/searchable_dropdown/issues/150#issuecomment-840082887

The main issue here that you try to use desktop-like approach on device with limited screen space.

**Comment by vasilich6107** [comment]
@salim-lachdhaf technically this is duplicate of issue #150

**Comment by salim-lachdhaf** [comment]
duplicated https://github.com/salim-lachdhaf/searchable_dropdown/issues/150
