### ISSUE TITLE
Mode.BOTTOM_SHEET ignores custom theme of app

### ISSUE THREAD

**Issue by na-si** [salim-lachdhaf/searchable_dropdown#163]
Hello!
We migrated to nullsafety version of library and unfortunately I found problem on library side.

`_openBottomSheet(data)` method contains `MaterialApp` inside.

```
 Future<T?> _openBottomSheet(T? data) {
    return showModalBottomSheet<T>(
        barrierColor: widget.popupBarrierColor,
        backgroundColor: Colors.transparent,
        isScrollControlled: true,
        shape: widget.popupShape,
        context: context,
        builder: (ctx) {
          return MaterialApp(
            debugShowCheckedModeBanner: false,
            builder: (_, child) {
              return SafeArea(
                top: widget.popupSafeArea.top,
                bottom: widget.popupSafeArea.bottom,
                left: widget.popupSafeArea.left,
                right: widget.popupSafeArea.right,
                child: Container(
                  color:
                      widget.popupBackgroundColor ?? Theme.of(ctx).canvasColor,
                  child: _selectDialogInstance(data, defaultHeight: 350),
                ),
              );
            },
          );
        });
```
It is the reason why my theme is ignored. This problem is only with Mode.BOTTOM_SHEET, other modes work perfectly.
Please, could someone fix it?
This MaterialApp should be removed from here.
Thanks a lot

Edit: Sorry, forgot to mention version of library [0.6.1] - 2021.05.02

**Comment by salim-lachdhaf** [comment]
we will try to fix that, thank you for reporting that

**Comment by salim-lachdhaf** [comment]
@vasilich6107 could you check this, the safe area applied on bottomSheet caused this regression (adding materialApp erases the plugin theme, if possible to pass app theme to that MaterialApp)

**Comment by vasilich6107** [comment]
ok
