### ISSUE TITLE
hide dropdown button icon

### ISSUE THREAD

**Issue by YouSour** [salim-lachdhaf/searchable_dropdown#166]
hi , i'm using searchable_dropdown , i got some problem , i don't know how can i hide or remove dropdown button icon ?

**Comment by salim-lachdhaf** [comment]
you can override `dropDownButton` and set it to empty `Container` for example

**Comment by YouSour** [comment]
@salim-lachdhaf hi, yeah i try it , but it still has hover , and my text won't go to center 😄 
![Screen Shot 2021-05-18 at 7 54 36 AM](https://user-images.githubusercontent.com/9318106/118575236-30747e00-b7b0-11eb-9623-ee213ff72350.png)

**Comment by salim-lachdhaf** [comment]
yeap, what if you use `showAsSuffixIcons` and `dropDownButton` to `null` or empty `Container`
