### ISSUE TITLE
Allow to type within the Dropdown.

### ISSUE THREAD

**Issue by AhmadRehan71** [salim-lachdhaf/searchable_dropdown#167]
For Searching we have to set value of showSearchBox to true, And it provides additional searchbox in DropDownMenu, Please allow to search query within the DropDownSearch Widget.

**Comment by salim-lachdhaf** [comment]
sorry , i didn't under stand your need

**Comment by AhmadRehan71** [comment]
Sorry, If I'm not able to clarify my point of view, Here in the Screenshot
![Screenshot_20210519-122509](https://user-images.githubusercontent.com/56255944/118772992-cb975180-b89d-11eb-9663-14ecfc840620.jpg)
These is a DropDownButton ("Select User...",), when we click it a menu opens and it also provides a TextField (Within the menu) ("Type your fanbase name...") to type query for searching items based on typed text. Everything is working fine, But can you provide the feature so we can directly type query on the DropDownButton ( where the hint "Select User..." is written in screenshot) and it seach the items in menu based on query.
I hope you understand my point.

**Comment by salim-lachdhaf** [comment]
you can use

**Comment by salim-lachdhaf** [comment]
you can use `searchBoxController:TextEditingController(text:'past user name to search')`

**Comment by salim-lachdhaf** [comment]
you can use `searchBoxController:TextEditingController(text:'past user name to search')`

**Comment by daianaboia** [comment]
I don't think this issue has been solved, I also want to be able to type directly in the first empty bar to search and don't have a second one 
![image](https://user-images.githubusercontent.com/82261607/185102550-315665ba-88c2-4d07-adc9-685d594a5675.png)
Is this possible?

**Comment by abdallah-odeh** [comment]
same here, I believe that it would be a better UX

**Comment by KiddoV** [comment]
Any update on this?
