### ISSUE TITLE
Issue when creating the dropdown list asynchronously from an offline location.

### ISSUE THREAD

**Issue by inimaga** [salim-lachdhaf/searchable_dropdown#168]
Hello!

I am trying to build a dropdown list from an asychronous function and have tried using "onFind" as per documentation. However I keep getting the error;  `"type List<Object> is not a subtype of List<String>"`. The list of strings is being fetched from a local sqflite database. As such, the returned list is always a Future<List>. 

Below is the excerpt of my code:

```
DropdownSearch<String>(
                mode: Mode.DIALOG,
                showSelectedItem: true,
                showSearchBox: true,
                onFind: (String filter) async {
                  var data = await DBHelper.getGnCities();
                  return data;
                },
                label: "Location",
                onChanged: print,
                selectedItem: null,
)
```

Why is it insistent on creating and returning a list of objects rather than accepting a List of Strings as the offline parameter "items:" would?

Am I missing something?
Many thanks for your help. :)

**Comment by salim-lachdhaf** [comment]
you request `DropdownSearch<String>` , so you have to pass a `list<String>` as items , 
so here you have to make sure that
 `var data = await DBHelper.getGnCities()` 
return a list of `String`

**Comment by inimaga** [comment]
Hi Salim, 

It is indeed returning a list of Future string. 

For testing, I changed it to:
`var data = ["item 1","item two","item 3"]`

and I still get the same error.

**Comment by inimaga** [comment]
Okay nevermind. It was my fault. All sorted now.
