### ISSUE TITLE
Onchanged method refresh the DropdownSearch widget.

### ISSUE THREAD

**Issue by panchalAlpit** [salim-lachdhaf/searchable_dropdown#17]
The DropdownSearch  "OnChanged" inside I implement an API call method but when I scroll the view, DropdownSearch widget is refreshing and sets label value and remove the selected item.

**Comment by salim-lachdhaf** [comment]
could you pass an example for your issue ? because your issue is not clear.

**Comment by panchalAlpit** [comment]
DropdownSearch<StatelistModel>(
items: liststate,
onChanged: (StatelistModel data) {
                  print(data);
                    CityAPICall();
                },
)
Here's I call the cityAPIcall method for another DropdownSearch<CitylistModel>, and both DropdownSearch I used inside the Singlechildscroll. after selecting the  DropdownSearch<StatelistModel> value and scrolling the view(screen), so my selecting  DropdownSearch<StatelistModel> value is removed or change to default or label value.

**Comment by salim-lachdhaf** [comment]
not clear yet, could you show me what's inside `CityAPICall();`

**Comment by panchalAlpit** [comment]
Future<List<CitylistModel>> CityAPICall() async {
final response = await http.post(url, body: payload);
Map<dynamic, dynamic> data = jsonDecode(response.body);
    {
      List decryptedparams = await decryptingListParam(data["data"]);
      decryptedparams.forEach((element) {
        CitylistModel sss = CitylistModel.formjson(element);
        listbank.add(sss);
      });
    }
}

**Comment by salim-lachdhaf** [comment]
I see NO relation between onChanged() and apiCall(), and not relation for the other dropdownSearch, i think that you have miss something or you have badly implemented the dropdown search.
If it's possible to pass all the statefull or stateless widget

**Comment by panchalAlpit** [comment]
Now I have fixed this error.
_callCityApi = CityListAPi();

**Comment by panchalAlpit** [comment]
> I see NO relation between onChanged() and apiCall(), and not relation for the other dropdownSearch, i think that you have miss something or you have badly implemented the dropdown search.
> If it's possible to pass all the statefull or stateless widget

I have fixed this issue.
_callCityApi = CityListAPi();
