### ISSUE TITLE
SafeArea gap

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/searchable_dropdown#170]
Hi, @salim-lachdhaf 

I noticed that you've changed the implementation of safe area 

This change causes transparent gap underneath the safe area

Could you clarify the reason of this change?

![image](https://user-images.githubusercontent.com/6721286/119224481-444d1680-bb07-11eb-942e-c8fb8e68da42.png)

**Comment by salim-lachdhaf** [comment]
i tested both solution and i found that both gives same result, so i optimized

**Comment by vasilich6107** [comment]
The initial solution kept “gap” the same color as whole list. To my mind it is more natural behavior for “bottom sheet”
