### ISSUE TITLE
Dropdown button has unwanted vertical offset when no selected item is present:

### ISSUE THREAD

**Issue by mattsimgithub** [salim-lachdhaf/searchable_dropdown#177]
When the dropdown is blank, the dropdown button is moved down several pixels from the vertical center:

![image](https://user-images.githubusercontent.com/82390849/119404566-962ba300-bca5-11eb-8407-0f6647c0b3e1.png)

When an item is selected, the dropdown button is shown correctly:

![image](https://user-images.githubusercontent.com/82390849/119404650-b9eee900-bca5-11eb-9fc6-a1be69035688.png)

I can get some improvement by customizing dropdownButtonBuilder (reducing padding to 0) but if there's something more standard I can do here, I'd rather do that. Maybe I'm just missing an option.

```
  Widget _customizedDropdownBuilder<T>(
      BuildContext context, T item, String itemDesignation) {
    if (item == null) return Container();

    return Padding(
      padding: const EdgeInsets.fromLTRB(12.0, 0, 0, 0),
      child: Text(
        itemDesignation,
        style: TextStyles.body.copyWith(fontSize: 16),
      ),
    );
  }

              child: DropdownSearch<T>(
                mode: dropdownMode,
                enabled: this.enabled,
                compareFn: this.compareFn,
                showSelectedItem: true,
                items: items,
                itemAsString: itemAsString,
                showSearchBox: showSearch,
                autoFocusSearchBox: showSearch,
                filterFn: filterFn,
                onChanged: (item) {
                  this.onChange(item);
                },
                dropdownBuilder: _customizedDropdownBuilder,
                dropdownBuilderSupportsNullItem: true,
                // required: by default the control will paint a border for itself we don't want.
                dropdownSearchDecoration:
                    InputDecoration(border: InputBorder.none),
                selectedItem: initialItem,
              ),
```

Thanks for any help.

**Comment by salim-lachdhaf** [comment]
set this `showAsSuffixIcons` to `true` and let me know if it works for you

**Comment by mattsimgithub** [comment]
Unforunately no. This setting changes the display a little when an item is selected, moving the text and icon a little higher:

![image](https://user-images.githubusercontent.com/82390849/119834068-3f9caf80-bec5-11eb-9177-74d6b8ba7c09.png)

But it doesn't change the button alignment when no item is selected:

![image](https://user-images.githubusercontent.com/82390849/119834243-65c24f80-bec5-11eb-8401-56dd0ff3d1c7.png)

**Comment by salim-lachdhaf** [comment]
i couldn't reproduce your issue !

**Comment by mattsimgithub** [comment]
Thanks for trying.

This app is built for WIndows desktop. I suspect my issue is specific to that platform. At one point I saw a build running on MacOS and the button alignments looked different.

Sorry I didn't think to mention my target platform originally. No objections if you close this issue.
