### ISSUE TITLE
Add support for changing baseStyle to Dropdown search formfield.

### ISSUE THREAD

**Issue by hamirshekhawat** [salim-lachdhaf/searchable_dropdown#178]
Currently there's no way to change the baseStyle of the form field. InputDecoration can't be used to change the baseStyle. User should be able to set this.

**Comment by vasilich6107** [comment]
I do not see any baseStyle property for textfield. Could you be more specific?

**Comment by salim-lachdhaf** [comment]
you can use `dropdownBuilder` and customize your widget as you want , there no need to specify for each item  all its attributs.

**Comment by hamirshekhawat** [comment]
@vasilich6107  In file dropdown_search.dart, inside method _formField, the ValueListenableBuilder can have a basestyle.
@salim-lachdhaf I don't think dropdownsearchbuilder would allow us to give the form field a baseStyle.
We need baseStyle so that when a user selects one of the options from the dropdown, the style of text displayed in searchbox can be controlled too. I can create a PR for this.

**Comment by salim-lachdhaf** [comment]
yes , but `dropdownsearchbuilder` gives to the user the possibility to fully customize his widget , so why add new attributs to defines alignement and style ... ?

**Comment by hamirshekhawat** [comment]
I think it saves a lot of time. Just to set text style I shouldn't have to write the complete builder. But that's just me.

**Comment by salim-lachdhaf** [comment]
this feature will be released in the next version.
thnx to @vasilich6107
