### ISSUE TITLE
How to implement selectedItem: using onFind method.

### ISSUE THREAD

**Issue by panchalAlpit** [salim-lachdhaf/searchable_dropdown#18]
DropdownSearch<UserModel>(
  label: "Name",
  onFind: (String filter) => getData(filter),
  onChanged: (UserModel data) => print(data),
),

How can I implement the already selected item for above code?

**Comment by salim-lachdhaf** [comment]
`OnFind` and `items` are the same , just onFind used to get data asyc , and you can even use them together and merge direct list with asyc list.

Example of uses of selectedItem: 
```
var defaultUser = UserModel(name: "Offline name1", id: "999");
DropdownSearch(
label: "Name",
onFind: (String filter) => getData(filter),
selectedItem: defaultUser,
showSelectedItem: true,
onChanged: (UserModel data) => print(data),
)
```

**Comment by panchalAlpit** [comment]
Thanks, @salim-lachdhaf for your help, now it's working.
