### ISSUE TITLE
Mode Bottom sheet is not being pushed up by the keyboard

### ISSUE THREAD

**Issue by t00nami** [salim-lachdhaf/searchable_dropdown#180]
Hello!
We migrated to nullsafety a few days ago and we have encountered the problem described in the title.

Version of library [0.6.1]

```
DropdownSearch<Dummy>(
                  mode: Mode.BOTTOM_SHEET,
                  selectedItem: _dummyProvider.selectedDummyItem,
                  emptyBuilder: (_, text) => ErrorBox(),
                  itemAsString: (Dummy item) => item.toStringContext(context),
                  items: _dummyProvider.getDummyList,
                  label: "Dummy text",
                  showSearchBox: true,
                  showSelectedItem: true,
                  compareFn: (Dummy? s, Dummy? t) => s != null && s.toStringContext(context) == t?.toStringContext(context),
                  popupItemBuilder: (_, item, isSelected) =>ComboItem(isSelected),
                  popupTitle: ComboHeader(),
                  onChanged: (value) {
                    _dummyProvider.selectedDummyItem= value;
                    FocusScope.of(context).unfocus();               
                  },
                )
```

**Comment by t00nami** [comment]
I have found that if you add margin to the container widget at the build method at the SelectedDialog class fix the problem

```
return Container(
      width: widget.dialogMaxWidth ?? maxWidth,
      constraints: BoxConstraints(maxHeight: widget.maxHeight ?? maxHeight),
      margin: MediaQuery.of(context).viewInsets.bottom != 0.0 ? const EdgeInsets.only(bottom: 225) : const EdgeInsets.only(bottom: 0),
```

Note: I have add some random bottom margin just to make the example clear.

**Comment by vasilich6107** [comment]
@t00nami 
This bug is already fixed by https://github.com/salim-lachdhaf/searchable_dropdown/pull/172
@salim-lachdhaf could we release the fix?

**Comment by tjmeal** [comment]
Hello, i have the same problem is it fixed ?

**Comment by vasilich6107** [comment]
@tjmeal lets wait for two more days for maintainer to make a release
Otherwise I will make a temp release until main package will be released

**Comment by tjmeal** [comment]
Of course, thank you very much ror your update :)

**Comment by vasilich6107** [comment]
@tjmeal  @t00nami @salim-lachdhaf 
This should be fixed in latest version
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L489

**Comment by t00nami** [comment]
> @tjmeal @t00nami @salim-lachdhaf
> This should be fixed in latest version
> https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L489

Thanks for your effort!!
