### ISSUE TITLE
Compatibility with GETX

### ISSUE THREAD

**Issue by ravdeepsingh22** [salim-lachdhaf/searchable_dropdown#188]
[Get] the improper use of a GetX has been detected. 
      You should only use GetX or Obx for the specific widget that will be updated.
      If you are seeing this error, you probably did not insert any observable variables into GetX/Obx 
      or insert them outside the scope that GetX considers suitable for an update 
      (example: GetX => HeavyWidget => variableObservable).
      If you need to update a parent widget and a child widget, wrap each one in an Obx/GetX.

`RxList<SingleIncidentType> incidentTypes = <SingleIncidentType>[].obs;`
  items: model.incidentTypes, is observable 

`  Container(
            height: 50,
            child: Obx(
              () => DropdownSearch<SingleIncidentType>(
                compareFn: (a, b) => a?.id == b?.id,
                mode: Mode.BOTTOM_SHEET,
                showAsSuffixIcons: true,
                showSelectedItem: true,
                showSearchBox: true,
                items: model.incidentTypes,
                dropdownSearchDecoration:
                    fieldDeco(hint: 'Select Incident Type'),
                onChanged: (e) {
                  model.setIncidentType(e);
                },
              ),
            ),
          ),`

Strangely this works on Hot Reload

**Comment by salim-lachdhaf** [comment]
i don't see bug here

**Comment by ravdeepsingh22** [comment]
> i don't see bug here

This may not be a bug , but definitely a performance issue or compatibility issue .

However have you tried it with getX
