### ISSUE TITLE
how to change text color?

### ISSUE THREAD

**Issue by FriendlyNeighbor** [salim-lachdhaf/searchable_dropdown#19]
I have a dark and light theme in my app. text is unreadable when using dark theme.

**Comment by namae101** [comment]
you can use popupItemBuilder to build dropdown item according to your theme

**Comment by salim-lachdhaf** [comment]
@FriendlyNeighbor witch text ? Popup text or dropdown text ?

Dark and light theme works fine, unless you have customised dropdownBuilder or popupItemBuilder, in this case you have to handle text color by yourself (try Theme.of(context).textTheme.subtitle1 as style for your text , this will handle both themes....).
