### ISSUE TITLE
Search box not working properly if filter value contains space

### ISSUE THREAD

**Issue by AliEasy** [salim-lachdhaf/searchable_dropdown#190]
Hi
I just realized a problem in `onFind` when string contains a space (' ')
So my `_onFind` Function Works fine but after `return` filtered data coming from Api, my search dialog box is empty!

I traced it and I found the problem some where here but I dont know what it is
```
List<T> applyFilter(String filter) {
      return _items.where((i) {
        if (widget.filterFn != null)
          return (widget.filterFn(i, filter));
        else if (i.toString().toLowerCase().contains(filter.toLowerCase()))
          return true;
        else if (widget.itemAsString != null) {
          return (widget.itemAsString(i))
                  ?.toLowerCase()
                  ?.contains(filter.toLowerCase()) ??
              false;
        }
        return false;
      }).toList();
    }
```

At `selectDialog.dart`

thanks in advance

**Comment by salim-lachdhaf** [comment]
could you pass your searchableDropdown widget

**Comment by AliEasy** [comment]
Actually by using the latest version of `dropdown_search` this issue is solved
But still in my offline mode I have this problem and I dont kwon how to solve it

here is my function to search in string

```
onFind:(text) {
    List<ComboRowModel> filtered = [];
    for (int i = 0; i < list.length; i++) {
          if (list[i].title.contains(filter)) {
              filtered.add(list[i]);
           }
     }
    return;
}, 

```

somehow this `contains` method not working properly when there is a space in string

I appreciate your help

**Comment by salim-lachdhaf** [comment]
are you using this parameter `isFilteredOnline` ?

**Comment by AliEasy** [comment]
by setting `isFilteredOnline`  to `true`, problem solved
Thanks
