### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by AliEasy** [salim-lachdhaf/searchable_dropdown#191]
/E:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-0.6.3/lib/src/selectDialog.dart:193:23: Error: No named parameter with the name 'interactive'.
                      interactive: widget.scrollbarProps?.interactive,
                      ^^^^^^^^^^^
/E:/Flutter/flutter/packages/flutter/lib/src/material/scrollbar.dart:63:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'E:\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 49s
Exception: Gradle task assembleDebug failed with exit code 1

`dropdown_search: ^0.6.3`

**Comment by ashish-andev** [comment]
Same issue

**Comment by salim-lachdhaf** [comment]
that's weird, please try clean project ...

**Comment by AliEasy** [comment]
Did try that. but didnt work

**Comment by salim-lachdhaf** [comment]
is the issue existe in v0.6.2 ?

**Comment by AliEasy** [comment]
Yes
Also in v0.6.1

**Comment by salim-lachdhaf** [comment]
here i think to double check your project maybe you are me missing something

**Comment by ashish-andev** [comment]
It's not happening on 0.6.1.
@AliEasy please confirm if you removed ^, so that it won't auto upgrade to v 0.6.3
Please use it like `dropdown_search: 0.6.1`

**Comment by AliEasy** [comment]
Using `dropdown_search: 0.6.1` seems to solve it

Thanks to @ashish-andev

**Comment by cuongmanhvo162** [comment]
I got same issue with version greater than 0.6.1
Keep my use at 0.6.1 make it work fine.

**Comment by Mohamed50** [comment]
same here

**Comment by vasilich6107** [comment]
It seems that you need to update FLutter version
`interactive: widget.scrollbarProps?.interactive,`

**Comment by vasilich6107** [comment]
interactive was added 
![image](https://user-images.githubusercontent.com/6721286/122219099-c686eb80-ceb7-11eb-8c65-d4a1dbd32b65.png)

**Comment by vasilich6107** [comment]
Flutter 2.0.0 does not have this property
As far as the latest stable version is 2.2.1 it is better to update

![image](https://user-images.githubusercontent.com/6721286/122220241-d2bf7880-ceb8-11eb-9ee5-6b5d48979025.png)

**Comment by vasilich6107** [comment]
Unfortunately you will have to update to `2.2.*`

**Comment by AsadSaleh** [comment]
So right now we need to change our deps from `dropdown_search: ^0.6.1` to `dropdown_search: 0.6.1` (without the caret) right?

**Comment by ShalikaAshan01** [comment]
This issue is not showing on **flutter 2.2**
