### ISSUE TITLE
How can I search by tapping a search button only?

### ISSUE THREAD

**Issue by misici234** [salim-lachdhaf/searchable_dropdown#195]
I don't want to search as soon as I type a character in a TextField search box which is triggered on onChanged callback. The reason is that I make web API call on each keyboard button press and make unnecessary web API calls. I don't want that. I want to type a search string and tap a search button and make the search by calling a web API. How can I do it, please?

**Comment by misici234** [comment]
Hi, Could anyone provide an update on this one?

**Comment by salim-lachdhaf** [comment]
we do not provide this feature for now, we just use timer that you can use it to auto search or use `isFilteredOnline`  parameter to false, if all your data are loaded with empty filter so you will have only one call to the api
