### ISSUE TITLE
multiSelection Feature

### ISSUE THREAD

**Issue by salim-lachdhaf** [salim-lachdhaf/searchable_dropdown#197]
the multi selection will be available in the next release 🥳

**Comment by vasilich6107** [comment]
nice

**Comment by GrapevineLin** [comment]
I can't wait！

**Comment by vasilich6107** [comment]
any updates on release date?

**Comment by salim-lachdhaf** [comment]
@vasilich6107 i'm trying my best to make the release today, otherwises it will be in the next week's days

**Comment by vasilich6107** [comment]
@salim-lachdhaf I wish you happy release this weekend)

**Comment by salim-lachdhaf** [comment]
multiSelection is released in v1.0.0-beta
