### ISSUE TITLE
errorText not showing?

### ISSUE THREAD

**Issue by teoprayoga** [salim-lachdhaf/searchable_dropdown#199]
String? _errMessage;

setstate{
_errMessage = 'Error';
}

errorText: _errMessage,

--> Error message not showing

**Comment by salim-lachdhaf** [comment]
there is not attribute called `errorText`

**Comment by salim-lachdhaf** [comment]
no Replay

**Comment by anoop-tm** [comment]
This would be a nice feature to have for this wonderful package

**Comment by salim-lachdhaf** [comment]
you can use `errorBuilder` .
