### ISSUE TITLE
dropdownSearchDecoration is not work

### ISSUE THREAD

**Issue by agisrh** [salim-lachdhaf/searchable_dropdown#2]
Hi...
I tried to use the dropdownSearchDecoration for the style, but when I added the dropdownsearch it didn't work at all

**Comment by salim-lachdhaf** [comment]
Hi, yes because the decoration is applied for the default dropdownSearchBuilder, so if customize your dropdownSearchBuilder the decoration will not be applied.
Well this is not really a bug , but we have improved the behiever in this next version 0.3.4 witch will be published soon with amazing new features.

**Comment by leanhro2812** [comment]
@salim-lachdhaf 
dropdownSearchDecoration => Not work
Does this feature work now?
The current version is 0.4.3

**Comment by salim-lachdhaf** [comment]
it works fine, please check examples [here](https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart), otherwise please paste a example for your code.

here is a simple example :

```
DropdownSearch<String>(
                showClearButton: true,
                label: 'Contries*',
                items: ["Brazil", "Italia (Disabled)", "Tunisia", 'Canada'],
                dropdownSearchDecoration: InputDecoration(
                    filled: true,
                    fillColor: Theme.of(context).inputDecorationTheme.fillColor,
                ),
   ),
```

**Comment by leanhro2812** [comment]
The default padding currently is:
ContentPadding: EdgeInsets (12.0, 12.0, .0.0, 0.0)
I want to remove and customize it at my disposal but it doesn't work
My code: 
dropdownSearchDecoration: InputDecoration(
   contentPadding: EdgeInsets.all(0.0),
),

**Comment by salim-lachdhaf** [comment]
it's working fine.
just add `border: OutlineInputBorder(),` and you will see that there is no padding .

**Comment by leanhro2812** [comment]
> it's working fine.
> just add `border: OutlineInputBorder(),` and you will see that there is no padding .

The problem is not in the line border ..
The left and top padding is too large, causing my layout to be uneven.
So can not customize because it is the default?

**Comment by DhavalRKansara** [comment]
> order: OutlineInputBorder()
@salim-lachdhaf 

**Solution A(Set content padding as 0):**
```
<img width="324" alt="Screen Shot 2021-04-27 at 8 29 34 PM" src="https://user-images.githubusercontent.com/44993081/116264427-e80d0600-a797-11eb-8f9c-1b6c8a25fb27.png">: InputDecoration(
          contentPadding: EdgeInsets.all(0),
          labelStyle: TextStyle(color: Colors.indigo),
          isDense: true,
          enabledBorder: OutlineInputBorder(
              borderSide: BorderSide(
            color: Theme.of(context).primaryColor,
            width: 2.0,
          ))),
```

- Using solution A I am facing the below UI issue with dropdownSearchDecoration:

<img width="362" alt="Screen Shot 2021-04-27 at 8 30 24 PM" src="https://user-images.githubusercontent.com/44993081/116264247-c4e25680-a797-11eb-9195-b6223d5e457d.png">


**Solution B(Removed content padding):**
```
dropdownSearchDecoration: InputDecoration(
          labelStyle: TextStyle(color: Colors.indigo),
          isDense: true,
          enabledBorder: OutlineInputBorder(
              borderSide: BorderSide(
            color: Theme.of(context).primaryColor,
            width: 2.0,
          ))),
```

- Using solution B I am facing the below UI issue with(extra space around the content):

<img width="324" alt="Screen Shot 2021-04-27 at 8 28 58 PM" src="https://user-images.githubusercontent.com/44993081/116264504-f78c4f00-a797-11eb-9ec4-cb76405f038b.png">
