### ISSUE TITLE
Is it possible to disable or enable searchable_dropdown after button click?

### ISSUE THREAD

**Issue by panchalAlpit** [salim-lachdhaf/searchable_dropdown#20]
Is it possible to disable or enable searchable_dropdown after button click?
For just Example:- 
new TextFormField(
  readOnly: True,
);
if we set readOnly true so the user can't edit this.
So can we do the same thing in our searchable_dropdown to restrict to open Builder or open dialog?
Because I want to use the single searchable_dropdown in both displays and edit functionality.

Thanks.

**Comment by salim-lachdhaf** [comment]
of course, 

```
bool isEnabled = true;
DropdownSearch<String>(
       items: ["Brazil", "Italia", "Tunisia", 'Canada'],
       selectedItem: "Tunisia",
       enabled : true;//or enabled : isEnabled ;
 ),
```
