### ISSUE TITLE
How to give border-radius for popup box (not popup item)

### ISSUE THREAD

**Issue by nerdrun** [salim-lachdhaf/searchable_dropdown#202]
First of all, thanks for providing this nice plugin.

I know how to put styles for each popup item, however, I don't know how to give radius to the entire box surrounding all popup items.

Thank you.

**Comment by vasilich6107** [comment]
`popupShape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(25))`

**Comment by salim-lachdhaf** [comment]
check @vasilich6107  anwser or check examples page, the bottomSheet example has this feature.

**Comment by nerdrun** [comment]
Thanks for your comment, and sorry for the late.

I've tried your code @vasilich6107 , Apperantely it works but when I give background color to popup items then it turns as rectangle and I don't want to give the border radius to each popup items.

Do you have any suggestion?

**Comment by vasilich6107** [comment]
@nerdrun could you attach a screenshot alongside with code to illustrate the issue?

**Comment by tigrenok00** [comment]
Hi, I used to use popupShape for this but after updating to the new version it's deprecated, what is the alternative setting? Can't find it in popupProps
