### ISSUE TITLE
pre release v1 suggestions 

### ISSUE THREAD

**Issue by salim-lachdhaf** [salim-lachdhaf/searchable_dropdown#206]
any proposition before releasing v1 ?

**Comment by lypborges** [comment]
@salim-lachdhaf tks for your work in this project. It's possible to add a new Mode or any away change the style of Mode.Menu  for the search box appear on the same place where the input is?

**Comment by vasilich6107** [comment]
could we fix the implementation of multi selection before releasing?

**Comment by salim-lachdhaf** [comment]
of course, what are the bugs ? for this it's in beta version

**Comment by vasilich6107** [comment]
#207 #208 #209 
This is what I noticed for now

**Comment by salim-lachdhaf** [comment]
> @salim-lachdhaf tks for your work in this project. It's possible to add a new Mode or any away change the style of Mode.Menu for the search box appear on the same place where the input is?

could explain more ?

**Comment by weedget** [comment]
It would be great if there will be possibility to set all messages by myself. I mean I'd like to show message to user in his language instead of english.

**Comment by vasilich6107** [comment]
@weedget could you clarify what do you mean?
The `DropdownSearch` is pretty flexible in configuration so you can specify almost everything

**Comment by weedget** [comment]
> @weedget could you clarify what do you mean?
sure!
would like to personalize at least this message:
https://github.com/salim-lachdhaf/searchable_dropdown/blob/90dc9574edf0c1c1457694ffbf385985c82a9d63/lib/src/selection_widget.dart#L189
maybe more later, but this is essential for now

**Comment by vasilich6107** [comment]
@weedget you have an option for this
![image](https://user-images.githubusercontent.com/6721286/125289651-27bfa480-e328-11eb-9a4e-8581494152e3.png)

```dart
///custom layout for empty results
final EmptyBuilder? emptyBuilder;
```

**Comment by weedget** [comment]
@vasilich6107 

OK, thats not mentioned in layout customization docs, however that's not really what I need.

Please take a look on screen. This message which you mentioned is in search field. I'd like to show it instead this big red "No data found". More over I'd like to have full list when showing up the search box.
![Screenshot_20210712-162910](https://user-images.githubusercontent.com/3869776/125305282-8556ef80-e32e-11eb-98f5-f691b843c1a9.jpg)

**Comment by vasilich6107** [comment]
@weedget its better to start new issue for this. This thread is not the best place to continue

**Comment by dragongesa** [comment]
Please add the inputDecoration feature to the searchbox in Mode.BOTTOM_SHEET. Because we cant change the hintText and the style of searchbox like prefix or suffix icon and other things

**Comment by vasilich6107** [comment]
@dragongesa use `searchFieldProps` to pass decoration.

**Comment by salim-lachdhaf** [comment]
last call: is there any suggestions before releasing v1
