### ISSUE TITLE
selecteItem + selectedItems

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/searchable_dropdown#209]
Hi. I have a question.

Why do we need two items to store the selected values?
In case if widget supports multi select it seems simpler to have just `selectedItems` which will store selected items.

**Comment by vasilich6107** [comment]
this also duplicates other items like

onChangedMultiSelection + onChanged
dropdownBuilder + dropdownBuilderMultiSelection
onSaved + onSavedMultiSelection
validator + validatorMultiSelection
onBeforeChange + onBeforeChangeMultiSelection

**Comment by vasilich6107** [comment]
If you are ok switching to `selectedItems` only I can try to make PR

**Comment by salim-lachdhaf** [comment]
simply for two reason:
To be clear and elegant and separate between multi and single selection ...
And to make things easier to user, to handle things.
for example , let's say a user uses single selection mode, and he want to pass a validator as paramater, here is simple , it has his object and he pass his test as he want : ! value.contains('a').

if we pass always a list even in the single selection, here first the user will be confused, and he have to do extrat work ... beside it's not that elegant...
list.map( (value) => !value.contains('a'))
.....

**Comment by vasilich6107** [comment]
Ok)

Are there any other benefits besides the elegance of validator?

internal complexity of package grows and this could be a cause of bugs.

I’m not sure that elegance of validator is a good trade off

**Comment by salim-lachdhaf** [comment]
not only elegance, the user will be confused , he working on one single item, and he found him self working with a list for only one item !

**Comment by salim-lachdhaf** [comment]
i will close this, only if i found a way or argument solve the problem (it's a problem for me) bellow:
how convience a user that he is in single mode , but i give him the possibility to pass multiselected items ?
how to convience him in single mode that the returned result is a list but wait you are in single mode ! 
where is the logic in all that ?
remember that i well separated between single and multi selection, however , in single mode user face only single mode params and the samething for the multi mode.

if you notice , in the pluging , in the selectDialog widget i fully working with multi selection , but not the case in the plugin , for described reason.
