### ISSUE TITLE
oldSelectedItems != newSelectedItems

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/searchable_dropdown#211]
Two equal arrays are not equal from dart perspective.
We need to use something like this
https://stackoverflow.com/questions/10404516/how-can-i-compare-lists-for-equality-in-dart

![image](https://user-images.githubusercontent.com/6721286/125168344-d2f81e80-e1ad-11eb-8dc7-ceba9857e88b.png)

**Comment by salim-lachdhaf** [comment]
fixed in beta2
