### ISSUE TITLE
possibility to personalize "No data found" message

### ISSUE THREAD

**Issue by weedget** [salim-lachdhaf/searchable_dropdown#212]
Please add possibility to personalize message "No data found" when search will produce 0 results.
As for now its [here](https://github.com/salim-lachdhaf/searchable_dropdown/blob/90dc9574edf0c1c1457694ffbf385985c82a9d63/lib/src/selection_widget.dart#L189) in code.

**Comment by vasilich6107** [comment]
![image](https://user-images.githubusercontent.com/6721286/125412552-b33c4280-e3c7-11eb-9415-89325377ec0d.png)

**Comment by vasilich6107** [comment]
Open example and on line 224 add

```
emptyBuilder: (context, searchEntry) =>
                    Center(child: Text('No data')),
```

I do not know what is wrong with you sample that it displays the underlined text 
try reading here
https://stackoverflow.com/questions/47114639/yellow-lines-under-text-widgets-in-flutter

**Comment by salim-lachdhaf** [comment]
> Open example and on line 224 add
> 
> ```
> emptyBuilder: (context, searchEntry) =>
>                     Center(child: Text('No data')),
> ```
> 
> I do not know what is wrong with you sample that it displays the underlined text
> try reading here
> https://stackoverflow.com/questions/47114639/yellow-lines-under-text-widgets-in-flutter

@weedget maybe you miss to add `scaffold `as parent to your widget

**Comment by weedget** [comment]
@salim-lachdhaf @vasilich6107 Thank you guys, this way I can set this message.
Styling is separate thing not related to dropdown search.
You can close this issue.
