### ISSUE TITLE
Selected text wraps and overflows

### ISSUE THREAD

**Issue by Abhijit-Revamp** [salim-lachdhaf/searchable_dropdown#213]
If the width of the widget is smaller than the text, the text wraps (See pic) and overflows. 

What are the available options to style the display of text ?

![image](https://user-images.githubusercontent.com/44320018/125739820-5d705979-367e-44fa-8f74-93b9b01a2211.png)

**Comment by salim-lachdhaf** [comment]
as i see in the screenshot, you have two problems
- you have a very small width
- the text size is very big


it's not the issue of the plugin , you have the necessary params to handle a such case like `dropdownBuilder`

**Comment by Abhijit-Revamp** [comment]
@salim-lachdhaf  - I did not report this as bug. I wanted an option how the font size can be reduced or can ellipses be added

**Comment by salim-lachdhaf** [comment]
yes, i answred you , you can use `dropdownBuilder` to override all the widget or just use `dropdownSearchBaseStyle` to override the text style of the dropdown.

**Comment by Abhijit-Revamp** [comment]
Thanks. Let me use the same and try
