### ISSUE TITLE
Cannot run flutter

### ISSUE THREAD

**Issue by budescode** [salim-lachdhaf/searchable_dropdown#215]
I get this error each time I install it

../../../../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dropdown_search-1.0.0-beta2/lib/src/selection_widget.dart:206:25: Error: No named parameter with the name 'interactive'.
                        interactive: widget.scrollbarProps?.interactive,
                        ^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/scrollbar.dart:63:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({

**Comment by salim-lachdhaf** [comment]
solved here : https://github.com/salim-lachdhaf/searchable_dropdown/issues/191
