### ISSUE TITLE
Dropdown Menu has a gap with it's dropdown bar

### ISSUE THREAD

**Issue by pieas-asif** [salim-lachdhaf/searchable_dropdown#216]
The dropdown menu has a gap with it's dropdown bar. I don't know if this issue is only on my case or not. but I tried to implement dowpdown search on a blank screen and it has the same issue. 

https://paste.pics/32418030b619808a15870f2efea8cd11

**Comment by vasilich6107** [comment]
Check that you are using latest version and do not forget to provide reproduction code

**Comment by pieas-asif** [comment]
Yes I am in the latest version of `dropdown_search` which is `0.6.3`. 

and for the reproduction code, please run this code from your example

```
DropdownSearch<String>(
    mode: Mode.MENU,
    showSelectedItem: true,
    items: ["Brazil", "Italia (Disabled)", "Tunisia", 'Canada'],
    label: "Menu mode",
    hint: "country in menu mode",
    popupItemDisabled: (String s) => s.startsWith('I'),
    onChanged: print,
    selectedItem: "Brazil"),
```

here you will see there is a gap between the dropdown menu and the actual bar. which is a issue because your video shows everything works as expected.

**Comment by Nanway** [comment]
I have the same issue but it only occurs when I build on my Android device. There are no issues when I build for web.

**Comment by arsalanImtiaz455** [comment]
I have Same issue

**Comment by vasilich6107** [comment]
@arsalanImtiaz455 @pieas-asif here is your example on latest beta
![image](https://user-images.githubusercontent.com/6721286/127358437-bb8b7f9b-ed37-46b1-a2f2-aea4163b1e41.png)

**Comment by vasilich6107** [comment]
@pieas-asif I suppose you are having some modification to your `InputDecorator`

**Comment by pieas-asif** [comment]
Thank you. Issue fixed using 1.0.0-beta2, Still problem in version 0.6.3

Which one should I be using?

**Comment by vasilich6107** [comment]
@pieas-asif first of all you need to understand that current beta will some day become a release version)
Also the obvious way is to use that version which solves your issues)

**Comment by pieas-asif** [comment]
Ok ❤️ .
Thank You for this Awesome Package 📦
