### ISSUE TITLE
How to Increase the Size of the Items Dialog

### ISSUE THREAD

**Issue by evertonfoz** [salim-lachdhaf/searchable_dropdown#218]
Is it possible to scale the width of the search and items dialog? Is it also possible to do a padding of the search box?

![image](https://user-images.githubusercontent.com/9963789/126876531-a8a05e0e-86fa-43d0-a100-ea075e0b94a6.png)

**Comment by vasilich6107** [comment]
Currently there is no way of doing it

To achieve this we need to add ability to pass padding here
- https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/src/selection_widget.dart#L466

To increase dialog width we need to experiment with `AlertDialog` here
- https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L642

**Comment by vasilich6107** [comment]
@evertonfoz padding added in #226
