### ISSUE TITLE
Including this library results in this error..

### ISSUE THREAD

**Issue by dhruvbhagat8** [salim-lachdhaf/searchable_dropdown#219]
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-0.6.3/lib/src/selectDialog.dart:193:23: Error: No named parameter with the name 'interactive'.
                      interactive: widget.scrollbarProps?.interactive,
                      ^^^^^^^^^^^

**Comment by vasilich6107** [comment]
Update to latest flutter version

**Comment by dhruvbhagat8** [comment]
Thanks, worked.

**Comment by vasilich6107** [comment]
Why not to close the issue?
