### ISSUE TITLE
Navigator#pushNamed needs to be called twice

### ISSUE THREAD

**Issue by jmewes** [salim-lachdhaf/searchable_dropdown#22]
**Observed result**

The invocation of `Navigator.of(context).pushNamed` within the `onChanged` method of `DropdownSearch` has no effect. Only after calling it a second time it executes the navigation.

**Expected result**

When a value has been selected, I would like to navigate to another page.

**Steps to reproduce**

Here is the minimal example for what I tried to build:

```dart
class FirstPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: DropdownSearch<String>(
          hint: 'Please select something',
          items: ['Two'],
          onChanged: (item) {
            Navigator.of(context).pushNamed('/2');
            Navigator.of(context).pushNamed('/2');
          },
        ),
      ),
    );
  }
}
```

The complete code for this minimal navigation example can be found here:

https://github.com/jmewes/navigation_example/blob/master/lib/main.dart

**Environment**

Tested with Flutter for the web.

**Question**

Could you please help me to understand what is the problem here?

**Comment by salim-lachdhaf** [comment]
Thank you for reporting that, yes it's an issue, and it is fixed in the next version v0.4.4 that will be release toworrow morning.

**Comment by salim-lachdhaf** [comment]
the version 0.4.4 is live now, check it.

**Comment by jmewes** [comment]
@salim-lachdhaf ,

The example navigation described/linked above is working with a single `pushNamed`.

Thanks for the fast feedback!
