### ISSUE TITLE
searchBoxController

### ISSUE THREAD

**Issue by Yoda-Man** [salim-lachdhaf/searchable_dropdown#221]
Is it possible to change the value selected and displayed at runtime when a value of the TextEditingController changes?

**Comment by vasilich6107** [comment]
Describe your case with more details.
What effect are you expecting to achieve, overal steps and reasoning

**Comment by Yoda-Man** [comment]
I am dynamically creating DropdownSearch widgets on each form and for each DropdownSearch
 Widget I create a TextEditingController that gets added to a list of TextEditingController List<TextEditingController> textController = [];
When a value changes on one of the TextFormField  I want it to auto select items in the DropdownSearch controls when I update the text value example

textController[result2[0].index].text = lookup.columnValue;

**Comment by vasilich6107** [comment]
Check example to how to select items from outside
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart#L351

**Comment by vasilich6107** [comment]
@Yoda-Man any progress?

**Comment by Yoda-Man** [comment]
> @Yoda-Man any progress?

Hi thanks for the example it was very helpful.
