### ISSUE TITLE
showSelectedItem set to false not working

### ISSUE THREAD

**Issue by GitKyRep** [salim-lachdhaf/searchable_dropdown#222]
showSelectedItem set to false not working

**Comment by GitKyRep** [comment]
![image](https://user-images.githubusercontent.com/7789020/127116527-5fa2004c-d3cb-4873-9b65-6958010fefc1.png)

**Comment by GitKyRep** [comment]
![image](https://user-images.githubusercontent.com/7789020/127116718-6d56a609-c0f6-4f43-9434-391c43fdbe25.png)

**Comment by XROCKEFELLERX** [comment]
Did you manage to fix the problem?
I have the same problem
Thanks you

**Comment by GitKyRep** [comment]
> Did you manage to fix the problem?
> I have the same problem
> Thanks you

I fix with set selecteditem is null
Selecteditem = null

**Comment by chrallard** [comment]
> > Did you manage to fix the problem?
> > I have the same problem
> > Thanks you
> 
> I fix with set selecteditem is null
> Selecteditem = null

This isn't working for me.
