### ISSUE TITLE
The class 'DropdownSearch' doesn't have a constructor named 'multiSelection'.

### ISSUE THREAD

**Issue by XROCKEFELLERX** [salim-lachdhaf/searchable_dropdown#223]
Thank you and congratulations for your work, but I have a problem when I want to use the multiple selection. It works when the "dropdown_search" package is in my app folder, but not when I try to import it.
I get this error.
```
The class 'DropdownSearch' doesn't have a constructor named 'multiSelection'.
Try invoking a different constructor, or define a constructor named 
```
I can correctly use "DropdownSearch" but not the multiple version
Thank you very much for your help.

**Comment by vasilich6107** [comment]
Did you check the example?

**Comment by XROCKEFELLERX** [comment]
yes it was the version of the package
thanks you
