### ISSUE TITLE
Can't access the multiselector class with the current package on pub.dev

### ISSUE THREAD

**Issue by AaronMackiee** [salim-lachdhaf/searchable_dropdown#227]
hello!

First, I want to say thank you for developing this very useful package. I am trying to integrate it into my app and would like to use the multi-selection tool. I have downloaded and imported the most recent package into my app but it won't allow me to access the class explicitly stated in the docs this way, "DropdownSearch<String>.multiSelection()." I am guessing all that needs to be done is to update the package on pub.dev to the most recent version that's on here. Please advise and let me know what I can do to access the multi-selection tool.

thanks!

**Comment by AaronMackiee** [comment]
To be a little more specific, I tried copying the code below in the readme example and it was giving me errors because with the current package downloaded it said it wasn't included.

DropdownSearch<String>.multiSelection(
    mode: Mode.MENU,
    showSelectedItem: true,
    items: ["Brazil", "Italia (Disabled)", "Tunisia", 'Canada'],
    label: "Menu mode",
    hint: "country in menu mode",
    popupItemDisabled: (String s) => s.startsWith('I'),
    onChanged: print,
    selectedItems: ["Brazil"]),

**Comment by vasilich6107** [comment]
There are two versions on pub.dev
Latest: 0.6.3 - without multiselection
Prerelease: 1.0.0-beta2 - WITH multiselection

What version are you using?

**Comment by AaronMackiee** [comment]
@vasilich6107 Thank you very much for the quick response. I finally got it working with the beta version. I'll make sure to give some feedback on this release if I see any bugs. So far I really like the new look of how the list of items is displayed in the box after being selected. Great work!
