### ISSUE TITLE
[BUG-Web] HtmlElementView underneath selection popup consumes mouse event

### ISSUE THREAD

**Issue by acheronian** [salim-lachdhaf/searchable_dropdown#228]
Stepst to reproduce:
1. Create HtmlElementView element in view, expand it
2. Add an DropdownSearch element and fill it with elements
3. Open dropdown
4. Elements and ok button should not be selectable

This is an issue with Flutter, could be fixed by wrapping dialog with [pointer_interceptor](https://pub.dev/packages/pointer_interceptor)

**Comment by salim-lachdhaf** [comment]
it's not proble of the plugin.

**Comment by acheronian** [comment]
Well, no, not directly, but the proposed solution for flutter is to use the above mentioned package. Also, there will be no fix resolving the problem. For further details, please take a look at the [following issue](https://github.com/flutter/flutter/issues/54027).

**Comment by katimunzenrieder** [comment]
I encountered the same problem, which could easily be fixed by wrapping the dialog with [https://pub.dev/packages/pointer_interceptor](url) as mentioned above.

As declared by you, the package should be suitable for web, so in my opinion the issue is related to the plugin.
