### ISSUE TITLE
Tick only a certain number of items

### ISSUE THREAD

**Issue by XROCKEFELLERX** [salim-lachdhaf/searchable_dropdown#230]
Hello,

How to allow the user to be able to tick only a certain number of items?
For example, it can select a maximum of 2 items.

Thanks you.

**Comment by vasilich6107** [comment]
@XROCKEFELLERX 
use `onBeforeChange` callback
Example of usage
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart#L81

**Comment by salim-lachdhaf** [comment]
there is a lot of options for your :

1- you can use @vasilich6107 proposition for validation after user confirmation
2- use `validator` option for real time validation
3- use `popupOnItemAdded` option for validation after adding each item
4- you can use all 1, 2 and 3 option together
