### ISSUE TITLE
Searchbox value erased when typing

### ISSUE THREAD

**Issue by franckobe** [salim-lachdhaf/searchable_dropdown#233]
Hi, 
I have a problem with the value in the searchbox
![recorded-2773159974676](https://user-images.githubusercontent.com/11754497/129694691-eca18f6d-d28a-44bf-8f7f-65d636981cf8.gif)

`DropdownSearch(
  items: ['toto', 'titi', 'tata'],
  mode: Mode.BOTTOM_SHEET,
  showSearchBox: true,
  showClearButton: true,
)`

**Comment by salim-lachdhaf** [comment]
which version are you using ?

**Comment by salim-lachdhaf** [comment]
no reply => close
