### ISSUE TITLE
Firebase example

### ISSUE THREAD

**Issue by InfinityCoder88** [salim-lachdhaf/searchable_dropdown#234]
Please guys, if someone know-how and have time can you please provide an example of how to integrate this amazing plugin with Firebase firestore database to search?

Please help me I'm new with flutter, thanks in advance!

**Comment by InfinityCoder88** [comment]
No one 🤔 please guide me how to achieve this with Firebase, thanks!

**Comment by salim-lachdhaf** [comment]
you can use the asyn methode `onFind`.
see examples for more details
