### ISSUE TITLE
Unexpected space 

### ISSUE THREAD

**Issue by TurboLeiGlobalPay** [salim-lachdhaf/searchable_dropdown#235]
This might be caused by 0.6.3

IOS 14.5 - iPhone 11 pro

`
return DropdownSearch<R>(
        mode: Mode.MENU,
        showSearchBox: true,
        showSelectedItem: true,
        items: items,
        label: "Reason",
        itemAsString: (R r) => r.toString(),
        compareFn: (i, s) => i.id == s!.id,
        selectedItem: items[0]);
`

![image](https://user-images.githubusercontent.com/67527688/130058613-76a396fd-966f-4804-b87e-9dc0f325d68d.png)

After rollback to 0.6.1, it works well.

![image](https://user-images.githubusercontent.com/67527688/130058631-9beeab38-7f39-4107-ab11-c02987da2b69.png)

**Comment by vasilich6107** [comment]
@TurboLeiGlobalPay do not hesitate to use search to find similar issues

https://github.com/salim-lachdhaf/searchable_dropdown/issues/216

**Comment by TurboLeiGlobalPay** [comment]
thanks and about to close this one
