### ISSUE TITLE
Is there no controller?

### ISSUE THREAD

**Issue by greenking19** [salim-lachdhaf/searchable_dropdown#236]
I have a page to modify data that needs to go to DropdownSearch. I use the backend to get the data and then backfill it to DropdownSearch.
Are there the following operations similar to FormTextField?
```dart
textEditingController.text = 'old value';
```
I didn’t find the controller for DropdownSearch,
Only searchBoxController this.

**Comment by vasilich6107** [comment]
@greenking19 check `example` to find an example how to set selected value outside from dropdown search
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart#L348

**Comment by javitrujillo99** [comment]
Did you find how to make the controller? I have the same question and in the link, he uses SearchFieldProps, which is a controller for the searchField, not for the dropdown search...

**Comment by javitrujillo99** [comment]
You have a parameter called onChanged in which you can get the data and put into a variable 😄

**Comment by greenking19** [comment]
> You have a parameter called onChanged in which you can get the data and put into a variable 😄

Hello, how do I use it? _openDropDownProgKey.currentState did not find onChanged. I want to change now I can't change

**Comment by greenking19** [comment]
> You have a parameter called onChanged in which you can get the data and put into a variable 😄

Actually very simple, the following code will do
```dart
_openDropDownProgKey.currentState
                            ?.changeSelectedItem(oldItem);
```

**Comment by greenking19** [comment]
> @greenking19 check `example` to find an example how to set selected value outside from dropdown search
> https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart#L348



> @greenking19 check `example` to find an example how to set selected value outside from dropdown search
> https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart#L348

Thank you. My needs have been resolved.
Thank you very much brother😎😎😎

**Comment by MukkiBassist** [comment]
please I need to place controller into this widget for firestore. how to?
