### ISSUE TITLE
Clearing searchBox via Controller Does not Trigger re-filter API

### ISSUE THREAD

**Issue by starlight93** [salim-lachdhaf/searchable_dropdown#237]
Hi, this package is so awesome.
I have some problem when I try to set searchBox Controller:
this is my onFind function, it has no problem

` 
onFind: (String filter) async {
    String nextPage = 'https://myApiDomain.net/get';
    var response = await Dio().get(
       nextPage,
       queryParameters: { "search": filter },
    );
    var models = MyModel.fromJsonList(response.data['data']);
    return models;
 },`

this is my controller.
`
  final TextEditingController myController = new TextEditingController();
`

then,
I try to set search box controller via:
`
searchBoxController : myController
`

and try to set the controller via other way by using search field props:
`searchFieldProps : TextFieldProps(
     controller : myController
)
`

When I try to clear myController's value in other place:
`myController.clear();
`

the input Text is set to empty as expected and printing the controller's value shows empty value as usual without any problem.
But clearing this controller's value does not trigger re-loading data.
How to trigger filtering method when I change the controller's value? Thanks

**Comment by salim-lachdhaf** [comment]
you can use ``_openDropDownProgKey.currentState
                            ?.clear()``
 see examples for more details

**Comment by starlight93** [comment]
Thanks a lot for the answer @salim-lachdhaf ,
I did doing this as the example, add the key prop like this.
```
DropdownSearch<UserModel>(
    key: _openDropDownProgKey,
    ...
)
```

And then try to clear the searchbox text inside onPressed function like this:

```
searchFieldProps: TextFieldProps(
    controller: employeeController,
    decoration: InputDecoration(
      suffixIcon: IconButton(icon: Icon(Icons.clear),iconSize: 20, onPressed: (){
          employeeController.clear();
          _openDropDownProgKey.currentState ?.clear(); //this is the code
          print('state was cleared');
      },
    )
),
onFind: (String filter) async {
   //I expect the filter string will be empty after I clear the searchbox via suffixIcon in the searchbox
   print(filter);  //but the old filter string is still remaining
   ... other function

}
```
Do I forget doing something ? Thanks for the answer.

**Comment by salim-lachdhaf** [comment]
i see your need.
in your case you don't need :
``_openDropDownProgKey.currentState ?.clear(); //this is the code``

you to use `isFilteredOnline` attribute to make call to the API each time you change text
