### ISSUE TITLE
Multi Selection feature

### ISSUE THREAD

**Issue by devalensio** [salim-lachdhaf/searchable_dropdown#238]
hi, this package is really useful, but i wonder if i can use multiSelection from DropdownSearch<String>. In the implementation i saw one example using multiSelection, but if tried it locally, it says 

> The class 'DropdownSearch' doesn't have a constructor named 'multiSelection'.

I'm using dropdown_search: ^0.6.3, is there something wrong with my implementation ?

**Comment by salim-lachdhaf** [comment]
yes we do support multi selection mode in beta version:
https://pub.dev/packages/dropdown_search/versions/1.0.0-beta2

the uses of multi selection you can find it in examples page

**Comment by devalensio** [comment]
@salim-lachdhaf thanks for the reply. It works now
