### ISSUE TITLE
When I set  showSelectedItem: true, it crashes UI/throws error.

### ISSUE THREAD

**Issue by ElixirMike** [salim-lachdhaf/searchable_dropdown#239]
If I just set the showSelectedItem attribute to true, UI crashes

When the exception was thrown, this was the stack
#2      new DropdownSearch (package:dropdown_search/dropdown_search.dart:286:16)
#3      _DetailsControlsState.build.<anonymous closure>
package:graceblocks_prototypes/widgets/details_controls.dart:168
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
#6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
...

**Comment by salim-lachdhaf** [comment]
do you solved the issue ?

**Comment by ElixirMike** [comment]
yes, was missing the compare function
