### ISSUE TITLE
can't prefill DropdownSearch value using providers state

### ISSUE THREAD

**Issue by devalensio** [salim-lachdhaf/searchable_dropdown#243]
i have a dropdown search wrapped by Consumer from provider.

and then i use the provider value to prefill the dropdown search using selectedItem: provider.selectedBrand. The issue is whenever there is a changes in the provider.selectedBrand, the dropdown value does not change at all, event though the widget is rebuild. Is there any solution for this problem i'm facing ?

return Consumer<VehicleProvider>(
      builder: (_, provider, __) {
        return Column(
          children: [
            Row(
              children: [
                Expanded(
                  flex: 1,
                  child: Padding(
                    padding: const EdgeInsets.all(4.0),
                    child: SizedBox(
                      height: 40,
                      child: DropdownSearch<VehicleModel>(
                        searchFieldProps: TextFieldProps(autofocus: true),
                        key: _brandsDropdownKey,
                        showSearchBox: true,
                        label: PlansConstants.brand,
                        mode: Mode.MENU,
                        itemAsString: (vehicle) => vehicle!.name,
                        items: provider.brands,
                        dropdownSearchDecoration: InputDecoration(
                          contentPadding: const EdgeInsets.fromLTRB(8, 8, 8, 0),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(5.0),
                          ),
                        ),
                        maxHeight: 300,
                        selectedItem: provider.selectedBrand,
                        enabled: provider.brands.isNotEmpty,
                        onChanged: (VehicleModel? brand) {
                          provider.selectBrand(
                            brand,
                            () => _selectBrandCallback(),
                          );
                        },
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ],
        );
      },
    );

i'm using dropdown_search: ^1.0.0-beta2

**Comment by salim-lachdhaf** [comment]
you can use this strategy to change selected item.
``_openDropDownProgKey.currentState?.changeSelectedItem("No");``

see examples page for more details
