### ISSUE TITLE
Is there any way to change checkbox color, and check mark color?

### ISSUE THREAD

**Issue by ElixirMike** [salim-lachdhaf/searchable_dropdown#245]
I don't see any attributes that would allow this, but is there any way to change the background color of checkbox and checkmark itself? Right now it's showing yellow background with white checkmark.

Also, any way to provide helper text to the search box?

**Comment by ElixirMike** [comment]
figured out the helpe;r text in search box, ..still looking for how to change checkbox

**Comment by salim-lachdhaf** [comment]
you can use `popupSelectionWidget`.

please read plugin code or documentation to figure out all possible configuration ...

don't post posts as bugs like this .

**Comment by sabari7320** [comment]
give some example code lines

**Comment by sabari7320** [comment]
popupSelectionWidget: (context, item, isSelected) {
        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 16),
          child: Row(
            children: [
              SizedBox(
                width: 24, // Adjust as needed
                height: 24, // Adjust as needed
                child: Checkbox(
                  value: isSelected,
                  onChanged: (value) {
                    if (widget.onChanged != null) {
                      List<T> selectedItems = _selectedItems.toList();
                      if (value ?? false) {
                        selectedItems.add(item);
                      } else {
                        selectedItems.remove(item);
                      }
                      setState(() {
                        _selectedItems = selectedItems;
                      });
                      widget.onChanged!(selectedItems);
                    }
                  },
                  checkColor: Colors.white, // Change checkbox color here
                  activeColor: kBlueGrey, // Change checkbox fill color here
                ),
              ),

            ],
          ),
        );
      },
