### ISSUE TITLE
Deselecting an item which was defined as selected Item ends up duplicating item in list.

### ISSUE THREAD

**Issue by ElixirMike** [salim-lachdhaf/searchable_dropdown#246]
Here is simplified code with defined items as well as defined selectedItem.

On load, it correctly shows the selected Item.
![image](https://user-images.githubusercontent.com/34098742/132041724-8574f4cb-e171-4dd8-b426-9a38b7998b55.png)

In bringing up list, it correctly shows Item selected:
![image](https://user-images.githubusercontent.com/34098742/132041764-1767c205-d52e-42d7-9f73-01e7ca614ef3.png)

I then click to de-select, the item, but upon closing, it's added the item twice.
![image](https://user-images.githubusercontent.com/34098742/132041823-95e11444-6bc8-44d7-960d-c243fcafc29e.png)

```
DropdownSearch<dynamic>.multiSelection(
                items: [{"data":"Shooter","optionid":1,"attributes":{"text":"white","color":"#009688"}},{"data":"Stategy","optionid":2,"attributes":{"text":"black","color":"#ff80ab"}},{"data":"Puzzle","optionid":3,"attributes":{"text":"#FFFFFF","color":"#F44336"}},{"data":"Platformer","optionid":4,"attributes":{"text":"#000000","color":"#FFEBEE"}},{"data":"RPG","optionid":5,"attributes":{"text":"black","color":"#ff8a80"}},{"data":"Open World","optionid":6,"attributes":{"text":"black","color":"#03A9F4"}},{"data":"Metrovania","optionid":7,"attributes":{"text":"#FFFFFF","color":"#C79702"}},{"data":"Simulation","optionid":8,"attributes":{"text":"#FFFFFF","color":"#DD2C00"}},{"data":"Horror","optionid":9,"attributes":{"text":"#FFFFFF","color":"#E91E63"}}],
                // maxHeight: 300,
                searchFieldProps: TextFieldProps(decoration: InputDecoration(labelText: 'Filter...')),
                isFilteredOnline: false,
                 compareFn: (item, selectedItem) =>
                    item?['optionid'] == selectedItem?['optionid'],
                showClearButton: true,
                dropdownBuilder: _multiSelectDropDownRender,
                popupItemBuilder: _multiSelectPopupBuilder,
                label: e['header'].toString().toUpperCase(),
                selectedItems: [{"data":"Shooter","optionid":1,"attributes":{"text":"white","color":"#009688"}}],
                onChange: (dynamic s) async {
                    await widget.updateFieldValue(
                        widget.rowData['id'], e['data'], s, 6);
                  },
                showSearchBox: true,
              )
```

**Comment by ElixirMike** [comment]
I thought it might be an issue with changing state, but it's not...still have this issue.

**Comment by salim-lachdhaf** [comment]
well, based on your description, i think it's not a bug. how ever , i think it's a bad implementation for your `compareFn`. so the selected item didn't match the new selected item , so both will be selected.

- an advise: prevent using json as string , use object , which are more clean ...

if you find the issue as described up, please notify us.

**Comment by ElixirMike** [comment]
Well, the comparefn did work to show the item selected in the list? So, it seems like that's working.
However, I can move it to an object and see if that makes any difference.

**Comment by salim-lachdhaf** [comment]
yes, it's a bug.
the bug is : to show the selected item we use `compareFn` but when clicking we just use `.contains`  and not `compareFn`.

i will fix that in the v1.0.0 release. thank you for reporting that.

but as adviced, prevent dynamic in your code in general, use object ...

**Comment by salim-lachdhaf** [comment]
problem solved in v1.0.0.

**Comment by ElixirMike** [comment]
Thx, when will v1.0.0 be released?

**Comment by salim-lachdhaf** [comment]
it's already released.

**Comment by ElixirMike** [comment]
I updated to the v1.0 version, . Now, when I deselect the item, it doesn't duplicate the item, but it doesn't deselect it either...it remains in the list.

I haven't move to objects yet, using a Map object . Would moving to objects resolve this or is there potentially still a bug?

**Comment by salim-lachdhaf** [comment]
using object in all case is more clean, and can make resolving issue easier ...

change to object and if it didn't wok past an example that has the issue

**Comment by ElixirMike** [comment]
So, I updated code to use objects, and I am seeing the same issue.

My option class

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import '../utils/GetColor.dart';

class GBOption {
  final int id;
  final String name;
  final Color? textColor;
  final Color? color;

  GBOption({required this.id, required this.name, this.textColor, this.color});

  static String getFinalColor(String color) {
    if(color=='white') return '#FFFFFF';
    if(color=='black') return '#000000';
    return color;
  }

  factory GBOption.fromJson(Map<String, dynamic> json) {
    return GBOption(
      id: json["id"] ?? json['optionid'],
      name: json["data"],
      textColor: json["attributes"]['text'] != null
          ? hexStringToColor(getFinalColor(json["attributes"]['text']))
          : null,
      color: json["attributes"]['color'] != null
          ? hexStringToColor(getFinalColor(json["attributes"]['color']))
          : null,
    );
  }

    static List<GBOption> fromJsonList(List list) {
    return list.map((item) => GBOption.fromJson(item)).toList();
  }
}

```

And the  Dropdown code

```
DropdownSearch<GBOption>.multiSelection(
                  items: options,
                  searchFieldProps: TextFieldProps(decoration: InputDecoration(labelText: 'Filter...')),
                  isFilteredOnline: false,
                   compareFn: (item, selectedItem) =>
                      item?.id == selectedItem?.id,
                  showClearButton: true,
                  popupSelectionWidget: BuildCheckbox,
                  dropdownBuilder: _multiSelectDropDownRender,
                  popupItemBuilder: _multiSelectPopupBuilder,
                  label: e['header'].toString().toUpperCase(),
                  selectedItems: _selectedItems.length >0 ? _selectedItems.firstWhere((element) => element['field']==e['data'])['data'] as List<GBOption> : [],
                  onChange: (dynamic s) async {
                    print(s);
                    },
                  showSearchBox: true,
                ),
```
When I click to remove an item, the onchange print statement still shows same 2 items in list, it doesn't remove it.
So, appears to still be an issue.

**Comment by ElixirMike** [comment]
Found a different way to set selected items, and got it working.

**Comment by legrandced** [comment]
@ElixirMike how did you set selected items ? I am facing the same issue too and I really would like to solve it. Could you please post your "selectedItems" function ?

**Comment by legrandced** [comment]
Ok I found the solution. Effectively I was not using correctly the **selectedItems** functions. In my use case, I was using a **myMap = Map<Object1, List<Object2>>**, such that I displayed multiple **DropdownSearch<Object2>.multiSelection()** widgets, one for each **Object1**.

I used : 
`selectedItems: myMap.keys.firstWhere((element) => element.object1_id== _object1.object1_id, orElse: () => null),`
instead of simply using :
`selectedItems: myMap[_object1] ?? [],`

The first use did not take into account the instance of the object, so the Flutter id of the object. The comparison could then not be correctly done.
