### ISSUE TITLE
How to customize the appearance of the dropdown button?

### ISSUE THREAD

**Issue by ChanakaDev** [salim-lachdhaf/searchable_dropdown#248]
![Screenshot 2021-09-08 181250](https://user-images.githubusercontent.com/62310700/132511276-8efc8d41-63dd-4d73-bd51-203700732985.jpg)

**Comment by vasilich6107** [comment]
@ChanakaDev do not hesitate to check the docs

https://github.com/salim-lachdhaf/searchable_dropdown#layout-customization

You can use `dropDownButton` for this

**Comment by salim-lachdhaf** [comment]
as said @vasilich6107 , please don't hesitate to take a look to the docs.
https://pub.dev/documentation/dropdown_search/latest/dropdown_search/DropdownSearch-class.html
