### ISSUE TITLE
Problems using the "Dialog" mode

### ISSUE THREAD

**Issue by leanhro2812** [salim-lachdhaf/searchable_dropdown#25]
Problems using the "Dialog" mode
The white space for the first item with top , the last item with the bottom is quite large
Using maxHeight does solve the smaller dialog display but doesn't solve the white space top and bottom

https://i.ibb.co/sFRPqJD/Screen-Shot-2020-07-15-at-12-53-55-PM.png

**Comment by salim-lachdhaf** [comment]
Could you paste an examlpe of your code ?

**Comment by leanhro2812** [comment]
@salim-lachdhaf 
Hey bro.
I tried creating with a brand new project.
Example:
`DropdownSearch<String>(
              mode: Mode.DIALOG,
              showSelectedItem: true,
              items: ["Brazil", "Italia (Disabled)", "Tunisia", 'Canada'],
              label: "Menu mode",
              hint: "country in menu mode",
              popupItemDisabled: (String s) => s.startsWith('I'),
              onChanged: print,
              selectedItem: "Brazil",
              maxHeight: 300,
            ),`

**Comment by leanhro2812** [comment]
@salim-lachdhaf  
Have you come across this issue?

**Comment by salim-lachdhaf** [comment]
No, could you test on another device, or on android device

**Comment by binhodev** [comment]
I have same problem with 2 devices

**Comment by salim-lachdhaf** [comment]
Are you sure that your data did not contains any empty string ?

**Comment by salim-lachdhaf** [comment]
this issue is fixed in this next version v0.4.6
