### ISSUE TITLE
Clear button is visible even though selectedItem is null

### ISSUE THREAD

**Issue by slavap** [salim-lachdhaf/searchable_dropdown#250]
![image](https://user-images.githubusercontent.com/4129763/132924671-c185116e-9541-42ab-8701-8a00cb8a69e3.png)

I was able to fix this bug by changing _itemToList() method:

```dart
  List<T> _itemToList(T? item) {
    List<T?> nullableList = List.filled(1, item);
    return nullableList.where((e) => e != null).map((e) => e!).toList();
    //return nullableList.whereType<T>().toList();
  }
```
As I see under debugger **nullableList.whereType<T>().toList()** just gives [null] instead of []

Probably it is Flutter 2.2.3 problem, but I cannot migrate my project to 2.5.0 for some period of time.

**Comment by vasilich6107** [comment]
@slavap could you provide the code which reproduces the bug?

**Comment by slavap** [comment]
@vasilich6107 
You have code in my previous post.
Populate list with null and then compare results of
list.where((e) => e != null).map((e) => e!).toList();
Vs
list.whereType<T>().toList();

**Comment by vasilich6107** [comment]
@slavap so the issue is that you are trying to populate list with `null` items...
I do not see the bug here

**Comment by slavap** [comment]
@vasilich6107 setting selectedItem to null have always worked to clear drop down. It is not working anymore because of using  list.whereType in the code of this widget.

**Comment by vasilich6107** [comment]
@slavap i suppose you can set value to an empty array?

**Comment by slavap** [comment]
@vasilich6107 No, please open this widget code and look how _ itemToList method is used.

**Comment by salim-lachdhaf** [comment]
re Tested and the plugin seems working fine by using `_openDropDownProgKey.currentState?.changeSelectedItem(null);` or `_openDropDownProgKey.currentState?.changeSelectedItem([]);`  or `_openDropDownProgKey.currentState?.clear();`

i'm using the last version of Flutter SDK (v2.5.2)
