### ISSUE TITLE
dropdown appears behind keyboard in mode.Menu

### ISSUE THREAD

**Issue by dragongesa** [salim-lachdhaf/searchable_dropdown#252]
when dropdown placed in bottom part of the screen it will be in behind the keyboard when focused into searchbox.

`Doctor summary (to see all details, run flutter doctor -v)
:
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [
Version 10.0.19043.1200], locale id-ID)
[√] Android toolchain - develop for Android devices (Andro
id SDK version 30.0.3)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.60.0)
[√] Connected device (1 available)

• No issues found!

`

**Comment by vasilich6107** [comment]
Check the comment

https://github.com/salim-lachdhaf/searchable_dropdown/issues/150#issuecomment-840082887

**Comment by dragongesa** [comment]
It will be cool if the dropdown move up like above the dropdown button

**Comment by salim-lachdhaf** [comment]
in the next release (v1.0.1) you can use `positionCallback` property to change menu position.
