### ISSUE TITLE
Show default value at startup in DropdownSearch<UserModel>

### ISSUE THREAD

**Issue by byblady** [salim-lachdhaf/searchable_dropdown#254]
I'm trying to have a default value at the beginning, but I can't do it, could you help me please.

Also it would be good if the value is not in the list, let you write the value.

Thanks

**Comment by byblady** [comment]
I did the following, add in the if of item null the default value, it works fine.

`Widget _customDropDownExample(BuildContext context, UserModel? item) {
    if (item == null) {
      return Container(
        child: ListTile(
          contentPadding: EdgeInsets.all(0),
          leading: ConstrainedBox(
            constraints: BoxConstraints(
              minWidth: 40,
              minHeight: 40,
              maxWidth: 40,
              maxHeight: 40,
            ),
            //child: SvcP Image.asset('asset/countries/'+item['icon'], fit: BoxFit.cover),
            child: SvgPicture.asset('asset/countries/icons/chile.svg',
                //color: Colors.red,
                semanticsLabel: ''),
          ),
          //title: Text(item.name),
          title: Text("+56"),
          /*subtitle: Text(
          item.phoneNumberCode.toString(),
        ),*/
        ),
      );
    }

    return Container(
      child: (item.icon == "")
          ? ListTile(
              contentPadding: EdgeInsets.all(0),
              leading: CircleAvatar(),
              title: Text("No item selected"),
            )
          : ListTile(
              contentPadding: EdgeInsets.all(0),
              leading: ConstrainedBox(
                constraints: BoxConstraints(
                  minWidth: 40,
                  minHeight: 40,
                  maxWidth: 40,
                  maxHeight: 40,
                ),
                //child: SvcP Image.asset('asset/countries/'+item['icon'], fit: BoxFit.cover),
                child: SvgPicture.asset('asset/countries/' + item.icon,
                    //color: Colors.red,
                    semanticsLabel: ''),
              ),
              //title: Text(item.name),
              title: Text(item.phoneNumberCode),
              /*subtitle: Text(
          item.phoneNumberCode.toString(),
        ),*/
            ),
    );
  }`

**Comment by salim-lachdhaf** [comment]
you can use `selectedItem`. see examples for more details

**Comment by Ivanrputra** [comment]
> you can use `selectedItem`. see examples for more details

where or which part from the example? i cant get it,
