### ISSUE TITLE
Add showLoader property to show loader in the modal

### ISSUE THREAD

**Issue by anuragarwalkar** [salim-lachdhaf/searchable_dropdown#255]
I'm getting the items from the API for multiple dropdowns on init of the component hence I want to show the loader till items get loaded. I've tried the onFind method that way loadingBuilder show the loader but the issue is onFind method gets called when we click on the dropdown. But I want to get data for multiple dropdowns at the same time on the component init.

**Comment by vasilich6107** [comment]
@anuragarwalkar there is no clear understanding why are you trying to get values for multiple dropdown instead one by one
As far as cannot have more than one modal opened

**Comment by vasilich6107** [comment]
@anuragarwalkar you can add to your `fetching` function all three requests and return only corresponding one to the widget and save the other into variables
