### ISSUE TITLE
maxHeight not work when focus search field at Mode.BOTTOM_SHEET

### ISSUE THREAD

**Issue by killerhp12** [salim-lachdhaf/searchable_dropdown#256]
version 0.4.8
Normal
https://upanh.org/image/fddlUa

When focus search field
https://upanh.org/image/fddC5b

My code:
  Widget _homeCityField() {
    return Container(
      child: DropdownSearch<City>(
        maxHeight: Utils.viewHeight(0.5, context),
        dropdownSearchDecoration: inputStyle,
        searchBoxDecoration: inputStyle,
        mode: Mode.BOTTOM_SHEET,
        items: _listCity,
        dropdownBuilder: _ddHomeCity,
        popupItemBuilder: _cpHomeCity,
        label: "Chọn thành phố",
        showSearchBox: true,
        selectedItem: this._selectedHomeCity,
        dropdownBuilderSupportsNullItem: true,
        onChanged: (data) {
          this._getListDistrict('2', 'home', data.code);
          setState(() {
            this._homeCityCTL = data.code;
          });
        },
      ),
    );
  }

**Comment by vasilich6107** [comment]
@killerhp12 your version is too old.
Update to the latest one
