### ISSUE TITLE
How to I change OK button text and style?

### ISSUE THREAD

**Issue by ertekinozturgut** [salim-lachdhaf/searchable_dropdown#257]
![image](https://user-images.githubusercontent.com/33807207/133947967-fe90d1ba-8e23-4ba0-ad49-b7491684d59a.png)
Hi!
Firstly, I need change text of "OK" button that in picture.
That is important for me.

After that,  I need change style of it. 
But changing style is not important for me.

Could you help me?

Regards.

**Comment by vasilich6107** [comment]
Use `popupValidationMultiSelectionWidget` prop
