### ISSUE TITLE
Needed option for MENU mode to control menu width.

### ISSUE THREAD

**Issue by slavap** [salim-lachdhaf/searchable_dropdown#26]
Currently menu width is the same as widget width. Sometimes widget is small but open menu should be wider. There is already dialogMaxWidth, so adding popupMaxWidth would be nice.

![image](https://user-images.githubusercontent.com/4129763/88133381-c5114e00-cb96-11ea-8c81-e0f0865e28e4.png)

**Comment by salim-lachdhaf** [comment]
I see not the need for that , beside the menu used to be like this at least to know witch widget opened the menu ...
to solve that you can make parent widget larger, or use another mode.

**Comment by slavap** [comment]
@salim-lachdhaf it is not so rare that designers are using such concept. Of course I can use button with popup menu in such cases, but it is not very convenient, I prefer to have uniform widgets. That is sad you don’t want to add it, and actually not consistent with existing already dialogMaxWidth.

**Comment by jianzai9607** [comment]
![2c47be72-0db9-4e05-a63a-fd24cf4b9b74](https://user-images.githubusercontent.com/65189320/153994585-28321cc2-3838-4031-84cf-bf7945c8e977.png)
@salim-lachdhaf Hope to add this feature, cause there are really the use case that the menu width is larger than the input size, and using the same mode for uniform design.

**Comment by fehernyul** [comment]
Please reopen this ticket, or offer a workaround tricks.
