### ISSUE TITLE
Any way to default the list to open/expanded?

### ISSUE THREAD

**Issue by ElixirMike** [salim-lachdhaf/searchable_dropdown#261]
Is there a way to have the list appear in open mode, instead of requiring a click? Alternatively, is there a way to programmatically open the List?

**Comment by vasilich6107** [comment]
@ElixirMike 
Check the example
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart#L343

**Comment by ElixirMike** [comment]
Thx, it doesn't seem to be working for me? Could their be an issue on the multi-select mode?

```
final _openDropDownProgKey = GlobalKey<DropdownSearchState<String>>();

 DropdownSearch<dynamic>.multiSelection(
                      key: _openDropDownProgKey,
                      items: _items,
 ....}
```

and using button
```
 IconButton(icon: Icon(Icons.precision_manufacturing),onPressed: () {
            _openDropDownProgKey.currentState?.openDropDownSearch();
          },),
```

**Comment by vasilich6107** [comment]
![image](https://user-images.githubusercontent.com/6721286/134169742-544dbac4-5f45-4339-83f8-c6d7eb14cfaa.png)

**Comment by vasilich6107** [comment]
![image](https://user-images.githubusercontent.com/6721286/134169768-a4908952-edd7-4d45-bc92-408ce9ca9d4d.png)

**Comment by vasilich6107** [comment]
@ElixirMike first of all launch the `example` and do your tests.
If everything is fine -> move you your code

If not -> it will be easy to copy/paste code for reproduction to explain the issue

**Comment by ElixirMike** [comment]
Did more testing, so it works when the items are strings...no issue. I then used simple objects, and it doesn't work.

```
class GBOption {
  final String name;
  final int id;
  GBOption(this.name,this.id);
}
```

DropdownSearch<GBOption>.multiSelection(
                key: _openDropDownProgKey,
                compareFn: (item, selectedItem) => item?.id == selectedItem?.id,
                items: [GBOption('test', 1),GBOption('test2', 2)],
                label: "confirm",
                showSelectedItems: true,
                dropdownButtonSplashRadius: 20,
              )
```

**Comment by vasilich6107** [comment]
@ElixirMike 

```
              DropdownSearch<GBOption>.multiSelection(
                key: _openDropDownProgKey1,
                // items: ["Yes", "No"],
                items: [GBOption('test', 1), GBOption('test2', 2)],
                label: "confirm",
                compareFn: (a, b) => a == b,
                showSelectedItems: true,
                dropdownButtonSplashRadius: 20,
              ),
```

**Comment by vasilich6107** [comment]
@ElixirMike 
```
final _openDropDownProgKey1 = GlobalKey<DropdownSearchState<GBOption>>();
```

**Comment by vasilich6107** [comment]
@ElixirMike 
Force strong mode in your analyzer
https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks

and do not forget about types

**Comment by ElixirMike** [comment]
That worked, missed the type setting on the key. Thx!
