### ISSUE TITLE
Match default style with native dropdown button

### ISSUE THREAD

**Issue by leoshusar** [salim-lachdhaf/searchable_dropdown#262]
I think it would be nice to have the default style same as the native dropdown button, it would look better when those two widgets are in the same form.

![image](https://user-images.githubusercontent.com/13891066/134384891-22f05096-0d2b-48dc-a445-a51ae1c5d1c3.png)
![image](https://user-images.githubusercontent.com/13891066/134385152-9db9816f-8fd9-41b6-94e2-3f770e826383.png)

Changes:
- match widget height
- disable mouse hover color change
- remove button paddings
- maybe something else I cannot think of now?

**Comment by vasilich6107** [comment]
@leoshusar 
to match the height  - set `showAsSuffixIcons` to `true`
to redefine dropdown button set `dropDownButton` to whatever icon you like

We cannot redefine default look and feel cause it will break others code.

@salim-lachdhaf I suppose we can close it
