### ISSUE TITLE
Double scrollbar bug

### ISSUE THREAD

**Issue by leoshusar** [salim-lachdhaf/searchable_dropdown#263]
Since Flutter 2.2, ListViews now have scrollbars by default on web and desktop. That means there are now two scrollbars rendered and scroll drag does not work at all.

Confirmed removing Scrollbar in `SelectionWidget` fixes the issue.

**Comment by vasilich6107** [comment]
@leoshusar try to hide the `scrollbar` by setting thikness and hoverThikness to 0

**Comment by leoshusar** [comment]
Thanks, although this works, this should be considered only as a workaround.

**Comment by vasilich6107** [comment]
@leoshusar 
Sure)
I will make a PR to fix this more elegantly.
But the release schedule is pretty unexpected)
So it is better to have workaround than nothing)))

**Comment by salim-lachdhaf** [comment]
Re Tested on Google Chrome using last Flutter sdk (2.5.2) => no issue
