### ISSUE TITLE
Untick checkbox will still add the selected item

### ISSUE THREAD

**Issue by JustonJ99** [salim-lachdhaf/searchable_dropdown#270]
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-30 at 11 01 50](https://user-images.githubusercontent.com/37526525/135379075-66616c2c-9cca-4351-813d-1b4f8a364e86.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-30 at 11 01 56](https://user-images.githubusercontent.com/37526525/135379153-5b5c06f2-f3b6-44b3-8103-83c68b2ff51a.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-30 at 11 02 04](https://user-images.githubusercontent.com/37526525/135379188-589e99e9-425f-400f-8376-64c5bff662cb.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-30 at 11 02 09](https://user-images.githubusercontent.com/37526525/135379206-fa2a1248-28b9-4036-a904-2657b0f86bdb.png)

This is user item list testing. As you can see on 3rd and 4th image, I unticked the checkbox for remove the selected item but the result is added both item into list again. This make me confuse. Thank you. @vasilich6107

**Comment by salim-lachdhaf** [comment]
this will be fixed in the next release v1.01, it be release today.
