### ISSUE TITLE
Dropdown search

### ISSUE THREAD

**Issue by hassanrehman01398** [salim-lachdhaf/searchable_dropdown#272]
Dropdown search is hiding behind keyboard when searching.

**Comment by salim-lachdhaf** [comment]
it's a normal behavior for the menu mode,  use other mode.
see here https://github.com/salim-lachdhaf/searchable_dropdown/issues/252

**Comment by hassanrehman01398** [comment]
Is there any other way to adjust with menu mode as other mode will not give at a dropdown look. Thanks
