### ISSUE TITLE
emptyBuilder is used during first fetch instead of loadingBuilder

### ISSUE THREAD

**Issue by Daneel87** [salim-lachdhaf/searchable_dropdown#273]
When first opened and fetching data from api with onFind, the emptyBuilder is showed instead of the loadingBuilder.

**Comment by salim-lachdhaf** [comment]
this is the code :
``
if (snapshot.hasError) {

                      return _errorWidget(snapshot.error);

                    } else if (!snapshot.hasData) {

                      return _loadingWidget();

                    } else if (snapshot.data!.isEmpty) {

                      if (widget.emptyBuilder != null)
                        return widget.emptyBuilder!(
                          context,
                          widget.searchFieldProps?.controller?.text,
                        );
                      else
                        return const Center(
                          child: const Text("No data found"),
                        );
                    }``

**Comment by salim-lachdhaf** [comment]
i see no issue

**Comment by Daneel87** [comment]
Yes but  the behaviour is not the correct one once inside the app.

The problem is when the item list is still empty because first fetch has not been done yet, so it's normal that it shows "no data found", but you should consider adding a check for the first load.

**Comment by salim-lachdhaf** [comment]
in stream the `(snapshot.hasData)` is what define if we have data or not.
and after that we check if we have an empty data or not ...

**Comment by salim-lachdhaf** [comment]
if fetch data have not been finished yet , `hasData` is false , so the app is loading ...

**Comment by Daneel87** [comment]
I understand, but there has to be something if it behaves this way...

**Comment by salim-lachdhaf** [comment]
i didn't notice anything like that before, and it's the first time a user report for that bug , could you paste a gif or a small video and piece of your implementation of the dropdown

**Comment by Daneel87** [comment]
I don't have that since I now wrapped it into a FutureBuilder to call it directly with a full items List and using like it was local.

**Comment by salim-lachdhaf** [comment]
but in your first comment you write `onFind`, if you want to use `sync` items use `items` directely and not `onFind`

**Comment by Daneel87** [comment]
I had to fix in some way and changed to that.

**Comment by salim-lachdhaf** [comment]
you confirm that your problem is resolved ?

**Comment by Daneel87** [comment]
THe problem is not resolved, mine is a workaround.
If you could fix the thing would be better.

I'll try and document better the issue ASAP

**Comment by salim-lachdhaf** [comment]
if i could take a look to your implementation of the dropdown i sure i can find the problem
