### ISSUE TITLE
 No version of NDK matched the requested version 21.0.6113669. Versions available locally: 22.1.7171670, 23.0.7599858

### ISSUE THREAD

**Issue by rulefahd** [salim-lachdhaf/searchable_dropdown#275]
No version of NDK matched the requested version 21.0.6113669. Versions available locally: 22.1.7171670, 23.0.7599858

how can i solve this please

**Comment by salim-lachdhaf** [comment]
as mentionned @vasilich6107 , this not related to the package.

to solve it, open Android sdk manager and download 21.0.6113669 ndk.
