### ISSUE TITLE
no options for closed Dialog hint, label, border color.

### ISSUE THREAD

**Issue by FriendlyNeighbor** [salim-lachdhaf/searchable_dropdown#28]
closed dialog means the dropdown search widget is showing and waiting for actions.

how can I change the layout of it?

nothing in the example file fixed my problem.

seems like when I click the dropdownsearch, the focus color automatically switch to primary color without configuring it. how about when it's unfocused and haven't selected anything yet? border color, radius, label and hint colors?

**Comment by salim-lachdhaf** [comment]
You can customize `dropdownSearchDecoration`.
