### ISSUE TITLE
Multiselect incorrect object "checked"

### ISSUE THREAD

**Issue by brneas** [salim-lachdhaf/searchable_dropdown#284]
When using the dialog mode with a dropdown multi select when you select an item and the search for another one, the checkbox does not disappear. 

You can reproduce this by having a dropdown with multiple items.
1. Select the first item in the list
2. Search for an item that is not the one you selected
3. You'll see that the item you searched for is "checked" but you did not select it and within the code it is not technically checked. The checkbox does not get cleared.

There should be a gif/video attached with an example of this happening
![VS4IhqdNhq](https://user-images.githubusercontent.com/9089998/138286127-374209f1-02cd-4b26-bf47-41b7cc5a2a78.gif)
.

**Comment by salim-lachdhaf** [comment]
could you past your compareFn if your object is not a string
