### ISSUE TITLE
Add clear method after button pressed

### ISSUE THREAD

**Issue by agustinutec** [salim-lachdhaf/searchable_dropdown#288]
The issue there i'm facing is this:

I currently using 2 dropdownSearch widgets, one for category's and the other for sub category's.

When i clear the value of category dropDown i having a really rough time trying to clear the subCategory selected value. 
I try this in a lot of ways and i couldnt find how to do it, so i have start to think is a bug of the widget.

I leeve you some screenshots so you can understandme better
![image](https://user-images.githubusercontent.com/86895558/139754082-e662f356-3a3a-4f11-b9f2-05d8d3da0510.png)
![image](https://user-images.githubusercontent.com/86895558/139754192-8b04643d-6ee6-486f-8686-6901008e8b5f.png)

**Comment by salim-lachdhaf** [comment]
you can use a globalKey for your subCategory and clear it dymically, 
`gkeySubCategory.currentState.clear()`

you can find an example of use of the globalkey in the examples page

**Comment by agustinutec** [comment]
Thanks, that works.

**Comment by rehamalraee24** [comment]
@agustinutec how did you implement it? It is not working for me! Set state called after dispose!
