### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by tuskinhu** [salim-lachdhaf/searchable_dropdown#289]
Is there any way I can customize some messages like this? 
That message is displayed when i dont have any itens to show.

![image](https://user-images.githubusercontent.com/606731/140407162-ef2d40aa-3e8e-4279-9f71-c44f22eab730.png)

**Comment by vasilich6107** [comment]
Do not hesitate to look into available properties

https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L145
