### ISSUE TITLE
Change dropdown text style

### ISSUE THREAD

**Issue by poringe** [salim-lachdhaf/searchable_dropdown#290]
Is there any way I can customize this text style (font weight, size, color etc..)

![image](https://user-images.githubusercontent.com/17471198/140471748-e26d3845-546d-47b4-b0b3-2825e4fbb77c.png)

i've try some search but no luck

**Comment by vasilich6107** [comment]
You were not patient enough ;-)
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L100

**Comment by poringe** [comment]
thanks

i got solution  by using 'dropdownBuilder'

```
dropdownBuilder: (_, _text) => Container(
     child: _text != null
      ? Text(
     _text,
     style: TextStyle(
        color: Colors.red,
        fontSize: widthPage * 0.03,
         ),
     )
     : null), 
```

![image](https://user-images.githubusercontent.com/17471198/140508501-97d8eac4-3669-4692-aca1-2cdb34ca21d3.png)
