### ISSUE TITLE
can you add scaffold bottom sheet mode ?

### ISSUE THREAD

**Issue by jayachandra572** [salim-lachdhaf/searchable_dropdown#291]
@salim-lachdhaf

**Comment by vasilich6107** [comment]
@jayachandra572 any related links to flutter docs?

**Comment by jayachandra572** [comment]
> @jayachandra572 any related links to flutter docs?

https://api.flutter.dev/flutter/material/ScaffoldState/showBottomSheet.html

checkout above link

**Comment by jayachandra572** [comment]
@salim-lachdhaf @vasilich6107 

I built a form it's includes dropdowns and text fields, in large screen devices [desktops] dropdown modal bottom sheet occupy full width it's weird. attached sample below.

**actually happening**: 
![dropdown](https://user-images.githubusercontent.com/59283888/140908538-b0fbdc37-7abd-445f-8725-8ff1fba34e40.png)

**Excepted**
![Screenshot from 2021-11-09 16-09-20](https://user-images.githubusercontent.com/59283888/140909398-e701d96e-3f98-48c0-b877-3c41abea6650.png)

**Comment by salim-lachdhaf** [comment]
a new mode "BottomSheet" that solves this problem.
in the next version we will have 3 mode:
MENU, BOTTON_SHEET, MODAL_BOTTOM_SHEET.

So, just wait for the new version release ;)
