### ISSUE TITLE
how to add custom sort logic for already filtered data?

### ISSUE THREAD

**Issue by AErmek** [salim-lachdhaf/searchable_dropdown#293]
```
filteredList.sort((a, b) =>
              a.toLowerCase()
                .indexOf(filter)
                .compareTo(b.toLowerCase().indexOf(filter)
```
where i can add this kind of logic?

**Comment by salim-lachdhaf** [comment]
not clear, please explain more

**Comment by AErmek** [comment]
Hi, thanks for your feedback, i will try to explain more clearly

for example: 
var streets = ["testabc","abc"];
`return DropdownSearch<String>(... items:streets);`

when i will input search value "abc",
output suggestions will be : 1."testabc" 2."abc"
expected suggestions : 1."abc" 2."testabc"

so i want to output suggestions with more appropriate order by search value.

Thanks

**Comment by salim-lachdhaf** [comment]
here we can do nothing, it is a normal behavior ...,
but you can play with `compareFn` to get more precision results..., sorry there is no solution
