### ISSUE TITLE
How to implement "Select All" and "Select None" for multi selection dropdown?

### ISSUE THREAD

**Issue by jayaxel** [salim-lachdhaf/searchable_dropdown#294]
Hi! I'm trying to implement a Select All and Select None button in the multi selection dropdown which basically selects all (or deselects all) items in the dropdown, but am not able to find a way to update the selection in the dropdown itself.

The following is what I've tried: editing `popupValidationMultiSelectionWidget` to include the buttons, but I can't figure out how to select/unselect the items in the list.

I _can_ update the `selectedItems` list state, but that will require the dropdown list to be closed (and the state being updated triggers other parts of the app. Instead, my intention is to allow users to continue selecting the items in the list after clicking select all/none.

Any tips?

```
popupValidationMultiSelectionWidget: (context, list) {
                    final ButtonStyle textButtonStyle = TextButton.styleFrom(
                      primary: Colors.black,
                    );
                    return Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Expanded(
                          child: TextButton(
                            style: textButtonStyle,
                            onPressed: () {
                              // How should I select all items in the list?
                            },
                            child: const Text('All'),
                          ),
                        ),
                        Expanded(
                          child: TextButton(
                            style: textButtonStyle,
                            onPressed: () {
                              // How should I unselect all items in the list?
                            },
                            child: const Text('None'),
                          ),
                        ),
                        Expanded(
                          child: ElevatedButton(
                            style: ElevatedButton.styleFrom(
                              primary: Colors.black,
                            ),
                            onPressed: () {
                              // this closes the dropdown list and updates the state
                             updateFieldMulti(field, list);
                              Navigator.pop(context);
                            },
                            child: const Text('Done'),
                          ),
                        ),
                      ],
                    );
                  },
```

**Comment by vasilich6107** [comment]
@jayaxel 
Check the example on how to select items programmatically 
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart#L451

**Comment by jayaxel** [comment]
hey @vasilich6107 thanks for the response! unfortunately, that doesn't solve my problem too.
Here's the code i added, in addition to creating the key and adding it in the key param:
```
                          child: TextButton(
                            style: textButtonStyle,
                            onPressed: () {
                              progKey.currentState?.changeSelectedItems([]);
                            },
                            child: const Text('None'),
                          ),
```

To illustrate what's happening and my intention, here's a screenshot of my dropdown widget:
![image](https://user-images.githubusercontent.com/10866113/141279415-39f680aa-eb2f-475a-8043-61cd57690c19.png)

Pressing the "None" button removes the blue items, like in this screenshot:
![image](https://user-images.githubusercontent.com/10866113/141279598-1ed33228-2d9a-4261-b378-eeb17bdee51e.png)

Instead, what I'm looking for is where I'm able to press the "None" button and remove the selections from the dropdown list, like so:
![image](https://user-images.githubusercontent.com/10866113/141279709-0aca7ebd-d1b1-44db-b705-d30cab0a95f9.png)

**Comment by salim-lachdhaf** [comment]
add` Navigator.pop(context);` after ` progKey.currentState?.changeSelectedItems([]);` to dismiss the dialog, for now you can not dynamically change item on the dialog...

**Comment by salim-lachdhaf** [comment]
i'm developping a solution for that, it will be a good feature, it will be released today :)

**Comment by salim-lachdhaf** [comment]
check v2.0.1 first example ...

**Comment by jayaxel** [comment]
amazing! thanks @salim-lachdhaf!
