### ISSUE TITLE
How to listen for item removed?

### ISSUE THREAD

**Issue by AndrewBert** [salim-lachdhaf/searchable_dropdown#298]
I have variable that I want to contain the selected items. I see onChanged allows me to see which items were added, but not which items were removed. I need to update my selected list.

This leads me to believe there is a better way to do this, since my need is the most basic of needs.  If anyone has a solution, please let me know.

**Comment by vasilich6107** [comment]
@AndrewBert store the iterations of changes somewhere outside the widget and calculate the diff manually

**Comment by salim-lachdhaf** [comment]
you can use `popupOnItemRemoved`

**Comment by AndrewBert** [comment]
> @AndrewBert store the iterations of changes somewhere outside the widget and calculate the diff manually

A problem I have with that is I don't know of a way to listen to the clear button being used. It does not trigger `popupOnItemRemoved`.  `onChanged' is hit, but you cannot tell which items are removed from onChanged.

**Comment by salim-lachdhaf** [comment]
i tested `popupOnItemRemoved` and it works fine.

```
popupOnItemRemoved: (selectedItems, removedItem) {
       print(removedItem);
}
```
But i don't know which clear button you are talking about ?

**Comment by AndrewBert** [comment]
The X button that clears the selected items. 
![image](https://user-images.githubusercontent.com/46977613/141700591-56d567d8-69a7-40be-a0c4-cbc36b100241.png)

**Comment by salim-lachdhaf** [comment]
that X it clears all selected item; which means you have no selected items after clicking on that button

**Comment by AndrewBert** [comment]
I don't see how @vasilich6107 solution will overcome that problem. I can't manage the changes outside the widget if the clear button doesn't have a listener. Are you suggesting the clear button shouldn't even be used? 

My implementation needs are very basic. Tracking the state of the selected items should be at a core of a library like this. I feel like I'm missing something.

I appreciate your replies!

**Comment by AndrewBert** [comment]
Also `popupOnItemRemoved` is not reliable because it is called before the user confirms their changes. If the user clicks away from the dialog before confirming changes, then the input is not saved.
