### ISSUE TITLE
Fully customize dropdown

### ISSUE THREAD

**Issue by jayypee** [salim-lachdhaf/searchable_dropdown#299]
![Screenshot_1637000361](https://user-images.githubusercontent.com/57446563/141834047-7b65f440-5c5d-496d-ab18-863cba10415b.png)

The first one is your package. I'm trying to customize it to get the second one but I can't.

**Comment by salim-lachdhaf** [comment]
yes, you can fully customize the widget and get exactly what you mentionned.
just take a look to the examples page.
