### ISSUE TITLE
Cannot set height of dropdown widget even when dropdownBuilder is implemented

### ISSUE THREAD

**Issue by lorensewusu** [salim-lachdhaf/searchable_dropdown#30]
Customising the `dropdownBuilder` does not change the height of the dropdown_search widget. It basically just changes the width of the displayed/selected item. There are lots of trailing padding around the widget which seems to make it look bigger in terms of height.
This is when i make the dropdownbuilder have a very small height, it basically did not affect the height of the widget itself.
![image](https://user-images.githubusercontent.com/6972732/89136608-7bc4e500-d52c-11ea-8148-067c3eff6717.png)

From the image below
![image](https://user-images.githubusercontent.com/6972732/89136663-bcbcf980-d52c-11ea-90f1-d1d195b6fa72.png)

You can see that with the same text style the dropdown search has a bigger height than the password textfield below.

If i try to reduce the height of the widget by putting it in a container and squashing the height, the dropdown button goes out of place, look at the screenshot below

![image](https://user-images.githubusercontent.com/6972732/89136748-19201900-d52d-11ea-83f6-393f0b3eff30.png)

**Comment by robbysoerya** [comment]
you can custom decoration from parameter dropdownSearchDecoration, example

```
dropdownSearchDecoration: InputDecoration(
border: OutlineInputBorder(),
contentPadding: EdgeInsets.only(left: 8.0),
)
```

**Comment by salim-lachdhaf** [comment]
This two solves your problem:

https://github.com/salim-lachdhaf/searchable_dropdown/issues/27

https://github.com/salim-lachdhaf/searchable_dropdown/issues/7
