### ISSUE TITLE
space button not working in desktop version

### ISSUE THREAD

**Issue by Shams-Mahmoud** [salim-lachdhaf/searchable_dropdown#300]
space btn in menu mode not working  when user search inside dropdown list

**Comment by salim-lachdhaf** [comment]
duplicated https://github.com/salim-lachdhaf/searchable_dropdown/issues/249

**Comment by Shams-Mahmoud** [comment]
@salim-lachdhaf 

please review pull request to fix space key

**Comment by salim-lachdhaf** [comment]
this will be fixed in the next release
