### ISSUE TITLE
Change list physics

### ISSUE THREAD

**Issue by jayypee** [salim-lachdhaf/searchable_dropdown#301]
I want to change the list scroll physics but there is no property for that

**Comment by vasilich6107** [comment]
@jayypee nope there is one
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/src/selection_widget.dart#L242

**Comment by vasilich6107** [comment]
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L327

**Comment by jayypee** [comment]
yeah i thought this is the one but when i type SelectionListViewProps i get an error it doesnt exist

**Comment by jayypee** [comment]
nevermind i have it now i updated the package i was on version 1.0.3

**Comment by vasilich6107** [comment]
@jayypee do not forget to close the issue if your problem is solved
