### ISSUE TITLE
search field customization 

### ISSUE THREAD

**Issue by Roxgame95** [salim-lachdhaf/searchable_dropdown#302]
I don't know if this the right place to ask 

I have two questions  :
1- How to separate items with titles  
**Example :** 
![uE56E](https://user-images.githubusercontent.com/51464152/141996136-3c393d52-b5db-4656-a201-1cc300dc961f.png)

2- How to customize the field of search

Thank you

**Comment by vasilich6107** [comment]
1 - you can supply list of totally custom items and disable selecting the separators
2 - look for InputDecoration type props there is two of them one for initial filled, one for search bar inside popup

**Comment by Roxgame95** [comment]
Thank you it worked

**Comment by vasilich6107** [comment]
@Roxgame95 if it worked - don't forget to close the issue
