### ISSUE TITLE
I can't do a search in DropdownSearch<String>

### ISSUE THREAD

**Issue by junndobit** [salim-lachdhaf/searchable_dropdown#303]
I was copying one of the snippets and then it works but it has no search like when I clicked that one, It is just a dropdown, nothing more. It also seems there is no X thing like what I saw in the images.
![image](https://user-images.githubusercontent.com/20215990/142014807-e940a1b7-047c-4491-afc3-6ac7ea3dab7c.png)

**Comment by vasilich6107** [comment]
How could we guess what the issue without code?

**Comment by Roxgame95** [comment]
to have search field you have to add that line to your DropdownSearch

`showSearchBox: true,`

**Comment by salim-lachdhaf** [comment]
the plugin has a ton of parameters that you can try ....

**Comment by junndobit** [comment]
> to have search field you have to add that line to your DropdownSearch
> 
> `showSearchBox: true,`

Thank you. It is now showing.

**Comment by vasilich6107** [comment]
@junndobit before starting to work with plug-in check run `example` to see the functionality
