### ISSUE TITLE
Error: No named parameter with the name 'onChange'

### ISSUE THREAD

**Issue by junndobit** [salim-lachdhaf/searchable_dropdown#306]
I tried doing an onChange in multiSelection but it seems it shows that error instead. Here is my code.
`DropdownSearch<String>.multiSelection(
              key: _multiKey,
              mode: Mode.MENU,
              showSearchBox: true,
              showClearButton: true,
              items: items,
              hint: "Choose one or many services",
              onChange: (selectedItems) {
                selectedServices = selectedItems;
              },
            ),`

**Comment by vasilich6107** [comment]
@junndobit 
Check the `example` for demo projects

**Comment by vasilich6107** [comment]
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/CHANGELOG.md#200

**Comment by junndobit** [comment]
> https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/CHANGELOG.md#200

I see. Thank you for this.
