### ISSUE TITLE
Extra Space below drop down item

### ISSUE THREAD

**Issue by kamjony** [salim-lachdhaf/searchable_dropdown#307]
I have extra blank spaces below my drop down items. I want it to wrap all items without the extra white space. Please check the image for refernce.

I used the following code:
`DropdownSearch<PickPoint>(
                      showSearchBox: true,
                      autoFocusSearchBox: false,
                      searchBoxDecoration: InputDecoration(
                        suffixIcon: Icon(Icons.search),
                      ),
                      mode: Mode.MENU,
                      popupSafeArea: PopupSafeArea(top: false, bottom: true),
                      itemAsString: (PickPoint value) => value.name,
                      items: _con.pickPointData,
                      onChanged: (value) {
                        _con.pickPointValue = value;
                        _con.dropAreaValue=null;
                        _con.dropPointValue=null;
                        _con.getDropArea(false);
                      },
                      selectedItem: _con.pickPointValue,
                      dropdownBuilder: _customPickPointDropDown,
                      emptyBuilder: _errorEmpty,
                    ),`

Is this the default behaviour or am I doing something wrong.
![Screenshot_20211117-183123](https://user-images.githubusercontent.com/34217296/142202298-7e652acf-6328-4a23-b932-c3099bc21d6a.jpg)

**Comment by vasilich6107** [comment]
@kamjony there are a bunch of `builder...` props inside widget in order to override default build behaviour.
Check the list of porops.

**Comment by vasilich6107** [comment]
@kamjony you can also specify `maxHeight` prop to specify desired height

**Comment by salim-lachdhaf** [comment]
you can not wrap all the items with the dropdown, what if you have 10000 items ?!
and you have filter so the height is going to jump based on your search resultats ... !?

you can define a max height as said @vasilich6107 , if you know in advise that you have to pick from 3 or 5 items , in this case you have not even to add `showSearchBox` ...

**Comment by kamjony** [comment]
@vasilich6107 @salim-lachdhaf Thanks guys for your prompt reply. I made it work with maxHeight.

Can you guys help me on how can I add focusNode to the search Textfield in the dropdown? When the keyboard appears, I can not scroll the search textfield to view. SingleChildScrollView as parent widget does not work as well.
