### ISSUE TITLE
Extra space in DropdownSearch

### ISSUE THREAD

**Issue by geerson-pizarro** [salim-lachdhaf/searchable_dropdown#308]
At the time of writing in the search engine I get a white space that does not allow me to see the list that I have
![image](https://user-images.githubusercontent.com/85813700/142230181-4cbf49b0-51f2-461a-b082-069f2f322b18.png)
This is my code
![image](https://user-images.githubusercontent.com/85813700/142230385-5903378b-9d8f-41d2-a1cd-5b7f17c81789.png)

**Comment by salim-lachdhaf** [comment]
i think that you have same item that are empty (e.name is blank)

**Comment by DelfosTI** [comment]
Hello, thanks for the answer, but what happens is that if I have elements, if not at the time of writing in the search field, the list is separated, being below the keyboard
Attached before and after file
![image](https://user-images.githubusercontent.com/85813700/142250568-84867cdf-e540-47f8-8ce4-d55cd944b2a9.png)
and
![image](https://user-images.githubusercontent.com/85813700/142250667-005d66fd-f779-43c2-b74f-e5e7080a12b4.png)

**Comment by salim-lachdhaf** [comment]
it's the same behavior with sample data list ?

**Comment by DelfosTI** [comment]
Yes

**Comment by salim-lachdhaf** [comment]
which version of plugin are you using ?

**Comment by DelfosTI** [comment]
Hello, the version of the plugin that i´m using is dropdown_search: ^2.0.1

**Comment by salim-lachdhaf** [comment]
do not hesitate to use search to find similar issues https://github.com/salim-lachdhaf/searchable_dropdown/issues/235

**Comment by rhernandez-itemsoft** [comment]
I have the same problem. I use version 2.0.1,
How can I reduce that huge padding?

**Comment by vasilich6107** [comment]
@rhernandez-itemsoft  it could be related to your implementation 
Run the example from example folder and you could see how it works
