### ISSUE TITLE
Cannot filter data using onFind

### ISSUE THREAD

**Issue by phuclynk** [salim-lachdhaf/searchable_dropdown#310]
When i change text in searchbox the data weren't change. or i used it in wrong way
![image](https://user-images.githubusercontent.com/32064972/143007966-0597d745-75fa-4a17-a562-59f243507f81.png)

**Comment by vasilich6107** [comment]
@phuclynk run an example project.
There should be a sample for your scenario

**Comment by phuclynk** [comment]
![image](https://user-images.githubusercontent.com/32064972/143008875-17dc6b46-c1ed-4e48-a2a1-267510b68b19.png)
i ran but there was no api calling when i input the text search

**Comment by phuclynk** [comment]
The 'onFind' callback have been call when i open the dropdown but nothing happen when i input the text search . This is the code

**Comment by phuclynk** [comment]
![Uploading image.png…]()

**Comment by salim-lachdhaf** [comment]
use option `isFilteredOnline` to true

**Comment by phuclynk** [comment]
> 

thank you i will try it

**Comment by rcsousa14** [comment]
It still does not work using isFilteredOnline
