### ISSUE TITLE
Opening dropdown programmatically doesn't update the state of the items of the next dropdown correctly

### ISSUE THREAD

**Issue by TiffaaMC** [salim-lachdhaf/searchable_dropdown#311]
Hello,

I have a dropdown "D1" with a list of options, and depending on the selected option, it gives me different options in the dropdown "D2".
D1 programmatically opens D2 whenever an option is selected, like the example provided on this repo.
However, when I select something in D1, the list showing up in D2 will always be 1 selection late.

I've recreated the issue with a small application, the code is at the end.
For example if I select "Brazil" in D1, it should open D2 and give me 1, 2, 3, 4.
Then if I select "Italia" in D1 again, it should open D2 and give me 5, 6, 7, 8.
Finally, if I select "Brazil" again, 1, 2, 3, 4.

But everything is delayed by 1 state when I open it programmatically, so I first get nothing (it doesn't open since `selected = ""`) with the first "Brazil", then I get 1, 2, 3, 4 with "Italia", then I get 5, 6, 7, 8 with "Brazil" again, and so on.

 here is the code:

```dart
import 'package:dropdown_search/dropdown_search.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      theme: ThemeData.dark(),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _openDropDownProgKey = GlobalKey<DropdownSearchState<String>>();
  String _selected = "";

  Future<List<String>> fetchData() {
    return Future.delayed(
        Duration(seconds: 1),
        () =>
            _selected == "Brazil" ? ["1", "2", "3", "4"] : ["5", "6", "7", "8"]);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("DropdownSearch Test")),
      body: Padding(
        padding: const EdgeInsets.all(25),
        child: ListView(
          padding: EdgeInsets.all(4),
          children: <Widget>[
            DropdownSearch<String>(
              mode: Mode.BOTTOM_SHEET,
              items: [
                'Brazil',
                'Italia',
                'Tunisia',
                'Canada',
                'Zraoua',
                'France',
                'Belgique'
              ],
              onChanged: (String? value) {
                setState(() {
                  _selected = value!;
                });
                _openDropDownProgKey.currentState?.openDropDownSearch();
              },
            ),
            Padding(padding: EdgeInsets.all(15)),
            _selected == ""
                ? Container()
                : FutureBuilder(
                    future: fetchData(),
                    builder: (BuildContext context,
                        AsyncSnapshot<List<String>> snapshot) {
                      if (snapshot.hasData) {
                        return DropdownSearch<String>(
                          key: _openDropDownProgKey,
                          items: snapshot.data!,
                        );
                      } else if (snapshot.hasError) {
                        throw snapshot.error!;
                      } else {
                        return Center(child: CircularProgressIndicator());
                      }
                    },
                  ),
          ],
        ),
      ),
    );
  }
}
```

My flutter doctor:
```
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [version 10.0.19042.1348], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)

• No issues found!
```

I'm still a Flutter beginner, so after a lot of head-scratching, I first asked (a few times) about this issue in Flutter's Discord but the only person that answered me told me he didn't see anything wrong in my code, that's why I'm here now. Also, I haven't created a lot of issues so let me know if I forgot anything.

Thanks for this package btw.

**Comment by TiffaaMC** [comment]
Update on this issue:

We found out that even with a delayed future of 30sec, the 2nd dropdown would still open instantly, therefore not waiting for the future to be completed as the GlobalKey is bypassing it, directly calling the open function.

Could you please update the `///open dropdown programmatically` example in the repository (`example/lib/main.dart`, line 487) to work with some data called by a Future and not a `["Yes", "No"]` please?
It would be greatly appreciated!

**Comment by vasilich6107** [comment]
@TiffaaMC 
It seems that issue in your implementation approach
This package is capable of fetching data for dropdown by itself - sees the appropriate example item.
So you need just to fetch your data for second dropdown using selected value from the first one.
No statefull widget needed

**Comment by salim-lachdhaf** [comment]
if your items are `async` then don't use `items,` use `onFind`.

there is no issue.
