### ISSUE TITLE
Change "items" after the ModalBottomSheet is opened

### ISSUE THREAD

**Issue by AliRezaBeitari** [salim-lachdhaf/searchable_dropdown#318]
I need to change the `items` after the ModalBottomSheet is opened using `setState()`, but it doesn't work. Is there any way to do so?

**Comment by salim-lachdhaf** [comment]
your need is not clear, please be more specific , why you want change items after opening bottomSheet

**Comment by AliRezaBeitari** [comment]
> your need is not clear, please be more specific , why you want change items after opening bottomSheet

One of my dropdowns has real-time data. I have a stream listener and whenever new data arrives, I want to update the items shown in the opened modal bottom sheet.

**Comment by vasilich6107** [comment]
@WalterRadduso the issue is that you are using this package wrong.
This package supports downloading the options list from request(see the example project).

what you need is to save selection state of first dropdown and make a request to fetch options using built int functionality of dropdown search

**Comment by WalterRadduso** [comment]
@vasilich6107 you were right!

I have to use `onFind`, this is working well, but I detected a problem.
When I use `onFind` the filter with the input is not working anymore, but with the prop `items` is working good.

Do you know if I need anything else to make it work the filter with the search input??

**Comment by salim-lachdhaf** [comment]
@WalterRadduso you have to use `filterOnline` option to true
