### ISSUE TITLE
How to add styles to the search input.

### ISSUE THREAD

**Issue by WalterRadduso** [salim-lachdhaf/searchable_dropdown#319]
I need to change the styles (border, colors, hintText) of the search input inside of the dialog.
Is there any way to do so?

**Comment by vasilich6107** [comment]
@WalterRadduso did you try to look through the available props?

**Comment by WalterRadduso** [comment]
> @WalterRadduso did you try to look through the available props?

Yes, the README shows a prop called `searchBoxDecoration` but when I try to use it, the code said that it doesn't exists.

![Screen Shot 2021-12-06 at 11 25 08](https://user-images.githubusercontent.com/4683824/144863166-4da77ed2-6432-4905-973c-b244da6ec499.png)

![Screen Shot 2021-12-06 at 11 24 27](https://user-images.githubusercontent.com/4683824/144863052-fc0f6a48-72eb-4b74-b1cc-2d78909f9759.png)

**Comment by vasilich6107** [comment]
> > @WalterRadduso did you try to look through the available props?
> 
> @vasilich6107 Yes, the README shows a prop called `searchBoxDecoration` but when I try to use it, the code said that it doesn't exists.
> 
> ![Screen Shot 2021-12-06 at 11 25 08](https://user-images.githubusercontent.com/4683824/144863166-4da77ed2-6432-4905-973c-b244da6ec499.png)
> 
> ![Screen Shot 2021-12-06 at 11 24 27](https://user-images.githubusercontent.com/4683824/144863052-fc0f6a48-72eb-4b74-b1cc-2d78909f9759.png)

Check in the source code of the app for actual props. The documentation could be outdated

**Comment by vasilich6107** [comment]
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L60

**Comment by WalterRadduso** [comment]
> Check in the source code of the app for actual props. The documentation could be outdated

I did, the only one similar is `dropdownSearchDecoration` but is used to decorate the dropdown input, not the input inside of the dialog with the items.

**Comment by vasilich6107** [comment]
Awesome!
