### ISSUE TITLE
Search bar works in simulator / running in debug on a physical device but not in built app

### ISSUE THREAD

**Issue by phucgotecq** [salim-lachdhaf/searchable_dropdown#320]
The search bar/function of the Searchable.Dialog works fine when running my flutter app in simulator or on a physical device in debug mode (i.e. connected by a cable). However, when I distribute the app and open it using Firebase App Distribution, the search bar/function no longer works.

![image](https://user-images.githubusercontent.com/88519540/145518059-a3b572b5-0df0-42b6-bea5-4b86c96455a6.png)

**Comment by khaithumc** [comment]
.

**Comment by khaithumc** [comment]
same issue

**Comment by vasilich6107** [comment]
@khaithumc @phucgotecq 
This is not likely to be an issue of the package.
I have it in my own app and it works fine in debug and in prod modes

You have to add some error tracking to your app and try to figure out at least the error which happens.
Otherwise it is almost impossible to guess what's goes wrong on your side.

**Comment by phucgotecq** [comment]
This is the result when i use the simulator or real device. ( Debug mode )
![simulator_screenshot_73959A93-4473-441A-A078-2A181577C615](https://user-images.githubusercontent.com/88519540/145531916-a7a46f3b-71e2-4f69-a558-51b40e6e57a5.png)

And this is the result when i use the build in release mode
![5785b762f2c5399b60d4](https://user-images.githubusercontent.com/88519540/145532118-00868ce6-9681-49b2-b2dc-e2c3958de60c.jpeg)

I cannot track some error currently but i will try

**Comment by vasilich6107** [comment]
At least the difference between screenshots is capital letter in search term

**Comment by phucgotecq** [comment]
I think it's not the problem 🤣  I try it all and it works on debug mode

**Comment by phucgotecq** [comment]
![image](https://user-images.githubusercontent.com/88519540/145543674-44eba22b-5060-4d9b-8d03-a0699ae9d132.png)
![image](https://user-images.githubusercontent.com/88519540/145543716-6ffe358d-852e-4c23-b693-a592951aac47.png)

**Comment by phucgotecq** [comment]
![1dab0427a88163df3a90](https://user-images.githubusercontent.com/88519540/145544063-731a973a-85f8-4030-b642-db2e751572de.jpg)
I used Sentry for tracking error but nothing was recorded lol

**Comment by phucgotecq** [comment]
any suggestion 🤔

**Comment by PavelRusanov18** [comment]
is any internet connections available? Maybe for this reason Sentry also does not work?

**Comment by salim-lachdhaf** [comment]
from your code i have some advise:
1- prevent using dynamic for your `dropdownSearch` and in your devs in general if it's not a need ...
2- i see not a `compareFn` , and your dynamic it seems not to be a string , so you need a `compareFn`.

try these advise and let us know if you fixed your problem

**Comment by phucgotecq** [comment]
> is any internet connections available? Maybe for this reason Sentry also does not work?

of cource, internet is always available 👍

**Comment by phucgotecq** [comment]
> from your code i have some advise: 1- prevent using dynamic for your `dropdownSearch` and in your devs in general if it's not a need ... 2- i see not a `compareFn` , and your dynamic it seems not to be a string , so you need a `compareFn`.
> 
> try these advise and let us know if you fixed your problem

I haven't use dynamic anymore but it doesn't help, and i don't think compareFn will work in this issue but i will try it and feedback later

**Comment by salim-lachdhaf** [comment]
any news ?

**Comment by ingmferrer** [comment]
bump this

**Comment by phucgotecq** [comment]
> 

oh sorry i forgot to feedback about the issue, it work correctly thanks.
