### ISSUE TITLE
How can I add load more functionality ?

### ISSUE THREAD

**Issue by allaeddine** [salim-lachdhaf/searchable_dropdown#321]
Hello, I have a big list of users and would like to use this component to search and pick a user. How would I implement "load more" functionality when users scroll to the bottom of the list. I tried to use scrollController but couldn't update the popup list while it's displayed.

**Comment by vasilich6107** [comment]
@allaeddine do not hesitate to search for prev issues
https://github.com/salim-lachdhaf/searchable_dropdown/issues/280

**Comment by allaeddine** [comment]
Got it, Thank you ! 👍
