### ISSUE TITLE
Cannot filter data using onFind, can be able to reproduce

### ISSUE THREAD

**Issue by joo** [salim-lachdhaf/searchable_dropdown#322]
ver 1.0.0 and befor:  emulator open(or close) the Software Keyboard, can filter data. real mobile device can filter data.
ver 1.0.3 and later:  emulator open the Software Keyboard, cannot filter data. emulator close(disable) the Software Keyboard, can filter data. real mobile device cannot filter data.

**Comment by joo** [comment]
if you test with emulator, open the Software Keyboard, input letter cannot filter data.

**Comment by vasilich6107** [comment]
@joo 
Use v2.0.0

**Comment by salim-lachdhaf** [comment]
use last version.
