### ISSUE TITLE
Style issue in flutter web project

### ISSUE THREAD

**Issue by bambinoua** [salim-lachdhaf/searchable_dropdown#323]
It looks like there is an issue under flutter web. All TextFormFields on my form has a blue border when the field is focused by mouse or **keyboard**. When I press the `Tab` key on the `TextFormField` which is before `DropdownSearch` (i.e. I expect that next focused field will be the `DropdownSearch) then rounding focused border does not change the color to blue. So I don't know if it is focused.
But if I point the `DropdownSearch` widget by mouse the focused border is colorized as expected.

I tried to use `Theme` widget to override the `focusBorder`
```
Theme(
  data: Theme.of(context).copyWith(
    hoverColor: Colors.transparent,
    focusColor: Colors.transparent,
    inputDecorationTheme: Theme.of(context).inputDecorationTheme.copyWith(
      focusColor: Colors.blue,
      focusedBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Colors.blue),
      ),
    )
  ),
  child: DropdownSearch(
    dropdownSearchDecoration: InputDecoration(
      labelText: 'Country',
      hintText: 'Country',
    ),
  ),
)
```
but it does not helps.

**Comment by salim-lachdhaf** [comment]
did you runned plugin example and you get the same issue ?

**Comment by bambinoua** [comment]
Yes. Just run the example in web and try press `Tab` key. No blue focus border you see. But when you click on the dropdown the border become blue.

**Comment by bambinoua** [comment]
Why do you close the issue if it is not fixed?
