### ISSUE TITLE
Field don't keep selectedItem Value when I press the "Process" button to call API 

### ISSUE THREAD

**Issue by ghulamsabir5353** [salim-lachdhaf/searchable_dropdown#326]
Hey, 
I integrate API on the "Submit" Button and I want the field to show the selected item value but when I pressed the button and call API. Field automatically reset.

**Comment by vasilich6107** [comment]
@ghulamsabir5353 it does not sound like a package bug
If you will add minimal reproduction sample - we could possibly help you

**Comment by ghulamsabir5353** [comment]
@vasilich6107 Please check this once 

  
  return Container(
                      margin: EdgeInsets.symmetric(
                        horizontal: sizeConfig.width(.04),
                        vertical: sizeConfig.height(.02),
                      ),
                      child: DropdownSearch<String>(
                        mode: Mode.BOTTOM_SHEET,
                        popupBackgroundColor: Colors.white,
                        items: value.groupList,
                        itemAsString: (String? u) => u ?? '',
                        dropdownSearchDecoration:
                            InputDecoration(labelText: 'Group'),
                        showSearchBox: true,
                        onChanged: (newValue) =>
                            value.selectedGroup = newValue!,
                        selectedItem: 'Select',
                      ),
                    );

**Comment by vasilich6107** [comment]
It is not a reproduction sample.
Could this code demo the behavior which you describe if I copy it in my project - no.
This is just a widget wrapped into container.
