### ISSUE TITLE
Hi guys. Menu doesn't move when keyboard shows up. Can you fix it?

### ISSUE THREAD

**Issue by 10urb** [salim-lachdhaf/searchable_dropdown#328]
Here is the snapshot;

![drop1](https://user-images.githubusercontent.com/77685360/147165491-662b80fb-2540-434e-843d-7138c50e8315.png)

![drop2](https://user-images.githubusercontent.com/77685360/147165507-0eab5694-54ab-4c02-ac4e-8467e232ef7d.png)

**Comment by salim-lachdhaf** [comment]
use dialog mode

**Comment by vasilich6107** [comment]
@10urb 
Check the comment
Do not hesitate to search among the previous issues

https://github.com/salim-lachdhaf/searchable_dropdown/issues/150#issuecomment-840082887

**Comment by salim-lachdhaf** [comment]
https://github.com/salim-lachdhaf/searchable_dropdown/issues/328
