### ISSUE TITLE
Possible to have the searching text as a dropdown option?

### ISSUE THREAD

**Issue by fenchai23** [salim-lachdhaf/searchable_dropdown#33]
I would like to add the searching text as an option to select in the menu.

I have been trying to find a way to get the text I am writing so I could change the menu list but I haven't been able to find out how.

**Comment by salim-lachdhaf** [comment]
Do you mean, select whatever you write even it did not exist in the dropdown list ?

**Comment by fenchai23** [comment]
> Do you mean, select whatever you write even it did not exist in the dropdown list ?

yes, just to show as first option

**Comment by salim-lachdhaf** [comment]
Sadly exactly as uou want NO, this is not even a correct behavior of autocomplete ..., BUT i have a solution to you that solve your problem in correct way, you can customize `emptyBuilder` (the widget to show when no item is found for your filter) and add a button with a text or an add icon to tell user to accept his query as selected item ...

**Comment by fenchai23** [comment]
> 
> 
> Sadly exactly as uou want NO, this is not even a correct behavior of autocomplete ..., BUT i have a solution to you that solve your problem in correct way, you can customize `emptyBuilder` (the widget to show when no item is found for your filter) and add a button with a text or an add icon to tell user to accept his query as selected item ...

do you have an example of the emptybuilder? I also think this would be a good solution
