### ISSUE TITLE
On Screen Keyboard keeps popping-up again and agin when pressing 'Back' button on Bottom Sheet's SearchBox (when autoFocus is true)

### ISSUE THREAD

**Issue by mrishabh72** [salim-lachdhaf/searchable_dropdown#331]
**My Virtual Device : Pixel XL API 29**

**Steps To Reproduce:**
1) Use the code as given below these steps
2) Tap on DropdownSearch. Bottom Sheet will pop up, with search field.
3) Tap on search Field to perform search.
4) Now when we press back button, keyboard goes down then comes up again which is a buggy behavior.

**Widget Code:**
  DropdownSearch<int>(
                showSearchBox: true,
                searchFieldProps: TextFieldProps(autofocus: true),
                dropdownSearchDecoration: const InputDecoration(
                  label: const Text("Country"),
                ),
                mode: Mode.BOTTOM_SHEET,
                onFind: (keyword) async {
                  if (keyword == null) return state.countryList.keys.toList();
                  return state.countryList.entries
                      .where((element) => element.value.startsWith(keyword))
                      .map((e) => e.key)
                      .toList();
                },
                itemAsString: (id) => state.countryList[id]!,
                selectedItem: state.country,
              )

where, state.countryList is a Map<int,String> containing key as Id and Value as countryName.

**Comment by salim-lachdhaf** [comment]
fixed in the last version.
