### ISSUE TITLE
How can i clear sub dropdown means , there are two dropdown country and states , states dropdown should be clear regarding when country selection

### ISSUE THREAD

**Issue by rahulraj7626** [salim-lachdhaf/searchable_dropdown#332]

**Comment by mrishabh72** [comment]
Using onFind & onChanged can help you. 
1) add onChanged to countries dropdown :
 void onCountrySelect(int? countryId) {
    if (countryId == null) return;
    ApiRequest.getMasterStates(country!).then((states) {
      stateList = {0: "Select your state", ...states};
      notifyListeners();
    });
  }

2) then add onFind to state dropdown :
void onFindState(keyword) async {
                  return state.stateList.keys.toList();
                },

**Comment by salim-lachdhaf** [comment]
check examples page.
you can use GlobalKey and you can change the selected value dynamically and a lot other options ...

re check examples page, there an example of use .

**Comment by shimafanissa** [comment]
> check examples page. you can use GlobalKey and you can change the selected value dynamically and a lot other options ...
> 
> re check examples page, there an example of use .

where's the example?
