### ISSUE TITLE
How can i detect if the DropdownSearch is Focused

### ISSUE THREAD

**Issue by TariqHattab** [salim-lachdhaf/searchable_dropdown#333]
Hello, I want to change the dropdown button on focus or when the popup items are visible how can I detect this, Thank you very much

**Comment by vasilich6107** [comment]
There is a focusNode param
But it is bound to textfield
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/src/selection_widget.dart#L562

**Comment by TariqHattab** [comment]
Thank you very much for the fast response, I used positionCallback function to detect the start of focus and  onPopupDismissed function to detect the focus end, so this solves this issue for now, I have another problem I will open a separate issue for. Thanks

**Comment by vasilich6107** [comment]
@TariqHattab very smart workaround with `positionCallback`
