### ISSUE TITLE
Selected item not visible when a async function is called inside onChanged 

### ISSUE THREAD

**Issue by Debrup1201** [salim-lachdhaf/searchable_dropdown#334]
![image](https://user-images.githubusercontent.com/40709692/147575063-4e69af45-23d0-4bff-8fc4-cc58c96313b5.png)

**Selected item is not visible in Communty**
### Code - 

                          DropdownSearch<Community>(
                          mode: Mode.BOTTOM_SHEET,
                          items: communityList,
                          itemAsString: (Community? item) => item!.name,
                          dropdownSearchDecoration: const InputDecoration(
                            labelText: "Community",
                          ),
                          onChanged: (value) {
                            _userData!['community'] = value!.id;
                            fetchCommunityHomes(_userData!['community']);
                            _userData!['home'] = null;
                          },
                          selectedItem: null,
                          showSearchBox: true,
                          showAsSuffixIcons: true,
                          searchFieldProps: TextFieldProps(
                            decoration: const InputDecoration(
                              border: OutlineInputBorder(),
                              labelText: "Search a community",
                            ),
                          ),
                          popupTitle: Container(
                            height: 50,
                            decoration: BoxDecoration(
                              color: Theme.of(context).primaryColorDark,
                              borderRadius: const BorderRadius.only(
                                topLeft: Radius.circular(12),
                                topRight: Radius.circular(12),
                              ),
                            ),
                            child: const Center(
                              child: Text(
                                'Communities',
                                style: TextStyle(
                                  fontSize: 24,
                                  fontWeight: FontWeight.bold,
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ),
                          popupShape: const RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(12),
                              topRight: Radius.circular(12),
                            ),
                          ),
                        ),

**Comment by mrishabh72** [comment]
I think 'selectedItem' field shouldn't be null. Assign a variable to 'selectedItem', then update that item in 'onChanged'

**Comment by Debrup1201** [comment]
Thanks that worked
