### ISSUE TITLE
Scrolling my screen up when menu close to bottom?

### ISSUE THREAD

**Issue by TariqHattab** [salim-lachdhaf/searchable_dropdown#336]
Hello,  I am using  Menu Mode and have a problem when dropdown search is close to the bottom of the screen, the menu when it appears covers the dropdownserach field, my question is how to scroll my screen when the DropDown Search menu is close to the bottom of the screen? Thank you very much,

**Comment by salim-lachdhaf** [comment]
check for the documentation of `CustomScrollView` widget
