### ISSUE TITLE
[Request] text ellipsis or seperate short title for selected item and long title in search panel

### ISSUE THREAD

**Issue by patachi** [salim-lachdhaf/searchable_dropdown#337]
is there any option to set `overflow: TextOverflow.ellipsis` for the selected item?

it would be great if we had two types of `itemAsString` 
a short one for display selected item
and a long one in the search panel
it's useful when choosing the country for phone numbers or states that just need a small code to be shown and search by long country name/native name.

**Comment by salim-lachdhaf** [comment]
you can use `dropdownBuilder` and `popupItemBuilder`
