### ISSUE TITLE
Clear multiselected values

### ISSUE THREAD

**Issue by ETBMina** [salim-lachdhaf/searchable_dropdown#338]
I have two dropdowns, the second one depends on the first, The problem is that I cannot clear the second one selection programmatically when changing the first dropdown, I tried to empty the list of selectedItems and rebuild, but still the old values are selected.

**Comment by salim-lachdhaf** [comment]
you do not need to rebuild ....
you can do that using globalKey ...
check examples , there is an example that could help you in your case.
