### ISSUE TITLE
onChanged for searchBox string

### ISSUE THREAD

**Issue by KillTheProcess23** [salim-lachdhaf/searchable_dropdown#339]
Hi everyone!

Is there a way to call an "onChanged" when typing into the searchbar? I want to implement this cause i need to call some api.

**Comment by bambinoua** [comment]
Use `onFind` callback

**Comment by KillTheProcess23** [comment]
> Use `onFind` callback

Can you show me an example on a basic usage?

**Comment by salim-lachdhaf** [comment]
check example page for more examples

**Comment by socramm9** [comment]
@salim-lachdhaf Could this be a bug? Because `onFind` is only Triggering once for me and is ignored when typing into the searchbar. 

To run my query with onFind i have to 

1. open the Dropdown 
2. type into the Searchbar
3. Close Dropdown 
4. And the reopen the Dropdown

**Comment by socramm9** [comment]
My code:

```
class FormBuilderDropdownSearch extends StatelessWidget {
  const FormBuilderDropdownSearch({
    Key? key,
    required this.name,
    required this.onFind,
    this.validator,
    this.decoration = const InputDecoration(),
  }) : super(key: key);
  final String name;
  final InputDecoration decoration;
  final Future<List<dynamic>> Function(String?) onFind;
  final String? Function(Object?)? validator;

  @override
  Widget build(BuildContext context) {
    return FormBuilderField(
      name: name,
      validator: validator,
      builder: (field) {
        return DropdownSearch<dynamic>(
          mode: Mode.DIALOG,
          onFind: (search) async {
            print("search: $search");             <====================
            return onFind(search);
          },
          showSearchBox: true,
          searchFieldProps: TextFieldProps(
            decoration: const InputDecoration(
              prefixIcon: Icon(Icons.search),
            ),
          ),
          dropdownSearchDecoration: decoration.copyWith(
            errorText: field.errorText,
            contentPadding: EdgeInsets.zero,
          ),
          itemAsString: (item) => item.toString(),
          onChanged: (value) {
            field.didChange(value);
          },
        );
      },
    );
  }
}
```

This is what I get when following the 4 steps on my previous comment.
<img width="262" alt="Bildschirmfoto 2022-01-10 um 14 39 06" src="https://user-images.githubusercontent.com/52098754/148775470-a79a795b-ec34-41dc-9182-5d07099b1534.png">


Correct would be to get this Output:

flutter: search:
```
flutter: search: t
flutter: search: te
flutter: search: tes
flutter: search: test
```

**Comment by salim-lachdhaf** [comment]
use `filterOnline` to false

**Comment by socramm9** [comment]
> use `filterOnline` option to false

I had to set `isFilteredOnline` to true. 
Thanks

**Comment by KillTheProcess23** [comment]
Hi, i figured it out but when i use Future<List<UserModel>> the override of the toString method doesnt work and i get the error 

"The return type 'Future<List<UserModel>>' isn't a 'Future<List<String>>', as required by the closure's context."

This force me to use  'Future<List<String>>' for the "getData" method.

**Comment by Sami-63** [comment]
How to do the same thing now? onFind is not available now.
