### ISSUE TITLE
Mode : "Menu"  Covered by Keyboard ?

### ISSUE THREAD

**Issue by leanhro2812** [salim-lachdhaf/searchable_dropdown#34]
In BOTTOM_SHEET mode + DIALOG mode, when the keyboard is turned on, it will automatically push the list up
But in "Menu" mode the keyboard is almost completely covered

**Comment by salim-lachdhaf** [comment]
Yes the menu supposed to have fixed position under parent widget only when there is no place from the begining. For the best practice use dialog or bottomSheet for long lists.

**Comment by leanhro2812** [comment]
"For the best practice use dialog or bottomSheet for long lists."
My list contains only 4 items. But at the bottom of the page.
When you click on the parent it will move up.
But for keyboard when clicking on input search it will mask it

**Comment by salim-lachdhaf** [comment]
yes, when i said not use menu for short list , this will made the searchBox non usable !
