### ISSUE TITLE
Add optional style parameter for selected item(s)

### ISSUE THREAD

**Issue by bambinoua** [salim-lachdhaf/searchable_dropdown#341]
Now the style for selected item is hardcoded.
 * for single selection
https://github.com/salim-lachdhaf/searchable_dropdown/blob/3b51853089415554ffb80f7515d305c069db8fbe/lib/dropdown_search.dart#L515
 * for multiple selection (row 491)
https://github.com/salim-lachdhaf/searchable_dropdown/blob/3b51853089415554ffb80f7515d305c069db8fbe/lib/dropdown_search.dart#L491

It would be good to customize those styles. Now we have some GUI inconsistencies.

**Comment by salim-lachdhaf** [comment]
you can use `dropdownBuilder` and customize the selected item as you want.
