### ISSUE TITLE
Item counts less than four

### ISSUE THREAD

**Issue by nilpkthmsk** [salim-lachdhaf/searchable_dropdown#344]
Even if the items count is less than four, it shows 4 line of the dropdown.
Any work around ?

<img width="376" alt="Screen Shot 2022-01-12 at 1 28 41" src="https://user-images.githubusercontent.com/35032711/148982357-55233cc4-0adc-43e1-b69c-57545bccf0d2.png">

Thank you in advance.

**Comment by vasilich6107** [comment]
@nilpkthmsk check minHeight property
