### ISSUE TITLE
Scrolling down does not work in the desktop version

### ISSUE THREAD

**Issue by Shams-Mahmoud** [salim-lachdhaf/searchable_dropdown#346]
Scrolling down does not work when pressing and dragging the scrollbar down in the desktop version

**Comment by Shams-Mahmoud** [comment]
@salim-lachdhaf

**Comment by salim-lachdhaf** [comment]
please past an example

**Comment by salim-lachdhaf** [comment]
no reply

**Comment by MalikSamiAwan** [comment]
is there any solution for that yet?
