### ISSUE TITLE
Clear the text programmatically?

### ISSUE THREAD

**Issue by lkc33** [salim-lachdhaf/searchable_dropdown#349]
How to clear the text programmatically?
i tried to clear via texteditingcontroller, texteditingcontroller.clear(), it did clear the text but not the displaying text.
Anyone can help?

Thanks in advance

**Comment by salim-lachdhaf** [comment]
not clear

**Comment by lkc33** [comment]
I have created a few dropdowns and textfields and want to empty(clear the search bars) all the texts in the dropdown/textfield at once via a button.

**Comment by salim-lachdhaf** [comment]
use `GlobalKey` .
check examples page

**Comment by rehamalraee24** [comment]
@salim-lachdhaf Keys not wokring I/flutter (25439): LocalNotifier was disposed.

**Comment by rehamalraee24** [comment]
@lkc33  Did you implement it?

**Comment by salim-lachdhaf** [comment]
follow this example:
https://github.com/salim-lachdhaf/searchable_dropdown/blob/3b51853089415554ffb80f7515d305c069db8fbe/example/lib/main.dart#L29

**Comment by rehamalraee24** [comment]
This is not working, locale notifier called after dispose, set state called after dispose

**Comment by salim-lachdhaf** [comment]
if you want to manage text in searchTextField use this
https://github.com/salim-lachdhaf/searchable_dropdown/blob/3b51853089415554ffb80f7515d305c069db8fbe/example/lib/main.dart#L31

and if you want control your dropdownSearch programmatically use the previous solution.

**Comment by lkc33** [comment]
Thank you very much.
It helps a lot
