### ISSUE TITLE
Bug: Inactive InputConnection

### ISSUE THREAD

**Issue by dalton5** [salim-lachdhaf/searchable_dropdown#351]
Hi,

When I open the dropdown I have an error in my debug console:

W/IInputConnectionWrapper(32060): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(32060): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(32060): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(32060): beginBatchEdit on inactive InputConnection

Then the search is not working.

How can I fix this?

Thanks,

**Comment by salim-lachdhaf** [comment]
past an example of your code

**Comment by vasilich6107** [comment]
@dalton5 it is not an error it is warning `W` at the beginning of the message

You can also dig here
https://github.com/flutter/flutter/issues/11321
