### ISSUE TITLE
[WEB]: Switch focus on DropdownSearch using Tab does not colorize the focus border as it should

### ISSUE THREAD

**Issue by bambinoua** [salim-lachdhaf/searchable_dropdown#355]
It looks like there is an issue under flutter web. All `TextFormField`s widgets on form _has a blue border when the field is focused_ by **mouse** or **keyboard**. When I press the `Tab` key on the `TextFormField` which is before `DropdownSearch` (i.e. I expect that next focused field will be the `DropdownSearch) then rounding focused border does not change the color to blue. So I don't know if it is focused.
But if I point the `DropdownSearch` widget by mouse the focused border is colorized as expected.

I tried to use `Theme` widget to override the `focusBorder`
```
Theme(
  data: Theme.of(context).copyWith(
    hoverColor: Colors.transparent,
    focusColor: Colors.transparent,
    inputDecorationTheme: Theme.of(context).inputDecorationTheme.copyWith(
      focusColor: Colors.blue,
      focusedBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Colors.blue),
      ),
    )
  ),
  child: DropdownSearch(
    dropdownSearchDecoration: InputDecoration(
      labelText: 'Country',
      hintText: 'Country',
    ),
  ),
)
```
but it does not helps.

P.S. If bug was not fixed why it is closed?

**Comment by Ch4v3-98** [comment]
Someone said that they found a workaround by using `positionCallback`. Don't know extactly how tho. 

Still, an easier and cleaner way to do this would be really nice IMO.

**Comment by bambinoua** [comment]
I investigated your code and I noticed that you use `Text` widget to display the selection widget but I think you should use `TextFormField` (with `readOnly = true`) which allows to handle focus in a regular way.

**Comment by salim-lachdhaf** [comment]
it's not a bug, because it's not an TEXT FIELD, so the border will be colored (as selected) only when the popup is open.

otherwise, with tab you can click in space button of your keyboard to click (open) the dropdown.

by using tab you are hovering the dropdown not clicking it. so you can try using `HoverColor` instead.
by the way , i'm using `FormField` https://github.com/salim-lachdhaf/searchable_dropdown/blob/81f3ec712d0b05582b9c75046695afe2152a8833/lib/dropdown_search.dart#L543

**Comment by scognito** [comment]
I think that the widget should highlight when it is focused with keyboard.
Every widget has a visual sign when it is selected, we are using navigation with keyboard and the user doesn't understand when the widget is selected
