### ISSUE TITLE
Can not clear the selected data after perform on changed function

### ISSUE THREAD

**Issue by rehamalraee24** [salim-lachdhaf/searchable_dropdown#356]
How can I reset the data after onchange? when I tried the global keys I got local notifier after  dispose and such exceptions that hang the app

**Comment by rehamalraee24** [comment]
I/flutter ( 3073): LocalNotifier was disposed.

**Comment by salim-lachdhaf** [comment]
you can use GlobalKey as you mentionned it's the best solution. take a look at examples page.
make sure that you are implrmenting it well.

you have to past an example of your code to understand your problem.

please stop posting question as bugs it's not stackoverFlow.
