### ISSUE TITLE
Dropdown Search for Mode.BOTTOM_SHEET Not Working

### ISSUE THREAD

**Issue by edsumpena** [salim-lachdhaf/searchable_dropdown#357]
I'm trying to use a search box for BOTTOM_SHEET mode for DropdownSearch, but it doesn't seem to be working. After typing in the search box, there seems to be no response by the search filter (the full dropdown list is still displayed).

Here is the code that I am using:
````
DropdownSearch<String>(
            mode: Mode.BOTTOM_SHEET,
            items: [ "Item 1", "Item 2", "Item 3", "Item 4" ],
            showSelectedItems: true,
            onChanged: (String? item){
              setState(() {
                // Perform some action
              });
            },
            showSearchBox: true,
            searchDelay: const Duration(),
            selectedItem: "Item 1",
          ),
````

Is there anything that I am doing wrong? Any ideas on how I can fix this issue? Thank you in advance.

**Comment by salim-lachdhaf** [comment]
correct or remove `searchDelay`.

**Comment by edsumpena** [comment]
The search still doesn't work upon removing `searchDelay` per your suggestion. It works on .MENU and .DIALOG modes, just not for BOTTOM_SHEET.
