### ISSUE TITLE
Suggestions dropdown height is not adjusting as per suggestions content

### ISSUE THREAD

**Issue by rohit-suthar** [salim-lachdhaf/searchable_dropdown#361]
Suggestions dropdown height is fixed and height is not shrinking even if we get only one or two suggestion items as a result after search.

![image](https://user-images.githubusercontent.com/88317149/152090428-024d22b7-d945-4cd0-b62b-5f7e705c7fb5.png)

**Comment by salim-lachdhaf** [comment]
you can try `maxHeight`. the height is not dynamic
