### ISSUE TITLE
How to adjust the default height of DropdownSearch to atch with other widgets

### ISSUE THREAD

**Issue by ishaantantra** [salim-lachdhaf/searchable_dropdown#362]
By default the height of DropdownSearch is greater than the default height of other form-fields. How do I change the height of DropdownSearch to match he default height of other form-fields. 

![DropDown Serach](https://user-images.githubusercontent.com/40491518/152093653-7b6b5e7b-5ca6-4d5a-8e0d-4a2db69ec68d.PNG)

**Comment by salim-lachdhaf** [comment]
you can use `showAsSuffixIcons` or you can simply override it all, by using `dropdownBuilder`

**Comment by salim-lachdhaf** [comment]
@KiddoV you limit the the height as you want like :

```
return DropdownSearch<Person>.multiSelection(
    [...],
    dropdownBuilder: (ctx, slItems) {
         const SizedBox(
               height: XX,
               child: [...your item],
        )
    }
);
```

**Comment by salim-lachdhaf** [comment]
Thanks for these informations
