### ISSUE TITLE
AutovalidateMode.onUserInteraction but form autovalidate

### ISSUE THREAD

**Issue by trunghq17520184** [salim-lachdhaf/searchable_dropdown#368]
DropdownSearch<String>.multiSelection(
                key: _multiKey,
                showSearchBox: true,
                autoValidateMode: AutovalidateMode.onUserInteraction,
                validator: (List<String>? v) {
                  return v == null || v.isEmpty ? "required field" : null;
                },
                dropdownBuilder: (context, selectedItems) {
                  Widget item(String i) => Container(
                        padding: EdgeInsets.only(
                            left: 6, bottom: 3, top: 3, right: 0),
                        margin: EdgeInsets.symmetric(horizontal: 2),
                        decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(10),
                            color: Theme.of(context).primaryColorLight),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Text(
                              i,
                              textAlign: TextAlign.center,
                              style: Theme.of(context).textTheme.subtitle2,
                            ),
                            MaterialButton(
                              height: 20,
                              shape: const CircleBorder(),
                              focusColor: Colors.red[200],
                              hoverColor: Colors.red[200],
                              padding: EdgeInsets.all(0),
                              minWidth: 34,
                              onPressed: () {
                                _multiKey.currentState?.removeItem(i);
                              },
                              child: Icon(
                                Icons.close_outlined,
                                size: 20,
                              ),
                            )
                          ],
                        ),
                      );
                  return SizedBox(
                    height: 30,
                    child: ListView(
                      scrollDirection: Axis.horizontal,
                      children: selectedItems.map((e) => item(e)).toList(),
                    ),
                  );
                },
                popupCustomMultiSelectionWidget: (context, list) {
                  return Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      Padding(
                        padding: EdgeInsets.all(8),
                        child: OutlinedButton(
                          onPressed: () {
                            // How should I unselect all items in the list?
                            _multiKey.currentState?.closeDropDownSearch();
                          },
                          child: const Text('Cancel'),
                        ),
                      ),
                      Padding(
                        padding: EdgeInsets.all(8),
                        child: OutlinedButton(
                          onPressed: () {
                            // How should I select all items in the list?
                            _multiKey.currentState?.popupSelectAllItems();
                          },
                          child: const Text('All'),
                        ),
                      ),
                      Padding(
                        padding: EdgeInsets.all(8),
                        child: OutlinedButton(
                          onPressed: () {
                            // How should I unselect all items in the list?
                            _multiKey.currentState?.popupDeselectAllItems();
                          },
                          child: const Text('None'),
                        ),
                      ),
                    ],
                  );
                },
                dropdownSearchDecoration: InputDecoration(
                  hintText: "Select a country",
                  labelText: "Menu mode multiSelection*",
                  contentPadding: EdgeInsets.fromLTRB(12, 12, 0, 0),
                  border: OutlineInputBorder(),
                ),
                mode: Mode.DIALOG,
                showSelectedItems: true,
                items: ["Brazil", "Italia (Disabled)", "Tunisia", 'Canada'],
                showClearButton: true,
                onChanged: print,
                popupSelectionWidget: (cnt, String item, bool isSelected) {
                  return isSelected
                      ? Icon(
                          Icons.check_circle,
                          color: Colors.green[500],
                        )
                      : Container();
                },
                popupItemDisabled: (String s) => s.startsWith('I'),
                clearButtonSplashRadius: 20,
              ),

<img width="463" alt="Screen Shot 2022-02-23 at 16 17 42" src="https://user-images.githubusercontent.com/45090989/155290617-9f86dad2-a688-4cff-9cd2-033c3c02eace.png">

Hi team, i use `autoValidateMode: AutovalidateMode.onUserInteraction,` but the form is always validate. Can you help me?

**Comment by Bikram-Shrestha** [comment]
I have the same issue.  And looks like this is close @salim-lachdhaf  @trunghq17520184. Can you help me find the soln
