### ISSUE TITLE
Popup or keyboard does not open when textfield is inside dropdownbuilder

### ISSUE THREAD

**Issue by ajaystefins** [salim-lachdhaf/searchable_dropdown#369]
I have the textfield inside the dropdown builder and set 'showSearchBox' to false(like in #167 ). 
When I tap on the textfield, popup doesn't open and the keyboard opens and closes in a second.

> DropdownSearch<Business>.multiSelection(

              mode: Mode.MENU,
              items: _controller.businesses,
              popupBackgroundColor: AppColors.greyVariant2,
              dialogMaxWidth: MediaQuery.of(context).size.width * 0.60,
              onChanged: print,
              // selectedItem: "Brazil",
              dropdownBuilder: (context, value) {
                return Row(
                  children: [
                    Icon(Icons.search, color: AppColors.textGrey),
                    Expanded(child: TextFormField(
                      onChanged: (value) {
                        _controller.searchBoxFocus.requestFocus();
                      },
                    )),
                  ],
                );
              },
              maxHeight: 290.sh,
              popupItemBuilder: (context, value, isSelected) {
                return dropdownItem(value, isSelected);
              },
              popupSelectionWidget: (context, value, bool) {
                return Container();
              },
              dropdownButtonBuilder: (context) {
                return _controller.searchTextController.text != ""
                    ? Padding(
                        padding: EdgeInsets.only(right: 10.sw),
                        child: InkWell(
                            onTap: () {
                              _controller.searchTextController.clear();
                            },
                            child: Icon(Icons.close)),
                      )
                    : Container();
              },
              popupShape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.only(
                bottomLeft: Radius.circular(15),
                bottomRight: Radius.circular(15),
              )),
              popupValidationMultiSelectionWidget: (context, items) {
                // return Container(color: Colors.blue);
                return Align(
                  alignment: Alignment.center,
                  child: Container(
                      width: 311.sw,
                      height: 56.sh,
                      padding: EdgeInsets.only(bottom: 20.sh, right: 16.sh),
                      child: ElevatedButton(
                        onPressed: () {},
                        child: Text(
                          'Follow',
                          style: TextStyle(
                              fontWeight: FontWeight.bold, fontSize: 17.sf),
                        ),
                      )),
                );
              },
              clearButton: Icon(Icons.close, color: Colors.blue),
              showClearButton: true, focusNode: _controller.searchBoxFocus,
              searchFieldProps: TextFieldProps(
                controller: _controller.searchTextController,
              ),
            ),

**Comment by salim-lachdhaf** [comment]
try to remove focusNode
