### ISSUE TITLE
Is there a way to trigger show / hide dropdowns instead of manually clicking?

### ISSUE THREAD

**Issue by leanhro2812** [salim-lachdhaf/searchable_dropdown#37]
I want when I go to the page the dropdown will automatically pop up instead of being actively touched by the user.

**Comment by salim-lachdhaf** [comment]
No there is not. The plugin is not meant to behave like this

**Comment by leanhro2812** [comment]
> No there is not. The plugin is not meant to behave like this

Tks bro ..
Because it has a bottom sheet flutter, normally there is a controller that helps show / hide

**Comment by salim-lachdhaf** [comment]
yeap, but in our case we have MENU/DIALOG/BOTTOMSHEET ...

**Comment by leanhro2812** [comment]
> yeap, but in our case we have MENU/DIALOG/BOTTOMSHEET ...

Hi bro
Is there any way to make use of the BottomSheet controller?

**Comment by salim-lachdhaf** [comment]
Hi, for the current versions you cannot access to controller, maybe in the next release

**Comment by leanhro2812** [comment]
> Hi, for the current versions you cannot access to controller, maybe in the next release

Yes I am looking forward to the next update
Tks. 👍

**Comment by leanhro2812** [comment]
@salim-lachdhaf 
Have you considered this issue yet?
I have been waiting since version 0.4.4
and now 0.4.6 already :(

**Comment by salim-lachdhaf** [comment]
@leanhro2812 , yes in the version 0.4.6 this feature is available, check plugin example

**Comment by leanhro2812** [comment]
@salim-lachdhaf 
Can't I find any info about proactively show / hide dropdown?
Where is the example?

**Comment by salim-lachdhaf** [comment]
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart
the last examples

**Comment by GiddyNaya** [comment]
1) Initialize globalkey:


```
final _openDropDownProgKey = GlobalKey<DropdownSearchState<int>>();
```

2) Set key to your dropdownsearch widget:

```
DropdownSearch<int>(
                key: _openDropDownProgKey,
```

3) Trigger popup from anywhere:

```
_openDropDownProgKey.currentState?.openDropDownSearch();
```
