### ISSUE TITLE
Add useRootNavigator Property

### ISSUE THREAD

**Issue by BigDataGh-2020** [salim-lachdhaf/searchable_dropdown#374]
Thank you soo much for this plugin.
I have come accross an implementation where I need to use searchable dropdown in a page within bottom nav.
The problem is that, the bottomsheet slides under the bottom nav instead of above. I cloned plugin and included the useRootNavigator Property of the bottomsheet so I can set it as true or false which in my scenario is true.

DropdownSearch(
      popupTitle: Padding(
        padding: const EdgeInsets.symmetric(vertical: 15),
        child: Center(
          child: Text(title!,
            style: const TextStyle(fontWeight: FontWeight.w500),),
        ),
      ),
      mode: Mode.BOTTOM_SHEET,
      showSearchBox: list!.length > 8 ? true : false,
      useRootNavigator: true,
      dropdownSearchDecoration: InputDecoration(
        contentPadding: const EdgeInsets.symmetric(vertical: 4, horizontal: 15),
        enabledBorder: inputBorder,
        focusedBorder: inputBorderFocused,
        errorBorder: inputBorder,
        focusedErrorBorder: inputBorderFocused,
        filled: true,
        fillColor: Colors.white,
      ),

So what I'm asking is to include this useRootNavigator property

**Comment by salim-lachdhaf** [comment]
property added for the next version.

stay tonned ;)
