### ISSUE TITLE
How To Change The SelectedItem Color in Single Selection DropDownSearch

### ISSUE THREAD

**Issue by AsadAMalikDeveloper** [salim-lachdhaf/searchable_dropdown#375]

**Comment by vasilich6107** [comment]
@AsadAMalikDeveloper 
Do not hesitate to look through the other issues

https://github.com/salim-lachdhaf/searchable_dropdown/issues/352
https://github.com/salim-lachdhaf/searchable_dropdown/issues/341

and check the `example`
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart#L350
