### ISSUE TITLE
Customizing the "No data found" text

### ISSUE THREAD

**Issue by alinealflen** [salim-lachdhaf/searchable_dropdown#38]
Is there a way to customize the "No data found" text?
I can't seem to find it, but I need to change it to something in my language (pt).

**Comment by leanhro2812** [comment]
emptyBuilder: (dataWidget) {
      return Center(
           child: Text('No data found, try again...'),
     );
},

**Comment by alinealflen** [comment]
Thank you.
And congratulations on the plugin, it helped me alot.

:D
