### ISSUE TITLE
[bug] Softkeyboard popup disconnects TextField from input

### ISSUE THREAD

**Issue by gslender** [salim-lachdhaf/searchable_dropdown#380]
The current release 2.0.1 has a serious bug that stops it working on iPhone/Android etc...

With the following example, when the soft keyboard pops up, and pushes all content up, the Textfield disconnects and no longer receives input. Odd enough, the input shows in the text field, but onChanged events are not trickling down to the filter (and not updating the list of items).

Have not been able to create a simple example to show this, but have tracked down the bad bit of code in the library that causes this - it must be due to the way I'm "building" the UI and the widget is rebuilt and creates duplicate DropDown widgets, which in turn are creating extra TextEditingControllers...

**Comment by yasaman93** [comment]
I have this problem, How did you fix it?

**Comment by yasaman93** [comment]
I realized that this problem only happens in android 11 (and maybe above 11)

**Comment by yasaman93** [comment]
It's odd, but [this library](https://pub.dev/packages/dropdown_search2) doesn't have this problem. I wanted to use that, but it has another problem: when I searched selected items, they seemed to be unselected in the result, and when I reselect them, they were removed from selected items!!!

**Comment by yasaman93** [comment]
@gslender can you reopen this issue if you haven't solved it?
It's very important to me!

**Comment by gslender** [comment]
Yes I have figured out the issue with this library. I will post a PR with the fixes in a day. It was essentially incorrectly creating a TextController on every build, which it didn't connect a listener because that was done in init!

**Comment by gslender** [comment]
I have raised a PR for this bug. https://github.com/salim-lachdhaf/searchable_dropdown/pull/383

**Comment by gslender** [comment]
Note, even though the PR fixes the bug, and doesn't introduce another, the package owner has closed the PR claiming it causes a regression (but fails to explain where and how)... so FYI if you have this bug, then you probably need to raise this issue again, and whilst my PR fixes it, it won't be implemented and the original bug will remain. Annoying but sometimes happens with Open Source where the effort invested by the package owner is variable and not always appropriate

**Comment by gslender** [comment]
So you fixed it in your latest code by doing exactly what I did in my PR ? What the ???
