### ISSUE TITLE
Unexpectedly large widget size

### ISSUE THREAD

**Issue by hasaan1582** [salim-lachdhaf/searchable_dropdown#381]
Hy developer, Great job on the library.
I am using the library and facing the issue that, every time I create this dropdown widget, it makes it unexpectedly large, and if I try to make it smaller by wrapping it in the sized box then the selected item vanishes and the dropdown icon is also dis-aligned.
Any suggestion would be great.
Thanks

**Comment by vasilich6107** [comment]
@hasaan1582 use showAsSuffixIcons: true

**Comment by hasaan1582** [comment]
> @hasaan1582 use showAsSuffixIcons: true

@vasilich6107 Thank you so much for that, it worked.
if you can explain why this was happening, that would be great.
Thanks anyways :)

**Comment by vasilich6107** [comment]
Check the source code)
