### ISSUE TITLE
Filter doesn't work in multiSelection in Android 11 and maybe above android 11!

### ISSUE THREAD

**Issue by yasaman93** [salim-lachdhaf/searchable_dropdown#382]
When I search something in Android 11, it doesn't work!

**Comment by salim-lachdhaf** [comment]
Tested and it works well on both Android 11 and 12.

**Comment by yasaman93** [comment]
It doesn't work and I'm completely sure about it! When you search something, results aren't filtered. We released our app with this bug and I can give you the link to test it. 
There is also [another issue](https://github.com/salim-lachdhaf/searchable_dropdown/issues/380) related to this bug. In addition, there was[ a pull request](https://github.com/salim-lachdhaf/searchable_dropdown/pull/383) which can resolve this bug. 
Please fix it :(

**Comment by salim-lachdhaf** [comment]
you have to provide an example code that prove that, because i'm sure you are missing something or forget something like `itemAsString` ....

**Comment by yasaman93** [comment]
This is my code:

```
DropdownSearch<String>.multiSelection(
              mode: Mode.BOTTOM_SHEET,
              popupBackgroundColor: Colors.white,
              showAsSuffixIcons: true,
              showFavoriteItems: false,
              showSearchBox: true,
              showClearButton: true,
              showSelectedItems: true,
              searchFieldProps: TextFieldProps(padding: EdgeInsets.all(Dimens.margin_12)),
              dropdownBuilder: (context, items) {
                return Wrap(
                  children: items.map((e) => defaultItemMultiSelectionMode(e)).toList(),
                );
              },
              itemAsString:(item){return item.toString();} ,
              selectedItems: widget.nativeLanguages.map((id) {
                return reversedLangMap[id]!.toString();
              }).toList(),
              items: snapshot.data?.keys.toList(),
              dropdownSearchDecoration: InputDecoration(
                isCollapsed: true,
                label: Text(
                  "Native Languages",
                  style: TextStyle(fontSize: Dimens.font_17, color: ColorsApp.sultan_blue.withOpacity(0.9), fontWeight: FontWeight.w500),
                ),
                filled: true,
                fillColor: AppColors.bgColor.withOpacity(0.1),
                enabledBorder: OutlineInputBorder(
                    borderSide: BorderSide(color: AppColors.bgColor.withOpacity(0.2)), borderRadius: BorderRadius.all(Radius.circular(16.0))),
                focusedBorder: OutlineInputBorder(
                    borderSide: BorderSide(color: AppColors.bgColor.withOpacity(0.5)), borderRadius: BorderRadius.all(Radius.circular(16.0))),
                hintText: "Choose your native languages",
                contentPadding: EdgeInsets.symmetric(horizontal: Dimens.margin_12, vertical: Dimens.margin_16),
              ),
              onChanged: (List<String> selectedLangs) {
                _nativeLanguages.clear();
                List<String> nativeLangCodes = List<String>.from(selectedLangs.map((i) => snapshot.data?[i]));
                _nativeLanguages.addAll(nativeLangCodes);
                nativeLanguagesLength.value = _nativeLanguages.length;
                widget.nativeLanguagesSelected(_nativeLanguages);
              },
            ),
```

I tested on emulators with Android 11 and 12 and there wasn't any problem. 

But on real devices with Android 11 it doesn't filter the results. So please test on a real device with Android 11 or above.

**Comment by gslender** [comment]
As mentioned, the package owner isn't correctly creating TextController at the right time/space, and as a result, it would be disconnecting the listeners as a new controller is added (but the listener wasn't). I've outlined a fix, and whilst it produces no regression, the package owner can't seem to get his head around it and has moved on... such as shame and I might just fork this repo and start another that has this bug fixed (so it helps others) --- thoughts?

**Comment by gslender** [comment]
Just checked the latest code and for some reason the code I submitted in my PR was included but the author denied the PR because of regression bugs !? Crazy and I'm very concerned for the quality of this package.
