### ISSUE TITLE
How to change color of unselected item square box?

### ISSUE THREAD

**Issue by danPyk** [salim-lachdhaf/searchable_dropdown#385]
I have problem - when my app is in dark mode, I can't see borders around selected items boxes. Is there any way to change color it? I don't want to change color of `popupBackgroundColor`

**Comment by vasilich6107** [comment]
@danPyk could you provide copy pastable reproduction code which will show your issue?
Something like main.dart

**Comment by salim-lachdhaf** [comment]
@danPyk you can use `popupItemBuilder`.

**Comment by danPyk** [comment]
@salim-lachdhaf The problem with this solution is that the background behind checkboxes still stay black, so I can't see unchecked ones.
![image](https://user-images.githubusercontent.com/78931719/167595300-0ec0fe5a-941f-4be2-a5da-73a2edbe2431.png)


@vasilich6107 
Code:
` DropdownSearch<String>.multiSelection(
                    mode: Mode.MENU,
                    popupItemBuilder: _customPopupItemBuilderExample,
                    popupBackgroundColor: Provider.of<Themes>(context).getTheme.primaryColor,
                    items: _createQueryVM.tagsList,
                    showSelectedItems: true,
                    dropdownSearchTextAlign: TextAlign.center,
                    // dropdownSearchBaseStyle: TextStyle(color: Provider.of<Themes>(context).getTheme.textTheme.bodyText1?.color),
                    dropdownSearchDecoration: InputDecoration(
                      hintText: 'Tags',
                      hintStyle: TextStyle(color: Provider.of<Themes>(context).getTheme.textTheme.bodyText1?.color),
                      enabledBorder: UnderlineInputBorder(
                        borderSide: BorderSide(
                            color: Provider.of<Themes>(context).getTheme.textTheme.bodyText1?.color as Color, width: 1.2, style: BorderStyle.solid),
                      ),
                    ),
                    popupItemDisabled: (String s) => s.startsWith('I'),
                    onChanged: (List<String> selectedValue) {
                      _createQueryVM.selectedItems = selectedValue;
                    },
                    selectedItems: _createQueryVM.selectedItems,
                  ),`
                  
           
`  Widget _customPopupItemBuilderExample(
      BuildContext context, String? item, bool isSelected) {
    return Container(
      margin: EdgeInsets.symmetric(horizontal: 8),
      decoration: !isSelected
          ? BoxDecoration(
        border: Border.all(color: Theme.of(context).primaryColor),
        borderRadius: BorderRadius.circular(5),
        color: Colors.blue,
      )
          : BoxDecoration(
        border: Border.all(color: Theme.of(context).primaryColor),
        borderRadius: BorderRadius.circular(5),
        color: Colors.white,
      ),
      child: Padding(
        padding: const EdgeInsets.only(bottom: 4.0),
        child: ListTile(
          selected: isSelected,
          title: Text(item!),

        ),
      ),
    );
  }`
