### ISSUE TITLE
Display properly a large list of select items

### ISSUE THREAD

**Issue by alan-valenzuela93** [salim-lachdhaf/searchable_dropdown#386]
Hi!
The situation is this, i have a list of items (users in this case) and i've implement a 'select all' option. The problem is that the list is huge, there are thousands of users and when i select them all, the app hangs there. It is not due to my 'selectAll' function, but to show so many selected items, I think. Like i said in the title, how should i handle this cases? Also, i have pre-selected users on another screen that sometimes could be thousands of them. That's why i was thinking of somehow displaying up to 5 or 3 users selected and after that just a few '...'. I don't know if it's possible something like that.

I hope I have explained myself well.  Thanks for this awesome package!

**Comment by vasilich6107** [comment]
could you provide copy pastable reproduction code which will show your issue?
Something like main.dart

**Comment by alan-valenzuela93** [comment]
Sure, i hope this will do.


class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'title',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class Example extends StatefulWidget {
  Example({Key? key}) : super(key: key);

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  final _multiKey = GlobalKey<DropdownSearchState<User>>();

  List<User> usersList = [];

  //pre-selected users comes from a 'users' array from API
  List<User> selectedUsers = [];

  List<Map<String, dynamic>> usersId = [];

  Map<String, dynamic> userObj = {};
  List<dynamic> resultClean = [];

  setUsers(List<User> selected) {

    //to remove possible duplicate items
    final jsonList = selected.map((item) => jsonEncode(item)).toList();

    final uniqueJsonList = jsonList.toSet().toList();

    final result = uniqueJsonList.map((item) => jsonDecode(item)).toList();

    result
        .map((e) => {
              this.userObj = {"_id": e["_id"]},
              usersId.add(userObj)
            })
        .toList();

    setState(() {
      final modificationUsersIdClean =
          usersId.map((item) => jsonEncode(item)).toList();
      final uniqueJsonListClean = modificationUsersIdClean.toSet().toList();
      this.resultClean =
          uniqueJsonListClean.map((item) => jsonDecode(item)).toList();
    });
  }

  Widget multiSelectedUsers(BuildContext context, List<User?> selectedItems) {
    return Wrap(
      children: selectedItems.map((e) {
        return Padding(
          padding: const EdgeInsets.all(4.0),
          child: Container(
            child: ListTile(
              contentPadding: EdgeInsets.all(0),
              title: Text(e.getName()),
            ),
          ),
        );
      }).toList(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        constraints: BoxConstraints(maxHeight: 400),
        padding: EdgeInsets.only(left: 15, right: 15),
        child: Card(
            elevation: 0,
            child: DropdownSearch<User>.multiSelection(
              key: this._multiKey,
              dropdownSearchDecoration: InputDecoration(
                  labelText: 'Usuarios', labelStyle: TextStyle(color: dark)),
              showSearchBox: true,
              dropdownBuilder: multiSelectedUsers,
              popupValidationMultiSelectionWidget: (context, list) {
                return Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    Padding(
                      padding: EdgeInsets.all(8),
                      child: OutlinedButton(
                        onPressed: () {
                          //_multiKey.currentState?.closeDropDownSearch();
                        },
                        child: const Text('Cancel'),
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.all(8),
                      child: OutlinedButton(
                        onPressed: () {
                          // How should I select all items in the list?
                          _multiKey.currentState
                              ?.changeSelectedItems(usersList);
                        },
                        child: const Text('All'),
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.all(8),
                      child: OutlinedButton(
                        onPressed: () {
                          // How should I unselect all items in the list?
                          //_multiKey.currentState?.popupDeselectAllItems();
                        },
                        child: const Text('None'),
                      ),
                    ),
                  ],
                );
              },
              mode: Mode.BOTTOM_SHEET,
              selectedItems: selectedUsers,
              items: usersList,
              popupOnItemRemoved: (userSelected, user) => removeUser(user),
              itemAsString: (User? u) => fixChars(u!.getName()),
              onChange: (selected) {
                setUsers(selected);
              },
            )));
  }
}

**Comment by salim-lachdhaf** [comment]
the issue is related to Flutter.
check here for more details
https://github.com/flutter/flutter/issues/97087
