### ISSUE TITLE
Change color of the icon when the dropdown shows options!

### ISSUE THREAD

**Issue by martinmelchior** [salim-lachdhaf/searchable_dropdown#388]
Sorry I'm new to GitHub. I hope this is the appropriate place to ask something.
How can I change the color of the icon to gray, when the dropdown shows its options?
In the image, the blue icon should look gray!
How could I change the iconEnabledColor property?
![Screenshot_20220413-174635](https://user-images.githubusercontent.com/64325299/163269742-2bf0395d-b502-4051-8b22-b83b425bc128.png)

**Comment by salim-lachdhaf** [comment]
you can use `dropdownButtonProps` to full customization of your dropdown icon.

**Comment by NotNotMarshall** [comment]
> `dropdownButtonProps`

Can't find isEnabledColor! DO YOU FUCKING MIND?

**Comment by NotNotMarshall** [comment]
None of these seemed to help
![Screenshot from 2022-07-24 13-36-58](https://user-images.githubusercontent.com/23288867/180640233-56c5fb56-7ac2-4de2-92be-e81beca56b1e.png)

I want the colour of the button to change when I open the list/menu/bottom sheet

**Comment by NotNotMarshall** [comment]
> you can use `dropdownButtonProps` to full customization of your dropdown icon.

focusColor, hoverColor, splashColor, highlightColor
none of the above worked for my case

**Comment by NotNotMarshall** [comment]
> you can use `dropdownButtonProps` to full customization of your dropdown icon.

![Screenshot_20220724-134836](https://user-images.githubusercontent.com/23288867/180640686-3175cad9-cbe4-4b7e-88ed-3f8d142b6c46.jpg)
How do you change the Icon's colour when tapped?

**Comment by miDeb** [comment]
@XiXiongMaoXiong You can do something like this:
```dart
dropdownDecoratorProps: DropDownDecoratorProps(
  dropdownSearchDecoration: InputDecoration(
    suffixIconColor: MaterialStateColor.resolveWith((states) {
      if (states.contains(MaterialState.focused)) {
        return  Colors.red /* focused color */;
      }
      return Colors.gray /* default color */;
    }),
  ),
),
```
