### ISSUE TITLE
DropdownMenuItem not working

### ISSUE THREAD

**Issue by ravidewanga** [salim-lachdhaf/searchable_dropdown#394]
mode: Mode.DIALOG,
                //showSelectedItems: true,
                showSearchBox: true,
                items:courseList.map((item) {
                  print('item $item');
                  return DropdownMenuItem(
                    child: Text(item['COURSENAME'].toString()),
                    value: item['COURSECD'].toString(),
                  );
                }).toList(),
                dropdownSearchDecoration: InputDecoration(
                  labelText: "Menu mode",
                  hintText: "country in menu mode",
                ),
                onChanged: print,
                selectedItem: "select",
              )

**Comment by salim-lachdhaf** [comment]
@ravidewanga your items should not be a widget. take a look to the examples page.
