### ISSUE TITLE
How can I change popupItemBuilder height dynamically?

### ISSUE THREAD

**Issue by TotoroDes** [salim-lachdhaf/searchable_dropdown#395]
I need change popupItemBuilder height, when I get items from api request. I don`t find how. Help me please)

**Comment by salim-lachdhaf** [comment]
this will be available in the next version (dynamic height).
for now you can use `maxHeight`

**Comment by TotoroDes** [comment]
Thanks, I'm waiting)

**Comment by TotoroDes** [comment]
Thanks)
