### ISSUE TITLE
The Scrollbar's ScrollController has no ScrollPosition attached Bug

### ISSUE THREAD

**Issue by MalikSamiAwan** [salim-lachdhaf/searchable_dropdown#399]
**Currently i am not able to scroll using scrollbar in web, desktop. Even i have provided the scroll controller and initial position as well. Could you share same example for that. Thanks in advance. Here is my code.**

`import 'package:chefnourish_app/helpers/app_style.dart';
import 'package:dropdown_search/dropdown_search.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class CustomSearchableDropDown extends StatefulWidget {
  final Mode menu;
  final bool showSelectedItem;
  final bool showSearchBox;
  final List<String> items;
  final Function(String? x) onChanged;
  final String labelText, hintText;
  const CustomSearchableDropDown(
      {Key? key,
        this.menu = Mode.MENU,
        this.showSelectedItem = true,
        this.showSearchBox = true,
        required this.items,
        required this.onChanged,
        this.labelText = 'Select',
        this.hintText = 'Search'})
      : super(key: key);

  @override
  State<CustomSearchableDropDown> createState() => _CustomSearchableDropDownState();
}

class _CustomSearchableDropDownState extends State<CustomSearchableDropDown> {
  late ScrollController _controller;
  late ScrollbarProps _scrollbarProps;
  @override
  void initState() {
    _controller=new ScrollController(initialScrollOffset: 0,keepScrollOffset: true);
    _scrollbarProps=new ScrollbarProps(interactive: true,controller:_controller );
    super.initState();
  }
  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return DropdownSearch<String>(
      scrollbarProps: _scrollbarProps,
      validator: (v) => v == null ? "required field" : null,
      autoValidateMode: AutovalidateMode.onUserInteraction,
      mode: widget.menu,
      showSelectedItems: widget.showSelectedItem,
      items: widget.items,
      //This is for the dropdown .
      popupShape: RoundedRectangleBorder(
        side: BorderSide(color: AppStyle.cupertinoGrey, width: .5),
        borderRadius: BorderRadius.vertical(bottom: Radius.circular(5)),
      ),
      searchFieldProps: TextFieldProps(
        decoration: InputDecoration(
          hintText: "Search",
          contentPadding: const EdgeInsets.only(left: 8, bottom: 4),

          //This is for Inner DropDown Search Input
          enabledBorder: OutlineInputBorder(
            borderSide: BorderSide(color: AppStyle.cupertinoGrey, width: .5),
            borderRadius: BorderRadius.all(Radius.circular(5)),
          ),
        ),
      ),
      dropdownSearchDecoration: InputDecoration(
        errorStyle: AppStyle.errorTextStyle.copyWith(color: Colors.red),
        counterStyle:AppStyle.counterTextStyle ,
        labelText: widget.labelText,
        // hintText: hintText,
        contentPadding: const EdgeInsets.only(left: 16, bottom: 8),
        border: OutlineInputBorder(
          borderSide: BorderSide(color: AppStyle.red, width: .5),
          borderRadius: BorderRadius.all(Radius.circular(5)),
        ),
        //This is for the main panel, when the dropdown appears.
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: AppStyle.cupertinoGrey, width: .5),
          borderRadius: BorderRadius.vertical(top: Radius.circular(5)),
        ),
      ),

      // dropdownSearchDecoration: InputDecoration(
      //   labelText: labelText,
      //   hintText: hintText,
      // ),
      onChanged: widget.onChanged,
      showSearchBox: widget.showSearchBox,
      // selectedItem: "Brazil",
    );
  }
}
`

**Comment by salim-lachdhaf** [comment]
it's a Flutter issue.
check here https://github.com/flutter/flutter/issues/97873

**Comment by salim-lachdhaf** [comment]
yes

**Comment by MalikSamiAwan** [comment]
@salim-lachdhaf thanks for answering, but i am still having this issue on mac os do i need to update package or what?

**Comment by salim-lachdhaf** [comment]
are you using the last version 5.0.1 ?
