### ISSUE TITLE
search entry as parameter on emptyBuilder

### ISSUE THREAD

**Issue by fahrezahafiz** [salim-lachdhaf/searchable_dropdown#40]
the `emptyBuilder` function should have the current search entry as a parameter alongside the build context.

```dart
...
emptyBuilder: (context, searchEntry) {
  return ListTile(
    title: Text('No result for $searchEntry'),
  );
},
...
```

This also might be useful if we want to implement a logic based on the search result, for instance:
Create a new dropdown entry from the user input on the `searchBox`

```dart
...
emptyBuilder: (context, searchEntry) {
  return ListTile(
    title: Text('Add new entry for $searchEntry'),
    onTap: () => addNewEntry(searchEntry),
  );
},

void addNewEntry(String entry) {
  // logic for adding a new entry here
}
...
```

**Comment by salim-lachdhaf** [comment]
Thank you for your proposition, this will be on the next version ;)
