### ISSUE TITLE
dropdown_search.dart:551:26: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by bmoraa** [salim-lachdhaf/searchable_dropdown#402]
Hi, I'm @bmoraa
I'm looking for your review about the next warning; i got it after updating flutter and dropdown_search.dart.

/C:/Users/bibia/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dropdown_search-3.0.1/lib/dropdown_search.dart:519:26: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/binding.dart').
          WidgetsBinding.instance!.addPostFrameCallback((_) {
                         ^

This is my flutter doctor summary-
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22000.675], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.10)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.67.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

Thank you in advance.

**Comment by sunnykinger** [comment]
Same issue

**Comment by salim-lachdhaf** [comment]
this warning is solved in the next version.

**Comment by zeshuaro** [comment]
Hey @salim-lachdhaf, would you be able to keep this issue opened until the next version is released? I almost opened a duplicate issue.
