### ISSUE TITLE
Provide the ability to disable dropDownButton.

### ISSUE THREAD

**Issue by vitalsh** [salim-lachdhaf/searchable_dropdown#412]
Just like with 'showClearButton' please provide the ability not to show the dropdownButton.
Ideally by providing a boolean parameter: showDropDownButton.

**Comment by slavap** [comment]
@salim-lachdhaf 
Exactly as I've asked in https://github.com/salim-lachdhaf/searchable_dropdown/issues/390
showDropdownButton is needed for sure.

**Comment by salim-lachdhaf** [comment]
added in the next version.
