### ISSUE TITLE
Provide the ability to set scrollbar color

### ISSUE THREAD

**Issue by vitalsh** [salim-lachdhaf/searchable_dropdown#413]
Please provide the ability to set scrollbars color in the lists.
This can be easily achieved by replacing ScrollBar with RawScrollBar which allows to set the thumb color.
i.e: 
RawScrollBar(
  thumbColor: Theme.of(context).primaryColor, 
  // insterad of Theme.of(context).primaryColor, the optional color or null for default
)

**Comment by salim-lachdhaf** [comment]
added in the next version.
