### ISSUE TITLE
Please add support for Flutter 3.0.0

### ISSUE THREAD

**Issue by NikhilKukreja26** [salim-lachdhaf/searchable_dropdown#416]
Hello,
I am Flutter Version 3.0.0 and Dart SDK Version 2.17.0. But after the upgrade, I am getting these exceptions
Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart'). WidgetsBinding.instance?.addPostFrameCallback(
                   ^

The application is running fine in debug mode, but I cannot build the release version for android and ios.

**Comment by salim-lachdhaf** [comment]
already supported , please check last version before posting a bug ...

**Comment by NikhilKukreja26** [comment]
But on pub.dev the version is not updated to latest version
