### ISSUE TITLE
How do you enable multiple select ?

### ISSUE THREAD

**Issue by josephwaiguru** [salim-lachdhaf/searchable_dropdown#42]
Is there a way to enable multiple select ?

**Comment by salim-lachdhaf** [comment]
this feature is coming soon ;)

**Comment by salim-lachdhaf** [comment]
this is will be in the next version ;)

**Comment by ronytesler** [comment]
@salim-lachdhaf next version is 0.4.8?

**Comment by salim-lachdhaf** [comment]
no multi selection is not available yet. current version is 0.5.0. it still need some work.

**Comment by ronytesler** [comment]
Any idea approximately when it will be ready?
Will it support an "other" option with a free text?

Thanks.

**Comment by salim-lachdhaf** [comment]
for now sadly i have no idea.
