### ISSUE TITLE
focusNode property is needed for DropdownSearch input field

### ISSUE THREAD

**Issue by slavap** [salim-lachdhaf/searchable_dropdown#421]
Currently it is possible to set focus to clear and dropdown buttons by using focusNode in clearButtonProps and dropdownButtonProps.
Also for search field there is:
```dart
/// props for selection focus node
final FocusNode? focusNode;
```
BUT there is not way to set focus to DropdownSearch itself.

**Comment by salim-lachdhaf** [comment]
the dropdownSearch is based on `FormField` which has not a `FocusNode` prop, how ever, focusing DropdownSearch means isOpened , in that case you can just open it programmatically and it will be focused...

**Comment by slavap** [comment]
@salim-lachdhaf I don't get your advice - if I call openDropDownSearch() it will open popup, which is not desired behavior, I need to focus it (just like navigating to it by pressing TAB).

**Comment by salim-lachdhaf** [comment]
i see your need but it's not possible to add `FocusNode` on `FormField` sadly.

**Comment by dsyrstad** [comment]
@slavap I'm just wrapping `DropdownSearch` in a `Focus` and giving the `FocusNode` to that widget. Seems to work for me.

**Comment by kateile** [comment]
@dsyrstad any example how you did that?

**Comment by dsyrstad** [comment]
> @dsyrstad any example how you did that?

@kateile Like this:

```dart
  Widget build(BuildContext context) {
    return Focus(
      focusNode: focusNode,
      child: DropdownSearch<SomeObject>(
...
```
