### ISSUE TITLE
Change layout of OK button on dropdown menu

### ISSUE THREAD

**Issue by vinhhoangdo** [salim-lachdhaf/searchable_dropdown#424]
**Do you mind if you let me know how to change the button submits items what we choose in dropdown menu?**

**Thank you!**

**Comment by salim-lachdhaf** [comment]
you can use `popupValidationMultiSelectionWidget` from `PopupPropsMultiSelection`

**Comment by vinhhoangdo** [comment]
Wow, thank you! But um, how to set the new position of button if we make a custom?. Because when I tried to custom OK button and it always expanded from the bottom right.

**Comment by salim-lachdhaf** [comment]
in that case, you have to use `popupCustomMultiSelectionWidget` and set `popupValidationMultiSelectionWidget` to `sizedBox.shrink()`. don't forget to handle validation by your self using `GlobalKey`
