### ISSUE TITLE
Backround effect when bottomsheet dropdown pops up

### ISSUE THREAD

**Issue by tjmeal** [salim-lachdhaf/searchable_dropdown#427]
Hello,

On Version 3.0.0 and before when the bottomsheet popup > the rest of the screen was becoming grey and when tapping outside the bottomSheet > the bottomSheet closes.

Now in version 5.0.1 thats not the case (at least by default) how can i set the same functionality (please check the image of the desired functionality)

Thanks you very much i will be waiting your reply. 

![Screenshot 2022-06-02 at 12 50 25](https://user-images.githubusercontent.com/54618806/171615596-9b91dfa5-d9d6-47fc-9d54-08080ac99422.jpeg)

**Comment by tjmeal** [comment]
Thanks for your reply.

Yeap that was it, can you please also let me know how can i decrease the marked red gap (i want to remove it like my original image)

![Simulator Screen Shot - iPhone 12 - 2022-06-03 at 09 19 46](https://user-images.githubusercontent.com/54618806/171798280-eb45fefb-5be7-4b4e-9d36-d5a9d3c92650.png)


Before it was: mode: Mode.BOTTOM_SHEET

Thanks again i will be waiting your reply.

**Comment by kanaydo** [comment]
hi, did you fix the empty gaps?, i'm having the same problem here.
