### ISSUE TITLE
 search problems

### ISSUE THREAD

**Issue by jpjf** [salim-lachdhaf/searchable_dropdown#43]
when I generate a search with the following example it does not deliver results and the API does

         DropdownSearch<UserModel>(
                mode: Mode.BOTTOM_SHEET,
                isFilteredOnline: true,
                showClearButton: true,
                showSearchBox: true,
                label: 'User *',
                dropdownSearchDecoration: InputDecoration(
                    filled: true,
                    fillColor:
                        Theme.of(context).inputDecorationTheme.fillColor),
                autoValidate: true,
                validator: (UserModel u) =>
                    u == null ? "user field is required " : null,
                onFind: (String filter) => getData(filter),
                onChanged: (UserModel data) {
                  print(data);
                },
                dropdownBuilder: _customDropDownExample,
                popupItemBuilder: _customPopupItemBuilderExample,
              ),

**Comment by salim-lachdhaf** [comment]
hi, the plugin works well for this example. i think you miss something, try our example , it has an example similar to this
