### ISSUE TITLE
Mode: DIALOG cannot display the selected Value. 

### ISSUE THREAD

**Issue by hanancs** [salim-lachdhaf/searchable_dropdown#436]
Following code, I've written to implement Searchable_dropdown widget; 

```
DropdownSearch<String>(
                mode: Mode.DIALOG,
                showSelectedItem: true,
                validator: (value) {
                  if (value == null) {
                    return 'Select a type';
                  }
                  return null;
                },
                hint: "Filter by type",
                items: Provider.of<ComplainProvider>(context)
                    .complainTypeList
                    .map((e) => e.name!)
                    .toList(),
                onChanged: (value) {
                  ComplainProvider complainProvider =
                      Provider.of<ComplainProvider>(context, listen: false);
                  ComplaintType complaintType = complainProvider
                      .complainTypeList
                      .firstWhere((element) => element.name == value);
                  this._selectedComplaintType = complaintType;
                  this.pageLoadController!.reset();
                }),
```
If I change the mode to either MENU or BOTTOM_SHEET, it works as expected and displays the selected value without any error. But when it comes to mode: Mode.DIALOG, it keeps on giving me errors like 

> ════════ Exception caught by gesture ═══════════════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════

Screenshots are provided below;

![image](https://user-images.githubusercontent.com/50701475/174953097-cff36204-c855-4c03-8b7c-514ad724a9a3.png)
![image](https://user-images.githubusercontent.com/50701475/174953191-05ab1f63-129b-4c1e-a36b-2ccd1c133bef.png)

**Comment by salim-lachdhaf** [comment]
try the last version.
