### ISSUE TITLE
List items not visible in dark and light theme

### ISSUE THREAD

**Issue by MalayAgrawal** [salim-lachdhaf/searchable_dropdown#438]
List items that are displayed as selected items are not visible.

When the app is in the dark theme containers appear as white when in the light they appear as black and have no visible text.

```
                            DropdownSearch<String>.multiSelection(
                              dropdownDecoratorProps: DropDownDecoratorProps(
                                  dropdownSearchDecoration: InputDecoration(
                                      hintText: " + Add Participant",
                                      floatingLabelStyle:
                                          TextStyle(color: Colors.red))),
                              items: participent_list,
                              popupProps: PopupPropsMultiSelection.menu(
                                  showSearchBox: true),
                            ),
```
![Screenshot_1656446698](https://user-images.githubusercontent.com/55668156/176277015-ee57a3f8-d55f-436b-839e-875956964348.png)

**Comment by sanchitverma168** [comment]
same issue color is not override with Theme or I am also unable to assign dynamic color as I want

**Comment by salim-lachdhaf** [comment]
i tested the dark mode and it works well, it seems that you overrided the itemBuilder ... and setted the text to white ...
![image](https://user-images.githubusercontent.com/13780503/191795883-e95a2c3e-0454-46d4-9267-b199c7057275.png)

if not please paste a reproductible example to analyse the issue.

**Comment by AlexBurdu** [comment]
Hi @salim-lachdhaf, here's a reproducible example for broken dark mode with `modalBottomSheet` popup: https://github.com/AlexBurdu/dropdown_dark_mode_broken_modal

Please let me know if you feel  it's unrelated to this issue and I can create a new one.

**Comment by salim-lachdhaf** [comment]
@AlexBurdu thanks for the example, i will check it.
