### ISSUE TITLE
Unable to set text color

### ISSUE THREAD

**Issue by SuricateTrading** [salim-lachdhaf/searchable_dropdown#439]
I am unable to change the color of of the text in the dropdown or the text of the popup. The text is always black.

Code:
```
            DropdownSearch(
              popupProps: PopupProps.menu(
                textStyle: TextStyle(color: Colors.yellow),
                menuProps: MenuProps(
                  backgroundColor: Colors.orange,
                  textStyle: TextStyle(color: Colors.yellow),
                ),
              ),
              items: [1, 2, 3],
              dropdownDecoratorProps: DropDownDecoratorProps(
                baseStyle: TextStyle(color: Colors.yellow),
                dropdownSearchDecoration: InputDecoration(
                  hintText: "hint",
                  hintStyle: TextStyle(color: Colors.green, fontStyle: FontStyle.italic),
                  border: OutlineInputBorder(borderSide: BorderSide(color: Colors.blue, width: 2)),
                ),
              ),
            )
```

I am using version 5.0.2 and tested in Chrome.

Edit:
I also can't change the color of the outline border. I've updated the example.

**Comment by abdullah017** [comment]
you can wrap it with Theme widget:

```
Theme(
          data: ThemeData(
            textTheme: TextTheme(subtitle1: TextStyle(color: Colors.green)),
          ),
          child: DropdownSearch<String>(
            mode: Mode.BOTTOM_SHEET,
            showSearchBox: true,
            dropdownSearchDecoration: new InputDecoration(
              enabledBorder: UnderlineInputBorder(
                borderSide: BorderSide(color: Colors.red),
              ),
...
```

**Comment by SuricateTrading** [comment]
Thanks, but this workaround does not work for the outline border or any other color property than text.
Also, it changes the color of all text inside the theme widget, not just thepopup text color.

**Comment by yutech23** [comment]
> you can wrap it with Theme widget:
> 
> ```
> Theme(
>           data: ThemeData(
>             textTheme: TextTheme(subtitle1: TextStyle(color: Colors.green)),
>           ),
>           child: DropdownSearch<String>(
>             mode: Mode.BOTTOM_SHEET,
>             showSearchBox: true,
>             dropdownSearchDecoration: new InputDecoration(
>               enabledBorder: UnderlineInputBorder(
>                 borderSide: BorderSide(color: Colors.red),
>               ),
> ...
> ```

Kardeşim Teşekkürler. birde center nasıl yapabiliriz?

**Comment by Stogi7789** [comment]
I have the same problem. Other properties are not showing as well. Any solution?

**Comment by salim-lachdhaf** [comment]
1- for the dropdownDecoration : is not a issue. take a look here https://stackoverflow.com/questions/50122394/not-able-to-change-textfield-border-color
you have already the same issue with TextFiled :)

2- textStyle issue: it's a bug:
textStyle is used no where. we removed it.
to change style you can use `itemBuilder` like this:
`itemBuilder: (ctx, item, isSelected)=>Text(item.toString(),style:TextStyle(color: Colors.yellow, fontSize: 20)),`

**Comment by SuricateTrading** [comment]
Creating a custom ItemBuilder is really a big overhead for something as simple as changing the text color.
