### ISSUE TITLE
Migrate version 3.0.1 to 5.0.02

### ISSUE THREAD

**Issue by SouMeiApp** [salim-lachdhaf/searchable_dropdown#442]
I need to migrate the version from version 3.0.1 and I am not able to do that. Could you help me with the following parameters:

DropdownSearch<Categoria>(
      **### mode: Mode.MENU,**
      compareFn: (c1, c2) => c1?.categoria == c2?.categoria,
      selectedItem: selectedCategory,
      items: categories,
      showClearButton: true,
      _**showSelectedItems: true,**_
      itemAsString: (m) => m?.descCategoria ?? '',
      **emptyBuilder: (_, __) => const Center(
        child: Text(
          'Nenhuma categoria disponível.',
          textAlign: TextAlign.center,
        ),**
      ),

Mode:
ShowSelectedItems
Emptybuilder

**Comment by sanchitverma168** [comment]
Please go through the changelog at pub.dev you will know which parameter is renamed  or which parameter has been changed its position. 
I was also getting same type of error when I upgraded to 5.0.1 then I read all the changelog then I learned where and how to put my existing parameters.

`DropdownSearch(
// ### mode: Mode.MENU,
      dropdownDecoratorProps: DropDownDecoratorProps(
        dropdownSearchDecoration: InputDecoration(
          labelText: "Select Unit",
        ),
      ),
      compareFn: (c1, c2) => c1?.categoria == c2?.categoria,
      selectedItem: selectedCategory,
      items: [],
      // here you can change the mode type like Bottomsheet/dialog/menu/modalbottomsheet
      popupProps: PopupProps.menu(
          showSearchBox: true,
          emptyBuilder: (_, __) => const Center(
                child: Text(
                  'Nenhuma categoria disponível.',
                  textAlign: TextAlign.center,
                ),
              ),
          showSelectedItems: true,
          title: Text(("Select Unit here"))),
      // showClearButton: true,
      clearButtonProps: ClearButtonProps(),
      itemAsString: (m) => m?.descCategoria ?? '',
    )`
