### ISSUE TITLE
modalBottomSheet padding or sizedbox

### ISSUE THREAD

**Issue by ddif** [salim-lachdhaf/searchable_dropdown#443]
Hello on v5.0.2 there is a padding or sized box upside of search widget. Is there any or where is the proper section for fixing that ?

popupProps: PopupProps.modalBottomSheet

I attacked screenshout of it . 

Thank you.
![Screenshot_1](https://user-images.githubusercontent.com/1752284/177760349-c5828e6e-470e-4742-89cf-832334dbdc33.png)

**Comment by salim-lachdhaf** [comment]
fixed in the last version.
make sure that you are using the last version of Flutter SDK.

**Comment by Badouu** [comment]
I have the same and I'm using the version : dropdown_search: ^5.0.3.
How can I add a padding to searchbox ?
<img width="411" alt="Capture d’écran 2022-09-28 à 13 17 59" src="https://user-images.githubusercontent.com/32416351/192789431-c3f59460-e89e-4580-8488-e8746917ffe5.png">
