### ISSUE TITLE
How to customize defaultItemMultiSelectionMode

### ISSUE THREAD

**Issue by ifnyas** [salim-lachdhaf/searchable_dropdown#451]
Hi, I want to customize the chip of item multi selection mode, also if possible the margin between chips. any idea? thanks

![image](https://user-images.githubusercontent.com/34657831/179323172-95399f77-cd47-4c22-933b-dcced169336a.png)

**Comment by salim-lachdhaf** [comment]
check examples page.
otherwise use `dropdownBuilder`
