### ISSUE TITLE
How to add removeitem feature on  customized list of items using dropdownBuilder?

### ISSUE THREAD

**Issue by Ipwak** [salim-lachdhaf/searchable_dropdown#452]
Hi, I am using dropdownBuilder ti custoñize the selected items in multiSelection mode, but I now miss the cross allowing me to remove the item(s) from the selection. How do I achieve this please?

Thank you!

**Comment by salim-lachdhaf** [comment]
update your liste passed to `items` and call `setState`

**Comment by Ipwak** [comment]
thanks for your answer but after updating selectedItems in setState, the selectedItems parameter in   dropdownBuilder: (context, selectedItems)  is still the same as initialized on  first build
