### ISSUE TITLE
TypeError: collection not iterable

### ISSUE THREAD

**Issue by skillFocus16** [salim-lachdhaf/searchable_dropdown#456]
**Describe the bug**
I am trying items search online and it is working(using graphql), but i keep getting this error box whenever i click on the search bar/try and search. It pops up every second.

![image](https://user-images.githubusercontent.com/19538491/181691750-59d53092-defc-448c-b038-12f9d4f4c645.png)

![dropdown search error](https://user-images.githubusercontent.com/19538491/181691588-13341ba2-aa92-4e82-aeed-20f258d5edce.PNG)

**Comment by salim-lachdhaf** [comment]
make sure that your `onFind` function returns `List<Organisation>` and the same thing for the `items`
