### ISSUE TITLE
Option to let the DropdownSearch be the search box

### ISSUE THREAD

**Issue by JustMilan** [salim-lachdhaf/searchable_dropdown#457]
**Is your feature request related to a problem? Please describe.**
At this moment I cannot find a way to let the default box work like a search box as well.
In my opinion the current way to use a search box isn’t as nice as it could be.

**Describe the solution you'd like**
Let the upper box function like the second box (actual search box) does. I think this would make it much cleaner.
![image](https://user-images.githubusercontent.com/55273851/182931286-1f595d41-a78e-487e-b11e-74f75bd6eaf1.png)

**Describe alternatives you've considered**
I have not.

**Additional context**
![image](https://user-images.githubusercontent.com/55273851/182931456-55b2b3fd-6561-4816-9103-7a50852d2b97.png)
![image](https://user-images.githubusercontent.com/55273851/182931504-1b4687d7-450d-4b33-a78d-dc828b592faa.png)
![image](https://user-images.githubusercontent.com/55273851/182931539-fae7a9a3-e381-4724-b91f-63d8aa7b3465.png)

**Comment by salim-lachdhaf** [comment]
did you tried to use `dropdownBuilder` and show it as `textField` and use it's textController to manage the textController of search field (which is hidden) ?

**Comment by kopchok** [comment]
More difficult to use. T^T

**Comment by jmsandiegoo** [comment]
@salim-lachdhaf is there an example to do the dropdownBuilder approach? That would help us a lot.
