### ISSUE TITLE
Can the checkbox be set to the left of the text in the case of multiple selections?

### ISSUE THREAD

**Issue by Jsin-Fei** [salim-lachdhaf/searchable_dropdown#458]
DropdownSearch<>.multiSelection(

I didn't find exposed property to set checkbox position。

thanks

**Comment by NafissaBHJ** [comment]
Hello, did you find a way to align box to the left ?

**Comment by salim-lachdhaf** [comment]
you can use  `selectionWidget` from `popupProps` to customize the toggle widget ...

**Comment by xakeppok** [comment]
hello. i facing the same issue and i did't find the way to set this checkbox at left. any solutions?
