### ISSUE TITLE
Not registering Taps directly after scrolling

### ISSUE THREAD

**Issue by czaefferer** [salim-lachdhaf/searchable_dropdown#459]
After I open a dropdown, I've got a number of entries I can scroll through. While scrolling, no taps are registered at all (which is not a problem for me).
After I'm done scrolling, there is a moment, where the dropdown is still scrolling on its own (getting slower until it stops completly), without me having my finger on the device.
If I tap during this moment, the scrolling will stop, but onChanged does not get called (nor any GestureDetectors around the widget).
However, I also have a global GestureDetector in my app (around the root MaterialApp), that unfocuses everything when tapped, so whenever the keyboard is open and the user taps anywhere without another tap-handler, the keyboard will always close. And this GestureDetector does get called when tapping in the moment the dropdown is still scrolling on its own. This causes the keyboard to close, so it seems to the user, their tap on an item was registered, when it really wasn't (the dropdown-elements are still visible, but the while dropdown moves down since the space of the keyboard is now free).

Is this a bug that can be fixed, or is it possible for me to either select an item when the user taps while the dropdown is scrolling on its own, or register a tap-handler for the items that does nothing, but at least prevents the global GestureDetector from being called?

**Comment by salim-lachdhaf** [comment]
i agree with you, but sadly is an Flutter issue.

please take look here https://github.com/flutter/flutter/issues/59404

we will try to find a workaround to solve the problem if possible.

**Comment by czaefferer** [comment]
Could you please elaborate how the performance of scrolling on the web platform relates to how GestureDetectors handle taps on native apps? Thank you
