### ISSUE TITLE
itemBuilder not called in search mode when popupValidate is invoked

### ISSUE THREAD

**Issue by zachary22321** [salim-lachdhaf/searchable_dropdown#464]
**Describe the bug**
I have a button in my dropdown to expand and contract rows. This works great, until I start to filter the row with the searchbox above. When the dropdown is being filtered and I click the button it calls popupvalidate, but the itembuilder function is no longer called.

**To Reproduce**
1. Filter the dropdown
2. Click the collapse button
3. No redraw is triggered and the children stay visible
**Expected behavior**
The control should redraw with the children collapsed.
**Screenshots**

**Desktop (please complete the following information):**
Windows 10
**Smartphone (please complete the following information):**
Android 13, API 33
resizable

[example files.zip](https://github.com/salim-lachdhaf/searchable_dropdown/files/9365473/example.files.zip)

**Comment by zachary22321** [comment]
Also after experimenting some more it I also notice that I cannot select items when the dropdown is filtered as well.

**Comment by salim-lachdhaf** [comment]
we could not reproduce the issue, please paste an full example to the issue to analyse the issue.
