### ISSUE TITLE
Box constraints Fixed to 500

### ISSUE THREAD

**Issue by prix737** [salim-lachdhaf/searchable_dropdown#465]
modalBottomSheet box constraints appear to be set to a maximum height of 500, regardless of a new height being defined in modal bottom sheet props. Is there a way of achieving a full Screen?

**Comment by salim-lachdhaf** [comment]
you can play with `fit` and `width` and `height` properties.

please don't hesitate to take a look to examples page.

**Comment by prix737** [comment]
Thank you for this suggestion
