### ISSUE TITLE
`emptyBuilder` always returns empty `searchEntry`?

### ISSUE THREAD

**Issue by nikneym** [salim-lachdhaf/searchable_dropdown#466]
**Describe the bug**
When I try to receive search entry that is not found on the list, I always get empty string.

**To Reproduce**
Add this prop to your DropdownSearch and do a miss search.
```dart
emptyBuilder: (context, String searchEntry) {
  print(searchEntry == "");
  print(searchEntry);
  return Text(searchEntry);
}
```

**Expected behavior**
the search entry that is not found on the list should be passed as secondary argument.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by johnnypramadya** [comment]
any updates on these issues?
