### ISSUE TITLE
How to search item with using name,phone number with same model class

### ISSUE THREAD

**Issue by nitishprivate** [salim-lachdhaf/searchable_dropdown#471]
let's take an example i have an model class
`class UserData{
String? name,
String? phoneNo,
...............
}`
Now what i want when i show list in dropdown and when user start typing name or phone number it's show the data

**Comment by salim-lachdhaf** [comment]
please don't hesitate to take a look to examples page.

**Comment by nitishprivate** [comment]
thank you for your reply can you please provide me the file i already look into example but i did not find

**Comment by nitishprivate** [comment]
sorry to disturb you. but i got the solution here is my code if anyone is looking

> filterFn: (item, filter) {
            if (filter.isEmpty) {
              return true;
            }
            if ((item.customerName
                        ?.toLowerCase()
                        .contains(filter.toLowerCase()) ??
                    "".isEmpty) ||
                (item.customerContact
                        ?.toLowerCase()
                        .contains(filter.toLowerCase()) ??
                    "".isEmpty)) {
              return true;
            } else {
              return false;
            }
          }
