### ISSUE TITLE
dropdown_search: onChanged + selectedItems does not update

### ISSUE THREAD

**Issue by SebastienFERRAND** [salim-lachdhaf/searchable_dropdown#475]
**Describe the bug**
```
DropdownSearch<StudentHappyPawn>.multiSelection(
                compareFn: (i1, i2) => i1.reference.id == i2.reference.id,
                popupProps: const PopupPropsMultiSelection.dialog(
                  showSearchBox: true,
                  showSelectedItems: true,
                ),
                asyncItems: (String filter) => storage.getStudents(),
                itemAsString: (StudentHappyPawn student) =>
                    student.studentAsString(),
                selectedItems: pickedStudentList,
                onChanged: (list) {
                  print("onChanged : $list");
                  pickedStudentList = list;
                },
              ),
```

It seems that having together selectedItems along with onChanged does not work: it does show selected items at first, but upon adding more elements, the onChanged just keeps the default element (does not print the newly-checked-items).

If I remove the selectedItems attribute, it's now correctly updating and adding (printing) the newly checked items in the onChanged.

But I need selectedItems to work along with onChanged, any suggestions?

**Comment by salim-lachdhaf** [comment]
i tested your case and it works well, there is no issue.
maybe make sure that your `pickedStudentList` is beclared **outside** the `build` function (as global variable) otherwise i see no way the reproduce your issue.
