### ISSUE TITLE
how to reset my dropdown controller to default?

### ISSUE THREAD

**Issue by vrajshah24** [salim-lachdhaf/searchable_dropdown#477]
`DropdownSearch<Map<int, String>>(
                          popupProps: const PopupProps.menu(
                            showSearchBox: true,
                          ),
                          dropdownDecoratorProps: const DropDownDecoratorProps(
                            dropdownSearchDecoration: InputDecoration(
                                label: Text('Select Market'),
                                contentPadding:
                                    EdgeInsets.fromLTRB(10, 1, 0, 20),
                                border: InputBorder.none,
                                floatingLabelBehavior:
                                    FloatingLabelBehavior.never),
                          ),
                          items: marketlist,
                          itemAsString: (item) {
                            String b = item.values.toString();
                            return b.substring(1, b.length - 1);
                          },
                          onChanged: ((value) {
                            String b = value!.keys.toString();
                            dropdownvalueformarket =
                                b.substring(1, b.length - 1);
                          }),
                        )`

**Comment by salim-lachdhaf** [comment]
request not clear.

**Comment by manandharsudhir** [comment]
How to programatically clear the selected value

**Comment by networlddeveloper** [comment]
How we can clean the selected value to default value when pressing a separate clear button(Clearing the selected value without interacting with the field )

**Comment by salim-lachdhaf** [comment]
You can do that using `globalKey`.
Please don't hesitate to check plung's last examples

**Comment by PKReejesh** [comment]
As @salim-lachdhaf pointed out, we can use `keyname.currentState?.clear();`
