### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by yusifahmadov** [salim-lachdhaf/searchable_dropdown#480]
Hello, I use 2 dropdowns in **Flutter Desktop App**. The second dropdown depends on the first dropdown. In case all of the dropdowns have data, when I go to the first one, I want to reset all data in all dropdowns. But selectedItem (setState) is not working

**Comment by salim-lachdhaf** [comment]
you don't need setState to handle your dropdown.

your can manage your dropdown using `GlobalKey` to access to dropDown fonctions.

take a look to examples page. there is a lot of examples of handling dropdown programatically
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart

**Comment by yusifahmadov** [comment]
Your method is not working. I got a error like this "myKey.currentState.clear() -> currentState is null"

**Comment by salim-lachdhaf** [comment]
take a look to the examples page:
https://github.com/salim-lachdhaf/searchable_dropdown/blob/9f1b1d67b62a2a6f23caf520c4fb078f02027312/example/lib/main.dart#L28

it's seems that you are not using the `GlobalKey` correctly
