### ISSUE TITLE
No data found text

### ISSUE THREAD

**Issue by Bryanmuloni** [salim-lachdhaf/searchable_dropdown#481]
Hi @salim-lachdhaf ,
I am using searchable_dropdown in my web app. I have also handled localization into Arabic but cannot translate this text with an arrow as in the picture here. Could it be possible to expose it as a property in the constructor to allow one to have any text in case the list is empty?
![no_data_label_LI](https://user-images.githubusercontent.com/12647392/192336879-6398a671-9825-4892-9c3d-d6a41d358d70.jpg)

**Comment by salim-lachdhaf** [comment]
you can use `emptyBuilder` , `errorBuilder,` `loadingBuilder` from `popupPros`.

**Comment by Bryanmuloni** [comment]
@salim-lachdhaf could you please give a sample code, I will start from there. Thanks in advance

**Comment by wahyu-handayani** [comment]
> you can use `emptyBuilder` , `errorBuilder,` `loadingBuilder` from `popupPros`.

Hi I little bit confused about hot to use errorBuilder here, would you like to give an example ?
