### ISSUE TITLE
link a form to dropdown search

### ISSUE THREAD

**Issue by rodriger06** [salim-lachdhaf/searchable_dropdown#482]
Hi, I am using Reactive form and would like to use this drop down search.
my form looks like this
```
  final form = FormGroup({
    incomeAmountLabel: FormControl<String>(
        validators: [Validators.required],
    ),
    frequencyLabel: FormControl<String>(
        validators: [Validators.required]
    ),

    datePaidLabel: FormControl<DateTime>(
        validators: [Validators.required]
    ),

    categoryLabel: FormControl<String>(
        validators: [Validators.required]
    ),

  });
```

my code using reactive dropdown search is as 
```
 return  ReactiveDropdownSearch<String, String>(
      formControlName: frequencyLabel,
      items: ["Weekly", "Bi-Weekly", "Monthly", 'Quarterly', 'Yearly', 'One Time'],
```
but the problem with reactive dropdown search is that i cannot customize it much. I am trying to use drodown search package now but i dont know how to link the drop down search to my form like the code above.  i used the following line:
formControlName: frequencyLabel,.

in dropdown search there is no formControlName parameters.  how can I link my dropdownsearch to my reactive form model?
thanks in advance

**Comment by salim-lachdhaf** [comment]
sadly you cannot related them together, except create a parent form and pass the key to your dropdowns to handle their validation
