### ISSUE TITLE
Selected Item Text Ellipsis

### ISSUE THREAD

**Issue by apripuppey** [salim-lachdhaf/searchable_dropdown#483]
Is there any way to make the selected item overflow ellipsis?  Below is the example.

![image](https://user-images.githubusercontent.com/33617452/192665685-f88d1b2f-c4ca-46b4-8ada-c913e750089a.png)

The red box is the selected item, as you can see it creates a new line when the selected value is exceeding the width of the box. What i want to make is the selected item becomes "TextOverflow.ellipsis" behaviour as seen on the green box (it's a placeholder). By doing this it won't change the box's height.

I tried to search for solutions on the documentation & stackoverflow but i couldn't find one.

Thank you.

**Comment by salim-lachdhaf** [comment]
use `itemBuilder` of `popupProps`.
with `itemBuilder` you can customize the text as you want.

**Comment by apripuppey** [comment]
> `itemBuilder`

Could you please give me an example? I tried to use `itemBuilder` inside of `popupProps` but instead it only changes the the text inside the pop up, not the selected text.

Thank you

**Comment by salim-lachdhaf** [comment]
in this case use `dropdownBuilder` 
take a look to examples pages on git.

**Comment by apripuppey** [comment]
Thank you, it's working now.
