### ISSUE TITLE
Globalkey method is not working

### ISSUE THREAD

**Issue by yusifahmadov** [salim-lachdhaf/searchable_dropdown#484]
Globalkey method is not working. I got a error like this "myKey.currentState.clear() -> currentState is null"

**Comment by salim-lachdhaf** [comment]
is working, please take a look for it's usage here :
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart

**Comment by brianmutiso** [comment]
Probably you are using Int or String instead of your Model Type
  final _openDropDownKey = GlobalKey<DropdownSearchState<Model>>();

**Comment by brianmutiso** [comment]
> Globalkey method is not working. I got a error like this "myKey.currentState.clear() -> currentState is null"

Probably you are using Int or String instead of your Model Type
final _openDropDownKey = GlobalKey<DropdownSearchState>();

**Comment by rednikisfun** [comment]
@brianmutiso Does it have to be my model? The example shows it with `GlobalKey<DropdownSearchState<int>>()`. Shouldn't that work?

**Comment by brianmutiso** [comment]
If you are using a different Type other than int or String then it won't
work
