### ISSUE TITLE
Searchbox Padding

### ISSUE THREAD

**Issue by Badouu** [salim-lachdhaf/searchable_dropdown#485]
Hello,

I'm using the version : dropdown_search: ^5.0.3.
The top padding is  to large. It's look like an issue. How can I manage it ?

Thanks

<img width="411" alt="Capture d’écran 2022-09-28 à 13 17 59" src="https://user-images.githubusercontent.com/32416351/192789923-84971788-f2cf-4f67-a8e0-f11fb0c46ac1.png">

**Comment by salim-lachdhaf** [comment]
in which mode ?

**Comment by Badouu** [comment]
In this mode : PopupPropsMultiSelection.modalBottomSheet

**Comment by salim-lachdhaf** [comment]
use `.bottomSheet` or try to update your Flutter SDK (the issue seems corrected with the last SDK).

**Comment by Badouu** [comment]
Thanks for the quick response. Flutter has been updated. 
It works for Android but not for iOS.

- iOS :
<img width="366" alt="Capture d’écran 2022-09-29 à 01 20 11" src="https://user-images.githubusercontent.com/32416351/192918826-45e148d3-b4b7-454c-bd59-e3a8b2c6e96c.png">

- Android :
<img width="352" alt="Capture d’écran 2022-09-29 à 01 33 24" src="https://user-images.githubusercontent.com/32416351/192918797-2f1fce0a-5e98-46ac-bffa-b9892945c386.png">

**Comment by salim-lachdhaf** [comment]
please past a simple example to analyse the issue

**Comment by Badouu** [comment]
Here is the code :

Widget _customPopupItemBuilderSubActivity(
    BuildContext context,
    SubActivityModel? item,
    bool isSelected,
  ) {
    return Container(
      margin: EdgeInsets.symmetric(horizontal: 8),
      decoration: !isSelected
          ? null
          : BoxDecoration(
              border: Border.all(color: Theme.of(context).primaryColor),
              borderRadius: BorderRadius.circular(5),
              color: Colors.white,
            ),
      child: ListTile(
        selected: isSelected,
        title: Text(item?.name ?? ''),
      ),
    );
  }

DropdownSearch<SubActivityModel>(
            key: _formKey,
            onChanged: (value) {
              if (value != null) {
                print(value.name);
                setState(() {
                  personalInformationData!['domainActivity'] =
                      value.code as String;
                  personalInformationValidation['domainActivity'] = false;
                });
              }
            },
            asyncItems: (String? filter) async {
              return await _subActivities;
            },
            popupProps: PopupPropsMultiSelection.bottomSheet(
              showSelectedItems: true,
              itemBuilder: _customPopupItemBuilderSubActivity,
              showSearchBox: true,
            ),
            compareFn: (item, sItem) {
              return item.name == sItem.name;
            },
            dropdownDecoratorProps: DropDownDecoratorProps(
              dropdownSearchDecoration: InputDecoration(
                labelText: 'Activité *',
                errorText: personalInformationValidation['domainActivity']
                        as bool
                    ? RegisterPersonnalDataValidator.domainActivity(
                        personalInformationData!['domainActivity'] as String)
                    : null,
                filled: true,
                fillColor: Colors.white,
                contentPadding: EdgeInsets.only(left: 0, top: 13, bottom: 15),
              ),
            ),
          ),

**Comment by Badouu** [comment]
Here is the code :

```dart
Widget _customPopupItemBuilderSubActivity(
    BuildContext context,
    SubActivityModel? item,
    bool isSelected,
  ) {
    return Container(
      margin: EdgeInsets.symmetric(horizontal: 8),
      decoration: !isSelected
          ? null
          : BoxDecoration(
              border: Border.all(color: Theme.of(context).primaryColor),
              borderRadius: BorderRadius.circular(5),
              color: Colors.white,
            ),
      child: ListTile(
        selected: isSelected,
        title: Text(item?.name ?? ''),
      ),
    );
  }

DropdownSearch<SubActivityModel>(
            key: _formKey,
            onChanged: (value) {
              if (value != null) {
                print(value.name);
                setState(() {
                  personalInformationData!['domainActivity'] =
                      value.code as String;
                  personalInformationValidation['domainActivity'] = false;
                });
              }
            },
            asyncItems: (String? filter) async {
              return await _subActivities;
            },
            popupProps: PopupPropsMultiSelection.bottomSheet(
              showSelectedItems: true,
              itemBuilder: _customPopupItemBuilderSubActivity,
              showSearchBox: true,
            ),
            compareFn: (item, sItem) {
              return item.name == sItem.name;
            },
            dropdownDecoratorProps: DropDownDecoratorProps(
              dropdownSearchDecoration: InputDecoration(
                labelText: 'Activité *',
                errorText: personalInformationValidation['domainActivity']
                        as bool
                    ? RegisterPersonnalDataValidator.domainActivity(
                        personalInformationData!['domainActivity'] as String)
                    : null,
                filled: true,
                fillColor: Colors.white,
                contentPadding: EdgeInsets.only(left: 0, top: 13, bottom: 15),
              ),
            ),
          ),
```

**Comment by emrgry** [comment]
I've got same issue can anyone solved this?

**Comment by iam-amanxz** [comment]
Facing the same issue, any update on this?

**Comment by iam-amanxz** [comment]
I thaught it might be the container, but it's something else.

```
popupProps: PopupProps.modalBottomSheet(
  containerBuilder: (context, popupWidget) {
    return Container(
      color: Colors.redAccent,
      child: popupWidget,
    );
  },
),
```

<img src="https://user-images.githubusercontent.com/50168544/205276483-1e4c27b2-ca28-4894-bf38-0e4df3cc0901.PNG" width="200"/>

**Comment by manueltag** [comment]
I did some tests and the problem seems to be related to the margin applied to the ModalBottomSheet container:

```
return Container(
   margin: EdgeInsets.only(
     bottom: viewInsetsBottom,
     top: viewPaddingTop,
   ),
   child: _popupWidgetInstance(),
);
```

The widget is displayed correctly by removing the margin.
