### ISSUE TITLE
_userEditTextController needs any dispose method

### ISSUE THREAD

**Issue by yakupbaser** [salim-lachdhaf/searchable_dropdown#486]
Hi, thanks for your wonderful package. I take an error like that:

`A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.`

I think it needs a dispose method for textEditingController.dispose()

`      popupProps: PopupPropsMultiSelection.modalBottomSheet(
                        showSelectedItems: true,
                        itemBuilder: _customPopupItemBuilderExample2,
                        showSearchBox: true,
                        searchFieldProps: TextFieldProps(
                          controller: _userEditTextController,
                          decoration: InputDecoration(
                            suffixIcon: IconButton(
                              icon: Icon(Icons.clear),
                              onPressed: () {
                                _userEditTextController.clear();
                              },
                            ),
                          ),
                        ),
                      ),`

**Comment by salim-lachdhaf** [comment]
the controller is disposed well. please make sure that you are not using it after dismissing the popup .
https://github.com/salim-lachdhaf/searchable_dropdown/blob/9f1b1d67b62a2a6f23caf520c4fb078f02027312/lib/src/widgets/selection_widget.dart#L86

**Comment by Nandhinidevi123** [comment]
i tried to dispose the controller its not working if any other solution for this issuse

**Comment by dgross881** [comment]
@salim-lachdhaf this can be duplicated on the example app in  [DropdownSearchBuidler examples] when triggered onDismiss 

```
The following assertion was thrown building Container(margin:
EdgeInsets(0.0, 24.0, 0.0, 0.0)):
A TextEditingController was used after being disposed.
Once you have called dispose() on a TextEditingController, it can no
longer be used.
```

it seems to only happen if the search field props  controller is present

```
searchBoxController = widget.popupProps.searchFieldProps.controller ??
        TextEditingController();

```
