### ISSUE TITLE
Item not removed from multiselection 

### ISSUE THREAD

**Issue by NafissaBHJ** [salim-lachdhaf/searchable_dropdown#487]
**Describe the bug**
when adding mutliple items, they get removed when removed from the check box but not when removed from the items list  the X next to the item

**To Reproduce**
1. select items
2.  click on the "x" near the item selected 
3. it is deleted from ui but no way to delete it from  the list 

**Expected behavior**
it get removed from list 

![20221001_202821](https://user-images.githubusercontent.com/20068041/193425282-f9606afd-3dfd-4563-ac0d-f65f37fceba7.jpg)

**Comment by salim-lachdhaf** [comment]
it's not an issue.

the two lists are not related until you validate your selection from the popup list. which means changes in the popup list are temporary and does not effect the dropdown list while you are not validate the selected items.
same thing for dropdown selected item.

**Comment by NafissaBHJ** [comment]
But in the dropdown list I can implement something in OnremoveItem , but  for the items that appear above I can't find where to remove items. The "X" is irrelevent as it remove the item from appearing but not from being selected.
Is there a way to remove the 'X' sign ?

**Comment by salim-lachdhaf** [comment]
`onRemoveItem` is popup property.
for the 'x' it will be in `onChange`
to customize 'x' use `clearButtonProps`
