### ISSUE TITLE
Question??

### ISSUE THREAD

**Issue by AgustinOMG** [salim-lachdhaf/searchable_dropdown#488]
Firts thank you for the amazing work, this widget is amazing, adn i really like it. This is not quite an issue but rather a question.
I want the dropdown to loose the selection when I update some information, but i just cant find how to this this except with the clearButtonProps.

Any advice on how to accomplish this.

Thank you very much 

Best regards

**Comment by salim-lachdhaf** [comment]
https://github.com/salim-lachdhaf/searchable_dropdown/issues/421
