### ISSUE TITLE
Double scrollbars on desktop platforms. Scrollbar position is incorrect in dialog.

### ISSUE THREAD

**Issue by slavap** [salim-lachdhaf/searchable_dropdown#489]
![image](https://user-images.githubusercontent.com/4129763/194459149-cc47c982-7c57-4ef6-928b-707a11a2f32a.png)

![image](https://user-images.githubusercontent.com/4129763/194460760-ebd7ac8f-47f3-41f0-9f52-71b6610fe4f7.png)

1. Double scrollbar on desktop platforms, see https://github.com/flutter/flutter/issues/99724
    In short: ListView.builder() must be wrapped with ScrollConfiguration and behavior has to be available in listViewProps
```dart
    child: ScrollConfiguration(
                    behavior: ScrollConfiguration.of(context).copyWith(scrollbars: false),
                    child: ListView.builder(
```

2. Invalid scrollbar position in dialog caused by overall layout structure in SelectionWidgetState.
    Container(constraints: widget.popupProps.constraints) -> ValueListenableBuilder() -> Column(crossAxisAlignment: CrossAxisAlignment.stretch) -> Flexible() -> Stack() -> StreamBuilder() -> RawScrollbar() -> ListView.builder()

In version 5 it is different from version 4 (were Stack was on top instead of Container), and in version 4 scrollbar position was correct.

**UPDATE for problem 2:** I did the investigation of my code and found out that incorrect scrollbar position only occurs in case when I have adjusted MediaQuery on the top of my widget tree:
```dart
MediaQueryData d = MediaQuery.of(context);
d = d.copyWith(padding: EdgeInsets.fromLTRB(100, d.padding.top, 100, d.padding.bottom));
return MediaQuery(data: d, child: MyPage1());
```
So somehow this "global" padding affects scrollbar position in dropdown (which is placed much much lower in the widget tree).

**Comment by CabraKill** [comment]
A temporary solution was adding the color using the Theme widget as a parent to the DropdownSearch.

```dart
scrollbarTheme: const ScrollbarThemeData(
          thumbColor: MaterialStatePropertyAll(
            Colors.transparent,
          ),
        )
```

This way we stick to only one scrollbar which may help.

**Comment by salim-lachdhaf** [comment]
I consider this issue as Flutter issue and not package issue.

**Comment by satvikpendem** [comment]
I just made everything invisible and non-interactive:

```dart
scrollbarProps: ScrollbarProps(
  interactive: false,
  trackVisibility: false, // may not be required to be set
  thumbVisibility: false, // may not be required to be set
  trackColor: Colors.transparent,
  thumbColor: Colors.transparent,
),
```

It seems like if `track/thumbColor` is transparent then the `track/thumbVisibility` don't do anything, not sure though.
