### ISSUE TITLE
How to validate form field

### ISSUE THREAD

**Issue by vrajshah24** [salim-lachdhaf/searchable_dropdown#491]
DropdownSearch<Map<int, String>>(
                          key: party,
                         
                          popupProps: PopupProps.menu(showSearchBox: true
                              // showSelectedItems: true,
                              ),
                          dropdownDecoratorProps: DropDownDecoratorProps(
                            dropdownSearchDecoration: InputDecoration(
                                label: Text('Select Party'),
                                contentPadding:
                                    EdgeInsets.fromLTRB(10, 1, 0, 20),
                                border: InputBorder.none,
                                floatingLabelBehavior:
                                    FloatingLabelBehavior.never),
                          ),
                          items: clientlist,
                          itemAsString: (item) {
                            String b = item.values.toString();
                            return b.substring(1, b.length - 1);
                          },
                          onChanged: ((value) {
                            String b = value!.keys.toString();
                            dropdownvalueforclient =
                                b.substring(1, b.length - 1);
                          }),
                        ))

**Comment by vrajshah24** [comment]
This is my code i just wanted to know how to validate my data in the normal dropdown of single key pair value

**Comment by salim-lachdhaf** [comment]
what do you lean by validate data

**Comment by salim-lachdhaf** [comment]
no reply.
