### ISSUE TITLE
multiSelection - empty value issue

### ISSUE THREAD

**Issue by doronnahum** [salim-lachdhaf/searchable_dropdown#492]
**Describe the bug**
When the "selectedItems" is empty list the screen is not loaded

**To Reproduce**
Run this code:
DropdownSearch<int>.multiSelection(
        items: [1, 2, 3, 4, 5, 6, 7],
        selectedItems: [],
      )

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Mac
 - Browser :  chrome Version 106.0.5249.103

**Additional context**
Verions dropdown_search: ^5.0.3

**Comment by salim-lachdhaf** [comment]
tested => there is no issue.
