### ISSUE TITLE
Documentation Code Samples Outdated

### ISSUE THREAD

**Issue by septianrazi** [salim-lachdhaf/searchable_dropdown#493]
Hi,

Thanks again for making this package. I've had some trouble actually figuring out how to use this properly, especially the search functionality. I was initially just trying to use the code on the README.md, but I believe the code snippets are out of date with the new updates.

Might be a good idea to update the code snippets to reflect the changes in the DropdownSearch fields with the new updates.

eg:
```
DropdownSearch<UserModel>(
    popupProps: PopupProps.bottomSheet(),
    dropdownSearchDecoration: InputDecoration(labelText: "Name"),
    asyncItems: (String filter) => getData(filter),
    itemAsString: (UserModel u) => u.userAsString(),
    onChanged: (UserModel? data) => print(data),
)
```
which is shown on the README does not compile on the newest version 5.0.3.

**Comment by salim-lachdhaf** [comment]
it's a correct. just you have to add UserModel entity.
dont hesitate to take a look to examples page :
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart
