### ISSUE TITLE
Customize display of selected items

### ISSUE THREAD

**Issue by laurafiorini** [salim-lachdhaf/searchable_dropdown#494]
Hey,

First of all, the package is very nice and just what I needed! 

But I am having trouble customizing how the selected items are displayed. In my case, this is what I get:

![image](https://user-images.githubusercontent.com/56408459/195849087-0726ec10-b854-44ce-adb0-4df553d84668.png)

I wanted to change the text color of the selected icons to white, since it's hard to see because of the contrast. Or change the background color to a lighter blue. Is there a way I can do that without changing my app's theme?

**Comment by salim-lachdhaf** [comment]
use `dropdownBuilder.`
