### ISSUE TITLE
How to change the font size?

### ISSUE THREAD

**Issue by sergdeus** [salim-lachdhaf/searchable_dropdown#496]
Hi! I need to change the font size (image).

When I try to use 

```
DropDownDecoratorProps(
        dropdownSearchDecoration: InputDecoration(
          labelStyle: TextStyle(fontSize: 10),
          floatingLabelStyle: TextStyle(fontSize: 10),
          hintStyle: TextStyle(fontSize: 10),
          counterStyle: TextStyle(fontSize: 10),
          helperStyle: TextStyle(fontSize: 10),
          prefixStyle: TextStyle(fontSize: 10),
          suffixStyle: TextStyle(fontSize: 10),
          filled: true,
```

it doesn't change the font-size.

The package version dropdown_search: ^5.0.3

<img width="385" alt="Screenshot 2022-10-17 at 12 37 00" src="https://user-images.githubusercontent.com/97783552/196144867-1be17dcd-b07f-4be1-a2f4-7df939c395b1.png">

**Comment by salim-lachdhaf** [comment]
use `dropdownBuilder` .
