### ISSUE TITLE
how to prevent changes in dropdown search?

### ISSUE THREAD

**Issue by tal-72** [salim-lachdhaf/searchable_dropdown#497]
I have a scenario. I need to change selected value in dropdown upon confirmation of user. Like if I have selected a value from dropdown list it ask confirmation msg from user. If user selects yes it should update the value but if user selects no it should not change dropdown value.. But in my case, it update value if i select No. Any help in this regard.

**Comment by salim-lachdhaf** [comment]
you can use `onBeforeChange`.
don't hesitate to take a look to examples page
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart

**Comment by tal-72** [comment]
ok thank you!
