### ISSUE TITLE
dropdownBuilderSupportsNullItem

### ISSUE THREAD

**Issue by lequyha** [salim-lachdhaf/searchable_dropdown#499]
I do not see dropdownBuilderSupportsNullItem in dropdown_search 5.0.3. Can you help me? thanks.

Update: I saw you rm in changelog. My question is how can I show label (not label text) because I have * in my label text and i want change it to red color.

**Comment by salim-lachdhaf** [comment]
there is no more need to dropdownBuilderSupportsNullItem after the migration to nullSafety.
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/CHANGELOG.md#400---20220516

use `nullable` object exemple `int?` instead of `int`.
