### ISSUE TITLE
Dark mode visual problems

### ISSUE THREAD

**Issue by slavap** [salim-lachdhaf/searchable_dropdown#5]
1. Default value for popupBackgroundColor should be Theme.of(context).dialogBackgroundColor
2. Clear and Dropdown buttons icon color should not be Colors.black54, something like:
```dart
color: Theme.of(context).brightness == Brightness.dark ? Colors.white54 : Colors.black54
```

**Comment by salim-lachdhaf** [comment]
Nice suggession, This will be improved in the next pub.

**Comment by slavap** [comment]
@salim-lachdhaf Minor clarification, by default Flutter uses black54 and white70.
See https://www.didierboelens.com/2020/05/material-textstyle-texttheme/

**Comment by salim-lachdhaf** [comment]
Yes, they are applied automatically, we don't have to specify them, this colors are handled by the theme itself.
