### ISSUE TITLE
'AutovalidateMode' not found.

### ISSUE THREAD

**Issue by bynalab** [salim-lachdhaf/searchable_dropdown#50]
../../../../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-0.4.5/lib/dropdown_search.dart:115:9: Error: Type 'AutovalidateMode' not found.
  final AutovalidateMode autoValidateMode;
        ^^^^^^^^^^^^^^^^
../../../../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-0.4.5/lib/dropdown_search.dart:115:9: Error: 'AutovalidateMode' isn't a type.
  final AutovalidateMode autoValidateMode;
        ^^^^^^^^^^^^^^^^
../../../../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-0.4.5/lib/dropdown_search.dart:148:29: Error: Getter not found: 'AutovalidateMode'.
    this.autoValidateMode = AutovalidateMode.disabled,
                            ^^^^^^^^^^^^^^^^

../../../../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-0.4.5/lib/dropdown_search.dart:253:7: Error: No named parameter with the name 'autovalidateMode'.
      autovalidateMode: widget.autoValidateMode,
      ^^^^^^^^^^^^^^^^

../../../../../dev/flutter/packages/flutter/lib/src/widgets/form.dart:282:9: Context: Found this candidate, but the arguments don't match.
  const FormField({
        ^^^^^^^^^

This is my code (I am using the example code):

 DropdownSearch<String>(
                mode: Mode.MENU,
                showSelectedItem: true,
                items: ['Brazil', 'Italia (Disabled)', 'Tunisia', 'Canada'],
                label: 'Menu mode',
                hint: 'country in menu mode',
                popupItemDisabled: (String s) => s.startsWith('I'),
                onChanged: print,
                selectedItem: 'Brazil',
),

**Comment by salim-lachdhaf** [comment]
As mentionned @ggaj sadly it's a breaking changes on version 0.4.5.
