### ISSUE TITLE
Can keep search box inside dropdown itself, instead of dropdown option above.

### ISSUE THREAD

**Issue by abhiBirwa** [salim-lachdhaf/searchable_dropdown#500]
![Screenshot from 2022-10-27 14-50-17](https://user-images.githubusercontent.com/57979114/198253183-8ddcb706-a6be-47e4-ad56-299b7e2d6e99.png)

**Comment by salim-lachdhaf** [comment]
i didn't try it before but it's not impossible.
use `dropdownBuilder` to change widget to `textField`, and use serach field controller to update to search query...
