### ISSUE TITLE
Autofocus Textfield in search box when Dropdown is opened

### ISSUE THREAD

**Issue by deivit21** [salim-lachdhaf/searchable_dropdown#501]
I'm always frustrated that, when I click on the DropdownSearch button in order to search something, I have to click on the textfield before typing. 

It would be better if this button had an option to control the autofocus of the textfield, in order to write directly in the textfield when the Dropdown is opened without having to click on it. It's faster and more intuitive.

When you open the dropdown button you would see the textfield focused like this:

![DropdownSearch](https://user-images.githubusercontent.com/83778863/198315414-3efe11a7-c663-4b29-ade7-3cdffe220415.PNG)

**Comment by vrajshah24** [comment]
I found a solution for your question:

showSearchBox: true,
searchFieldProps: TextFieldProps(autofocus: true) 

Paste this code inside PopupProps.menu

**Comment by salim-lachdhaf** [comment]
thanks @vrajshah24 .
