### ISSUE TITLE
Space between the menu button and the container

### ISSUE THREAD

**Issue by PavieOlivier** [salim-lachdhaf/searchable_dropdown#502]
I would like to have a space between the drop-down button and the popup menu like this picture;
What option do I need to change please?

<img src="https://github.com/salim-lachdhaf/searchable_dropdown/raw/master/screenshots/ex4.png?raw=true" width="250"/>

**Comment by salim-lachdhaf** [comment]
you can use `positionCallback` of `menuProps`.

**Comment by seshaipro** [comment]
Unable to find proper code for `positionCallback `in Examples. Can you explain a bit more clear.
