### ISSUE TITLE
Base Style on DropDownDecoratorProps doesn't works

### ISSUE THREAD

**Issue by urielexis64** [salim-lachdhaf/searchable_dropdown#503]
**Describe the bug**
Using baseStyle property on DropDownDecoratorProps doesn't have any effect.

**To Reproduce**
Set a TextStyle to DropDownDecoratorProps baseStyle property

**Expected behavior**
Text should be red color

**Screenshots**
![image](https://user-images.githubusercontent.com/47485144/199293700-c65df92a-719a-464b-8af9-31c1ffd2de1b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by salim-lachdhaf** [comment]
please take a look here:
https://github.com/salim-lachdhaf/searchable_dropdown/issues/439
