### ISSUE TITLE
how to send the data selected from the list

### ISSUE THREAD

**Issue by DanielCamaja** [salim-lachdhaf/searchable_dropdown#504]
How can I send the data I select to a database, or at least in a "print" that the data I select appear

`        

            DropdownSearch<UserModel>(
              asyncItems: (String? filter) => getData(filter),
              popupProps: PopupPropsMultiSelection.modalBottomSheet(
                showSelectedItems: true,
                itemBuilder: _customPopupItemBuilderExample2,
                showSearchBox: true,
              ),
              compareFn: (item, selectedItem) =>
                  item.etiqueta == selectedItem.etiqueta,
              dropdownDecoratorProps: DropDownDecoratorProps(
                dropdownSearchDecoration: InputDecoration(
                  labelText: 'Equipo',
                  filled: true,
                  fillColor: Theme.of(context).inputDecorationTheme.fillColor,
                ),
              ),
            ),

`

**Comment by salim-lachdhaf** [comment]
use `onChange` function.
please don't hesitate to take a look to examples page.
