### ISSUE TITLE
Prevent search not deleted

### ISSUE THREAD

**Issue by ariefsn** [salim-lachdhaf/searchable_dropdown#513]
**Describe the bug**
How to prevent search value after select item?

**To Reproduce**
1. Open
2. Type some text to search box
3. Select item
4. Popup closed, and the text that I typed before was cleared

**Expected behavior**
When I open again, should show the last search text

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android
 - Browser: stock browser
 - Version: 5.0.3

**Comment by salim-lachdhaf** [comment]
you can simply use TextEditingController like this :
```
popupProps: PopupProps.menu(
      searchFieldProps: TextFieldProps(
             **controller: yourController**
      )
)
```
