### ISSUE TITLE
Simple question (bug?) on border color adjustments

### ISSUE THREAD

**Issue by kevan-mtl** [salim-lachdhaf/searchable_dropdown#517]
hi,
First of all thank you for this awesome package!

Simple question: Is there a way to get rid of this weird blue line on top of the ListView right above the word "English" (it's there even when the  options are not shown). I search all the properties but I wasn't able to locate a way to change this... Thanks in advance!

<img width="212" alt="Screen Shot 2022-12-04 at 12 09 59 AM" src="https://user-images.githubusercontent.com/25143586/205475646-d7feb5a7-d442-49c9-a36a-656e3bf44396.png">

**Comment by salim-lachdhaf** [comment]
You have two options to manage that , simply by using `dropdownDecoratorProps` or override the hole dropdown using `dropdownBuilder`

**Comment by salim-lachdhaf** [comment]
this could help either https://github.com/salim-lachdhaf/searchable_dropdown/issues/439

**Comment by kevan-mtl** [comment]
thanks @salim-lachdhaf ! Indeed, here is what was needed:

`DropDownDecoratorProps(
          dropdownSearchDecoration:
              InputDecoration(enabledBorder: InputBorder.none))`
