### ISSUE TITLE
Breaking changes but only fix version bump

### ISSUE THREAD

**Issue by nstrelow** [salim-lachdhaf/searchable_dropdown#52]
According to semantic versioning any package with a 0.x.x as version number does not have a stable API.

Still it was very annoying for me to have a different package break, because a breaking change was introduced between 0.4.4 and 0.4.5:
https://github.com/danvick/flutter_form_builder/issues/507

The maintainer set the package version to: `dropdown_search: ^0.4.4` which should fetch all new packages 0.x.x for minor and fix changes, but not breaking.

Could you please use a major version bump if you introduce breaking changes? 1.0.0 and 2.0.0 and so on

here the official semantic versioning spec.
https://semver.org/

**Comment by salim-lachdhaf** [comment]
We are sorry for the issue, and greatfull for the information
