### ISSUE TITLE
Unable to center text

### ISSUE THREAD

**Issue by qq464418017** [salim-lachdhaf/searchable_dropdown#520]
DropdownSearch(
              popupProps: PopupProps.menu(
                textStyle: TextStyle(color: Colors.yellow),
                menuProps: MenuProps(
                  backgroundColor: Colors.orange,
                  textStyle: TextStyle(color: Colors.yellow),
                ),
              ),
              items: [1, 2, 3],
              dropdownDecoratorProps: DropDownDecoratorProps(
               textAlign: TextAlign.center,
                baseStyle: TextStyle(color: Colors.yellow),
                dropdownSearchDecoration: InputDecoration(
                  hintText: "hint",
                  hintStyle: TextStyle(color: Colors.green, fontStyle: FontStyle.italic),
                  border: OutlineInputBorder(borderSide: BorderSide(color: Colors.blue, width: 2)),
                ),
              ),
            )

**Comment by salim-lachdhaf** [comment]
are you using the last version ?

**Comment by qq464418017** [comment]
> 你在使用最后一个版本吗？

no,  I am using 5.0.3.

**Comment by salim-lachdhaf** [comment]
use the last version 5.0.5.
