### ISSUE TITLE
Checkbox at left side

### ISSUE THREAD

**Issue by xakeppok** [salim-lachdhaf/searchable_dropdown#522]
Hi. I m using this great package in my project and it really great.
I know it's duplicate #458. But i did't see the solution there.
My question is how can i set checkbox at left side in MultiSelect mode.

**Comment by lachesse** [comment]
Hi
any updates?

**Comment by salim-lachdhaf** [comment]
a new property `textDirection` for `popupProps` is added to handle that.

check the new version 5.0.6. (will be released today)

**Comment by xakeppok** [comment]
Hi. In this case it's mirroring the whole control.

**Comment by xakeppok** [comment]
any other solutions?

**Comment by salim-lachdhaf** [comment]
could paste an example image of what you wanted exactly ?

**Comment by xakeppok** [comment]
@salim-lachdhaf 
https://imgur.com/a/RMK09SI
i need these checkbox at left side

**Comment by xakeppok** [comment]
any updates?
