### ISSUE TITLE
Error: No named parameter with the name 'style'.

### ISSUE THREAD

**Issue by praveen0308** [salim-lachdhaf/searchable_dropdown#523]
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dropdown_search-5.0.5/lib/dropdown_search.dart:476:13: Error: No named parameter with the name 'style'.
            style: widget.clearButtonProps.style,
            ^^^^^
/C:/flutter_sdks/flutter/packages/flutter/lib/src/material/icon_button.dart:117:9: Context: Found this candidate, but the arguments don't match.
  const IconButton({
        ^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dropdown_search-5.0.5/lib/dropdown_search.dart:501:13: Error: No named parameter with the name 'style'.
            style: widget.dropdownButtonProps.style,
            ^^^^^
/C:/flutter_sdks/flutter/packages/flutter/lib/src/material/icon_button.dart:117:9: Context: Found this candidate, but the arguments don't match.
  const IconButton({
        ^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter_sdks\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter_sdks\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by salim-lachdhaf** [comment]
please sdk's versions for dart and flutter

**Comment by xbacon14** [comment]
> 

 Flutter (Channel stable, 3.0.5, on Microsoft Windows [Versi¢n 10.0.22000.1335], locale es-PY)
 Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "windows_x64"

**Comment by tuannvm-citigo** [comment]
I have same problem with
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (5 months ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

**Comment by ashimsaini** [comment]
any solution for this?

**Comment by tuannvm2109** [comment]
Downgrade version in pubspec.yaml to **dropdown_search: 5.0.3** solve this (it must be 5.0.3 not ^5.0.3)

**Comment by salim-lachdhaf** [comment]
please make sure that you using the lasstest versions of Flutter SDK, dropdown_search
