### ISSUE TITLE
dropdownButtonProps isVisiable bug

### ISSUE THREAD

**Issue by aljaff94** [salim-lachdhaf/searchable_dropdown#524]
when hiding dropdownButtonProps by setting is visible to false it still take some space
how can i hide it and using all available width

<img width="2198" alt="Screenshot 2022-12-17 at 5 37 35 AM" src="https://user-images.githubusercontent.com/5650955/208219812-db4014e9-2a07-480f-a63f-09bdd4a3723b.png">

<img width="2271" alt="Screenshot 2022-12-17 at 5 55 10 AM" src="https://user-images.githubusercontent.com/5650955/208220513-c039c2c7-b844-4d83-baff-41e4122ef747.png">

**Comment by gowda-nirmal** [comment]
I am facing the same issue. How did you fix this?
