### ISSUE TITLE
Can we have styling examples?

### ISSUE THREAD

**Issue by mariopepe** [salim-lachdhaf/searchable_dropdown#525]
Styling is extremely complex, props are deeply nested, and they are not easy to edit.

Can we have styling examples like the ones shown on the repo?

Thanks

<img width="644" alt="image" src="https://user-images.githubusercontent.com/14803862/208381941-1202c4b0-db3f-424c-aaaa-724b4582a59e.png">

**Comment by salim-lachdhaf** [comment]
i will work on that once i got time.

**Comment by fabioselau077** [comment]
> i will work on that once i got time.

any update? thx
