### ISSUE TITLE
Selected items overflow Multiselection Dropdown

### ISSUE THREAD

**Issue by FelipeEmos** [salim-lachdhaf/searchable_dropdown#526]
**Describe the bug**
Dropdowns with multiSelection overflow the layout.

**To Reproduce**
1. Create a `DropdownSearch.multiSelection` with many  items
2. Put this Dropdown inside a container with reasonable but limited space
3. Select all the items
4. Observe how the items go outside the Dropdown bar

The following code reproduces the bug

``` dart
@override
Widget build(BuildContext context) {
  return Container(
    height: 100,
    width: 400,
    child: DropdownSearch.multiSelection(
      items: const [
        'Avocado',
        'Banana',
        'Cashew',
        'Damasco',
        'Eggplant',
        'Fig',
      ],
    ),
  );
}
```

**Expected behavior**
I believe the items inside the dropdown should be clipped by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/10969700/209001004-d821e2b3-6204-4f14-851d-9d48922d30a3.png)
![image](https://user-images.githubusercontent.com/10969700/209001022-f360cea6-53f1-43d4-9c62-d1c577fc25c1.png)

**Desktop (please complete the following information):**
 - OS: linux ( but I'm pretty sure this will happen in all platforms )

**Additional context**

**Comment by brux88** [comment]
i have the same problem
