### ISSUE TITLE
How to open Dropdown Search (Bottomsheet) using onclick /ontap

### ISSUE THREAD

**Issue by abu0435** [salim-lachdhaf/searchable_dropdown#53]
I am trying to open dropdown bottomsheet search , when onclick/ontap in button. I dont know exactly how to integrate it

**Comment by salim-lachdhaf** [comment]
You mean open it programmatically ? If yes, this feature will be available in the next version which will be released soon

**Comment by ckrc** [comment]
Hi @salim-lachdhaf 

I think this feature is already available on version 0.4.8. Could you please provide example of how to programmatically open the dropdown (bottomsheet)?

**Comment by salim-lachdhaf** [comment]
you can open it like this:
`openDropDownProgKey.currentState.openDropDownSearch()`
where `openDropDownProgKey` is a `GlobalKey()`.

for now we do not have a feature to tell you if the dropdown is opened or not. maybe will be in the next feature.
