### ISSUE TITLE
Can i change the color of items in list from black to something else?

### ISSUE THREAD

**Issue by tal-72** [salim-lachdhaf/searchable_dropdown#530]
Hello there, first of all package is very nice. 
I want to change the color of items in in list from black to some other color. I repeat, not selected item color, but the color of all the items in the list?

Is there a way i can do that?

Thanks in advance.

**Comment by erenkaraboga** [comment]
same issue and ı want change font too

**Comment by tal-72** [comment]
> same issue and ı want change font too

i have found a solution for this. you can use itemBuilder for this.

code for reference
 itemBuilder: (context, item, isSelected) => Container(
              padding: EdgeInsets.all(8),
              child: Text(
                item.toString(),
                style: TextStyle(color: Colors.green, fontSize: 20),
              ),
            ),

**Comment by salim-lachdhaf** [comment]
hi @tal-72 , yes , it's the correct way to update popup items ;) .
