### ISSUE TITLE
Suffix Icon added in dropdownSearchDecoration is not displayed 

### ISSUE THREAD

**Issue by ask-mdn** [salim-lachdhaf/searchable_dropdown#536]
Custom suffix icon added in dropdownSearchDecoration is not displayed in latest version. I was using version 2.0.1 and suffix icon was working, but when I updated to latest version and now custom suffix icon is not displayed. 

**Suffix icon displayed in version 2.0.1:**

    return Scaffold(
      appBar: AppBar(title: Text("DropdownSearch Demo")),
      body: Padding(
        padding: const EdgeInsets.all(25),
        child: Form(
          key: _formKey,
          autovalidateMode: AutovalidateMode.onUserInteraction,
          child: Expanded(
            child: DropdownSearch<int>(
              mode: Mode.DIALOG,
              items: [1, 2, 3, 4, 5, 6, 7],
                dropdownSearchDecoration: InputDecoration(
                  hintText: "Select an Int",
                  prefixIcon: Padding(
                    padding: EdgeInsets.only(left: 24, right: 24),
                    child: Icon(Icons.filter_list_outlined),
                  ),
                  suffixIcon: Padding(
                    padding: EdgeInsets.only(left: 24, right: 24),
                    child: CloseButton(
                      onPressed: () {
                        // Close the dropdown search
                      },
                    ),
                  ),
                ),
            ),
          ),
        ),
      ),
    );
 

**Suffix icon displayed in version 5.0.5:**

    return Scaffold(
      appBar: AppBar(title: Text("DropdownSearch Demo")),
      body: Padding(
        padding: const EdgeInsets.all(25),
        child: Form(
          key: _formKey,
          autovalidateMode: AutovalidateMode.onUserInteraction,
          child: Expanded(
            child: DropdownSearch<int>(
              items: [1, 2, 3, 4, 5, 6, 7],
              dropdownDecoratorProps: DropDownDecoratorProps(
                dropdownSearchDecoration: InputDecoration(
                  hintText: "Select an Int",
                  prefixIcon: Padding(
                    padding: EdgeInsets.only(left: 24, right: 24),
                    child: Icon(Icons.filter_list_outlined),
                  ),
                  suffixIcon: Padding(
                    padding: EdgeInsets.only(left: 24, right: 24),
                    child: CloseButton(
                      onPressed: () {
                        // Close the dropdown search
                      },
                    ),
                  ),
                ),
              ),
              clearButtonProps: ClearButtonProps(isVisible: true),
              popupProps: PopupProps.dialog()
            ),
          ),
        ),
      ),
    );
  

**Screenshots**
Version 2.0.1
![Screenshot_20230125-105725](https://user-images.githubusercontent.com/97338818/214487616-02ce1546-0dae-47d2-a399-0b89aae2db40.jpg)

Version 5.0.5
![Screenshot_20230125-105517](https://user-images.githubusercontent.com/97338818/214487623-6fd3b195-4983-48ec-b0a4-5b764792cd41.jpg)

**Comment by salim-lachdhaf** [comment]
Yes that's correct, it's a breaking change.
in 2.0.1 we have `showAsSuffixIcons` (if you set it to `true` you will get the same result as 5.0.5). But in the v5 we deleted `showAsSuffixIcons` and the trailing icons are always as suffix icons.

to added extra icons as suffix you can use `dropdownBuilder` to customize freely your dropdown.

**Comment by ronytesler** [comment]
So why is the property still there? and why 'icon' is shown but 'suffixIcon' is not..

**Comment by Prathap-Aosta** [comment]
I'm added the icon inside the dropdownBuilder, It's working fine for me

// Custom dropdownBuilder to display the selected item with a trailing dropdown icon.
// This gives full control over layout, styling, and avoids issues with suffixIcon.

`dropdownBuilder: (context, selectedItem) {
  return Row(
    mainAxisAlignment: MainAxisAlignment.start,
    children: [
      // Text with ellipsis for long labels
      Flexible(
        child: Text(
          selectedItem ?? "Select an option",
          style: const TextStyle(
            color: Colors.black,
            overflow: TextOverflow.ellipsis,
          ),
          maxLines: 1,
        ),
      ),
      const Icon(
        Icons.keyboard_arrow_down,
        color: Colors.black,
      ),
    ],
  );
},
`
