### ISSUE TITLE
i want itemDialog always open below dropdownsearch field

### ISSUE THREAD

**Issue by HemangSidapara** [salim-lachdhaf/searchable_dropdown#538]
I have issue with, when i open itemMenu then it will overlap the dropdownsearch field(when field is bottom of the screen) but i want it always open below the field.

here is the video, you will get the issue:

https://user-images.githubusercontent.com/61095579/215013778-47edd861-bbcf-4a32-bdf5-49bb4e1397f8.mp4

**Comment by salim-lachdhaf** [comment]
it's not an issue, there is no space, the menu forced to move up. it's the same behavior of flutter dropdown

**Comment by HemangSidapara** [comment]
@salim-lachdhaf so, there is anyway to move screen with dropdown?
