### ISSUE TITLE
 Unhandled Exception: Bad state: Cannot add event after closing

### ISSUE THREAD

**Issue by farismohammed** [salim-lachdhaf/searchable_dropdown#55]
Throwing an exception  **Unhandled Exception: Bad state: Cannot add event after closing**,  when closing dropdown before future completes,

**Comment by salim-lachdhaf** [comment]
Could you please past an example for the issue and describe the scenario to reproduce the problem

**Comment by farismohammed** [comment]
When the user opens the future filter dropdown and pops it immediately before the current future completes, The dropdown is popped out, but the future complete after the dropdown closed, that time this exception is thrown. like below...


Restarted application in 1,058ms.
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Bad state: Cannot add event after closing
#0      _StreamController.addError (dart:async/stream_controller.dart:633:24)
#1      _SelectDialogState.manageItemsByFilter
package:dropdown_search/src/selectDialog.dart:252
<asynchronous suspension>
#2      _SelectDialogState.initState.<anonymous closure>
package:dropdown_search/src/selectDialog.dart:83
#3      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)
#4      _rootRun (dart:async/zone.dart:1182:47)
#5      _CustomZone.run (dart:async/zone.dart:1093:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart<…>

**Comment by salim-lachdhaf** [comment]
which version are you using ?

**Comment by salim-lachdhaf** [comment]
check v 0.4.6, this should be fixed.
