### ISSUE TITLE
Package does not work under flutter 3.3.10

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/searchable_dropdown#550]
**Describe the bug**
Package does not work under flutter 3.3.10

**To Reproduce**
1. activate flutter 3.3.10
2. run example

**Expected behavior**
Package work in flutter 3.3.10 or min flutter version specified in pubspeck.yaml

**Screenshots**
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/6721286/222244709-9c5f6d32-9b85-47ae-9dd9-45d3f6818a6d.png">

**Desktop (please complete the following information):**
any

**Smartphone (please complete the following information):**
any

**Additional context**
no

**Comment by ChandAbdullah** [comment]
https://stackoverflow.com/a/75613311/13474281

**Comment by salim-lachdhaf** [comment]
@vasilich6107 you have to update your Flutter SDK version.
I will update the min SDK to `2.19.2` in th `pubspec.yaml`
