### ISSUE TITLE
Version 5.0.6 makes the app crash

### ISSUE THREAD

**Issue by ramirezsebas** [salim-lachdhaf/searchable_dropdown#552]
**Describe the bug**
I get an error when I try to use version 5.0.6. It makes the app crash.

**To Reproduce**
1. Go to pubspec.yaml
2. Add dropdown_search: 5.0.6
3. Run the app

**Expected behavior**
The app shouldn't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/61977214/223749620-36467565-c67a-4f22-ad94-390b4f336714.png)
![image](https://user-images.githubusercontent.com/61977214/223749695-4005814a-661a-4c5f-ba59-cd29c8d98d23.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: Samsung S20 +
 - OS: Android 13
 - Browser Chrome

**Additional context**
When I lower the version of the library to 5.0.5 it works.

Flutter version
![image](https://user-images.githubusercontent.com/61977214/223750884-c7054b8d-0633-4fd6-a62b-9d0f2220cba8.png)

**Comment by salim-lachdhaf** [comment]
please use the lastest flutter sdk.
