### ISSUE TITLE
Set the readOnly style as in TextFormField

### ISSUE THREAD

**Issue by manueltag** [salim-lachdhaf/searchable_dropdown#553]
**Is your feature request related to a problem? Please describe.**
When I set the enabled flag to false the InputDecoration style is set as disabled (correct behavior). It would be useful to set the style as in the TextFormField when the readOnly flag is set to true. The field is made read-only but not with disabled style (gray colors).

![Screenshot 2023-03-15 alle 12 09 30](https://user-images.githubusercontent.com/18601109/225293878-a094e4fb-0615-4230-9ccb-7d2e0dc1e40e.png)

The other fields you see in the screenshot have the readOnly flag set to true.

**Describe the solution you'd like**
It would be useful to set the style as in the TextFormField when the readOnly flag is set to true. The field is made read-only but not with disabled style (gray colors).

**Comment by salim-lachdhaf** [comment]
thhnx, fixed in the next version v6.0.0-pre that will be released in next days
