### ISSUE TITLE
Generics T accepts only String

### ISSUE THREAD

**Issue by gfb-47** [salim-lachdhaf/searchable_dropdown#555]
Why is there a generics option T on the package? Since it only accepts a String object?

<img width="134" alt="Screenshot 2023-03-22 at 08 54 24" src="https://user-images.githubusercontent.com/46033500/226898012-3d7b462d-75ef-451c-9cfb-54591858ca0e.png">

If there's no reason, maybe it should be removed.

**Comment by salim-lachdhaf** [comment]
No that is Wrong, if you want to use `showSelectedItem` property you have to override the `compareFn`  if the option T is not a `String.`
that's the whole idea :)
