### ISSUE TITLE
Refresh elements (asyncItems) from title widget

### ISSUE THREAD

**Issue by fehernyul** [salim-lachdhaf/searchable_dropdown#560]
Hi,
**Is your feature request related to a problem? Please describe.**
I need to do that functionality which can refresh/requery the dropdown elements by external calling.
I have a DropdownSearch which has title widget within the popupProps property.
On t he title widget I have a CheckBox (actually 2, but whatever) and I need to force the content refreshing via asyncItem's requery from the API.

How can I do this?

![image](https://user-images.githubusercontent.com/25593792/232864566-f1a0be8a-4726-4acf-bb36-4236771d1412.png)

**Describe the solution you'd like**
I want that when I click on any CheckBox on title widget, the asyncItem need to be refreshed.

**Additional context**

DropdownSearch<dynamic>(
  popupProps: PopupProps.menu(
    showSearchBox: true,
    isFilterOnline: true,
    title: DropDownPopupTitleWidget(

**Comment by salim-lachdhaf** [comment]
you can simply use the controller of the search field.
example of use case :
you tape "Ba" you get your results.
now you check the Match case , you re set the text to the controller of searchField which will fire the call of asyncItems.
