### ISSUE TITLE
[Web] `No items` widget is not dissapeared when seach is active

### ISSUE THREAD

**Issue by bambinoua** [salim-lachdhaf/searchable_dropdown#561]
https://user-images.githubusercontent.com/45417992/233932297-052df8b2-0f09-4bf1-aa11-68268e2dc11d.mp4

```
DropdownSearch(
  popupProps: PopupProps.menu(
    showSearchbox: true,
    isFilterOnline: true,
    emptyBuilder: (context, searchEntry) => Center(child: IconizedMessage('No data found')),
  ),
  ... // other properties
)

**Comment by salim-lachdhaf** [comment]
you have to check your data returned by `asyncItems` propos.

**Comment by salim-lachdhaf** [comment]
forget about my previous message it's my mistake, i didn't well understood your issue.

Now back to the issue, the answer is no, it's not a bug,  it's a normal behavior, "no data found" is the current result (not a state), and the progress is just to indicate that there is something in progress (loading state)...
the progress indicator is not meant to hide or replace current result.

you can add a background to the progressIndicator if you want to hide the background/the current result
