### ISSUE TITLE
Enable the possibility to use different type for value

### ISSUE THREAD

**Issue by jpcodr** [salim-lachdhaf/searchable_dropdown#562]
**Is your feature request related to a problem? Please describe.**
Yes. Currently, it is not possible to use one data type for the items and a different data type to use as the reference value of the selected item. Or at least I haven't found an example.

Suppose my list of options is a list of `Item` objects

```dart
class Item {
  final int id;
  final String name;
  final String code;

  Item({
    required this.id,
    required this.name,
    required this.code,
  });
}
```

I would like to be able to define the selected item by the id and not the entire object. Also, i want to display as option a string compound of `item.code`  and `item.name`.

**Describe the solution you'd like**
The possibility of define how will be the selected item. I don't know if `compareFn` can be used for this purpose since the function receives two params.

**Describe alternatives you've considered**
Maybe use some approach like `DropdownButton` of Flutter where the generic is only for the value data type and not for the list of items.
```dart
int? selectedItem

// some code

// DropdownSearch<T, V>
DropdownSearch<Item, int>( 
  value: selectedItem, // V? value
  onChanged: (int? value) => setState(() { selectedItem = value; }),
  popupProps: PopupProps.menu(
    itemBuilder: (BuildContext ctx, T item, isSelected)) => Widget
    ...
  ),
)
```

Or define another prop like:
```dart
int? selectedItem

// some code

DropdownSearch<Item>(
  selectedFn: (Item? item) => item.id == selectedItem // determines if the item is selected
  onChanged: (Item? item) => setState(() { selectedItem = item.id });
)
```

**Comment by salim-lachdhaf** [comment]
yes , you don't have to use T and V.
you have just to use compareFn which handle the check of if to items are equals.
in your case 
`compareFn:(Item i1, Item i2)=> i1.id == i2.id`

in your case you don't have to override the `selectedFn`.

and that's all :)
