### ISSUE TITLE
External InkWell doesn't customize with dropdown border decoration

### ISSUE THREAD

**Issue by FedericoCampesan** [salim-lachdhaf/searchable_dropdown#564]
When dropdown border are customized, the _InkWell_ container doesn't follow the customization

Based on the code I already found the problem, **line 281**

_@override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<List<T?>>(
      valueListenable: _selectedItemsNotifier,
      builder: (context, data, wt) {
        return IgnorePointer(
          ignoring: !widget.enabled,
          child: InkWell(
            **HERE MISSING PROPERTY**
            onTap: () => _selectSearchMode(),
            child: _formField(),
          ),
        );
      },
    );
  }_

**Comment by ABruel** [comment]
I second this. 
Want to be able to completely remove the inkwell. 
It looks horrible with my rounded inputs.

**Comment by salim-lachdhaf** [comment]
All clicks are now fully customizable with the new version 6.0.0-pre that will be released in the next days

Stay tuned ;)
