### ISSUE TITLE
Able to access the field through focus using the tab key, even if the field is disabled

### ISSUE THREAD

**Issue by NagaprabhuNagarajan** [salim-lachdhaf/searchable_dropdown#569]
I have disabled the field (enabled: false), but still I can access the field using the tab key in web view. 
I have overwritten the code and raised a pull request

PR:- https://github.com/salim-lachdhaf/searchable_dropdown/pull/568

<img width="395" alt="image" src="https://github.com/salim-lachdhaf/searchable_dropdown/assets/77880972/47f0d5f2-237d-4581-a107-c1666cda0a6f">
<img width="365" alt="image" src="https://github.com/salim-lachdhaf/searchable_dropdown/assets/77880972/825c82be-31be-4233-8ebf-1a89ff097ca2">

**Comment by negulici-r-barnabas** [comment]
Hello, @NagaprabhuNagarajan  I was struggling with the same issue and as a workaround I found that FocusableActionDetector widget can fix it, out the DropDownSearch as a child widget and the same variable that you use for its enabled field set the FocusableActionDetector.descendantsAreFocusable field, that way you will disable all of DropDownSearch focusability.

**Comment by salim-lachdhaf** [comment]
issue not reproductible in the next version v6.0.0-pre. this version will be release in the next days.

to search from dropdown, you have just use `Tab` and `space` (tested on Widows).
`Tab` to navigate between widgets and `space` to click
