### ISSUE TITLE
dropdown height

### ISSUE THREAD

**Issue by ravidhwn01** [salim-lachdhaf/searchable_dropdown#571]
the  custom height of dropdown  property should be mention 
because if i  have 2 items in  my itemlist however it shows a long dropdown  

there is 2 items in dropdown list and  with 2 items and whole list in blanked
![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/87488989/591c9da2-1136-406e-a4b4-bfd7208afbb7)

**Comment by jmsandiegoo** [comment]
Im having the same issue

**Comment by ravidhwn01** [comment]
not ata all still facing the same issue

**Comment by glaceon2000** [comment]
You can set the height in **popupProps** like this
<img width="526" alt="image" src="https://github.com/salim-lachdhaf/searchable_dropdown/assets/51567674/4eaedd01-97fe-4751-af38-c890a3f7ad78">

**Comment by ravidhwn01** [comment]
thank you, now it is working

**Comment by koodimetsa** [comment]
With fit you can make it the size of content(still not larger than constraints:

```
 popupProps: PopupProps.menu(
            fit: FlexFit.loose,
```
