### ISSUE TITLE
I can't delete any characters when reopening the bottom sheet (only real device Android Samsung).

### ISSUE THREAD

**Issue by tranhuyphuc9091** [salim-lachdhaf/searchable_dropdown#573]
Describe the bug
I can't delete any characters when reopening the bottom sheet (only real devices Android samsung).

To Reproduce
1. Open
2. Type some text into the search box.
3. Select an item
4. The bottom sheet closed
5. And then I open it again I can't delete any characters. I can only delete it when I enter more characters.
Expected behavior
I can delete any characters when reopening.
I am using version:  dropdown_search: ^2.0.1
https://github.com/salim-lachdhaf/searchable_dropdown/assets/5925243/1d376d2b-a5af-4e7b-aa8c-7eca73359f48

Please help me. Thanks all!

**Comment by salim-lachdhaf** [comment]
please try with last version 5.0.6.
