### ISSUE TITLE
how to change the dropdown icon (arrow down) to another icon

### ISSUE THREAD

**Issue by rodriger06** [salim-lachdhaf/searchable_dropdown#575]
Hi, I would like to change the down arrow icon in the dropdownsearch to a forward arrow.
i try suffixIcon: Icon(Icons.arrow_forward_ios) but it is not working.
please let me know how to change the downarrow icon to a icon of my choice

this is partial code

 Widget dropDownField(BuildContext context) {
    return ReactiveDropdownSearch<String, String>(
        formControlName: widget.textFieldLabel,
      
        items: ["Weekly", "Bi-Weekly", "Monthly", 'Quarterly', 'Yearly', 'One Time'],
        showClearButton: true,
        dropdownDecoratorProps: const DropDownDecoratorProps(
          baseStyle: TextStyle( fontSize: text_size_18),
          dropdownSearchDecoration: InputDecoration(
            suffixIcon: Icon(Icons.arrow_forward_ios),
            hintText: frequencyLabel,
            //labelText: frequencyLabel,
            labelStyle: TextStyle( fontSize: text_size_18),
           // contentPadding: EdgeInsets.fromLTRB(margin_0dp, margin_18dp, margin_0dp, margin_18dp),
            enabledBorder: UnderlineInputBorder(
              borderSide: const BorderSide(color: Colors.black),
            ),

i want to change this icon
![downarrow](https://github.com/salim-lachdhaf/searchable_dropdown/assets/49496303/0b1428b6-4659-40ac-9bcd-c12ff0f279d1)

to this icon
![forward_arrw](https://github.com/salim-lachdhaf/searchable_dropdown/assets/49496303/bfe1e823-fd67-42bd-ad07-aa044d87f8b6)

thanks in advance

**Comment by OkeyEzeobele** [comment]
You can customize like this

```dart
dropdownButtonProps: DropdownButtonProps(
   icon: Icon(Icons.keyboard_arrow_right),
)
```

**Comment by rodriger06** [comment]
thanks a lot. it works great
