### ISSUE TITLE
Error: No named parameter with the name 'shadowThemeOnly'.

### ISSUE THREAD

**Issue by LefebvreIlyas** [salim-lachdhaf/searchable_dropdown#58]
See [flutter/pull/68922](https://github.com/flutter/flutter/pull/68922).

**Comment by salim-lachdhaf** [comment]
Need more information about the version of flutter used here ! Because the plugin with flutter v 1.22 had no issue either 1.23beta

**Comment by LefebvreIlyas** [comment]
Yes of course, here is my flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.24.0-7.0.pre.75, on Microsoft Windows [version 10.0.18363.1139], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.7.7)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
[√] VS Code (version 1.50.1)
[√] Connected device (4 available)

• No issues found!
```

**Comment by salim-lachdhaf** [comment]
Thank you for your reply, 1.24 still not the stable channel, current is 1.22, ones it passes to stable channel we add all necessary modification based on that new version.
I'm saying that to prevent to modify each time the plugin until get the stable version.

**Comment by LefebvreIlyas** [comment]
Yes, I understand, at least the PR is already ready. 😁 (for this change at least).

**Comment by Shiba-Kar** [comment]
I am also facing the same in master branch @LefebvreIlyas  could you suggest a workaround for now!!!.

**Comment by salim-lachdhaf** [comment]
downgrade the flutter version, and it's better to work only for stabe version , now flutter is in 1.22.3 stable and the plugin is fully adapted to that last stable version
