### ISSUE TITLE
Duplicate GlobalKey detected in widget tree.

### ISSUE THREAD

**Issue by gapkukb** [salim-lachdhaf/searchable_dropdown#582]
When duplicate click this component,will dispear the error message:

════════ Exception caught by widgets library ═══════════════════════════════════
Duplicate GlobalKey detected in widget tree.

by the way 

the dropdown unnecessary appear again if the dropdownmean was appeared.

the two problems cause by multiple click.

thanks . 

![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/15757875/6cc17cd9-675b-4890-89ae-b00b145c6288)

**Comment by herna** [comment]
Hello,

Any updates on this? I was also facing these "Duplicate GlobalKey" issues and after reduce my application to a minimum I just realised it happens with the simplest example when you select different options from the popup quickly.

Taking the example from this project: https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart

If you just use the first dropdown on the top left corner and select several times different options in the popup, you easily get the following error in the console:

![2023-09-29 11 38 00](https://github.com/salim-lachdhaf/searchable_dropdown/assets/3002441/ce4f9b66-fb51-4f2f-b134-ac4e41862c7e)

**Comment by salim-lachdhaf** [comment]
thank you for reporting that, i tried to reproduce that with the last version v6.0.0 but without success, could please check if you still have the issue ?

**Comment by herna** [comment]
It's working fine now. Thank you.

**Comment by salim-lachdhaf** [comment]
@herna thank you for the validation.
