### ISSUE TITLE
Supplying [items], [selectedItem] and[onChanged] fields in constructor, doesn't trigger [onChanged] event

### ISSUE THREAD

**Issue by IanMcCarthy** [salim-lachdhaf/searchable_dropdown#583]
My DropdownSearch<OrganisationRecord> constructor includes:

A list of OrganisationRecords in [items]
An OrganisationRecord to select in [selectedItem]
A function reference to call in [onChanged]
A PopupProps.menu() instance for [popupProps]

The widget renders as expected with the selected item's text in the dropdown field and if tapped the dropdown list appears with the same item highlighted.

However, the [onChanged] callback doesn't get called.

If I select a different item from the available list, the [onChanged] callback happens.

Would you not expect the callback to happen as the selected Item has changed, in the first instance as well?

Target currently Samsung S21 Android 13

**Comment by salim-lachdhaf** [comment]
Sadly i'm not able to reproduce the issue, the onChange should be called each time you select an item.
Have you an simple example to reproduce the issue ?

**Comment by salim-lachdhaf** [comment]
no repley
