### ISSUE TITLE
Error: 'EditableTextContextMenuBuilder' isn't a type.

### ISSUE THREAD

**Issue by yjt1216** [salim-lachdhaf/searchable_dropdown#584]
**Describe the bug**

../../../flutter305/flutter/.pub-cache/hosted/pub.flutter-io.cn/dropdown_search-5.0.6/lib/src/properties/text_field_props.dart:14:9: Error: 'EditableTextContextMenuBuilder' isn't a type.
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by salim-lachdhaf** [comment]
Bug not related to plugin.
