### ISSUE TITLE
EXCEPTION CAUGHT BY GESTURE after click Clear Button

### ISSUE THREAD

**Issue by fhassani** [salim-lachdhaf/searchable_dropdown#585]
**Describe the bug**
An "EXCEPTION CAUGHT BY GESTURE" after click Clear Button.

**To Reproduce**

in a DropdownSearch<String>
with 
clearButtonProps: const ClearButtonProps(isVisible: true),

1. Click on 'X'

4. See error in DEBUG CONSOL

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown while handling a gesture:
Unexpected null value.
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 606:63  nullCheck
packages/qayzar/widgets/crud_form_dropdownsearch.dart 74:30                       <fn>
packages/flutter/src/widgets/framework.dart 1139:30                               setState
packages/qayzar/widgets/crud_form_dropdownsearch.dart 73:19                       <fn>
packages/dropdown_search/dropdown_search.dart 646:16                              <fn>
packages/dropdown_search/dropdown_search.dart 663:17                              [_handleOnChangeSelectedItems]

**Expected behavior**
No EXCEPTION expected.

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by salim-lachdhaf** [comment]
you have problem in managing nullSafety, code you past an example code to reproduce the bug ?

**Comment by salim-lachdhaf** [comment]
no reply
