### ISSUE TITLE
Specified `hintTest` does not show

### ISSUE THREAD

**Issue by bambinoua** [salim-lachdhaf/searchable_dropdown#586]
I want to see the hint when dropdown is empty. I specified it
```dart
dropdownSearchDecoration: InputDecoration(
  hintText: 'Choose an item',
)
```
but it does not show.

**Comment by bhaumik-iconflux** [comment]
Same issue
"dropdownSearchDecoration" hintText does not show

**Comment by AbikMathew** [comment]
I also have the same issue

**Comment by CoreySafetyIndicators** [comment]
As of 5.0.6 this still seems to be an issue.  Does anyone have a timeline on a fix or a workaround?

**Comment by dieg0omni** [comment]
same problem here, with version dropdown_search: 5.0.6

**Comment by dhruv-d-7span** [comment]
hey devs,
as you can see in below code there's a `hintText` in `dropdownSearchDecoration` but in case you want to show the hintText in the searchBox of dropdown then first you have to use  `PopupPropsMultiSelection.menu` in which you can find the `searchFieldProps` which may help you to solve your current issues.

`                                              DropdownSearch<StateData?>(
                                                itemAsString: (StateData? item) => item?.name ?? '',
                                                validator: (StateData? data) {
                                                  if (data == null) {
                                                    return 'Please select state';
                                                  } else {
                                                    return null;
                                                  }
                                                },
                                                popupProps: PopupPropsMultiSelection.menu(
                                                  fit: FlexFit.loose,
                                                  searchFieldProps: TextFieldProps(
                                                    decoration: InputDecoration(
                                                      hintText: 'Search Your State Here',
                                                      border: OutlineInputBorder(
                                                        borderRadius: BorderRadius.circular(
                                                          AppTheme.defaultRadius,
                                                        ),
                                                      ),
                                                      focusedBorder: OutlineInputBorder(
                                                        borderRadius: BorderRadius.circular(
                                                          AppTheme.defaultRadius,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  showSelectedItems: true,
                                                  isFilterOnline: true,
                                                  showSearchBox: true,
                                                ),
                                                items: cityStateController.stateList ?? [],
                                                dropdownDecoratorProps: DropDownDecoratorProps(
                                                  baseStyle: context.textTheme.titleMedium,
                                                  dropdownSearchDecoration: InputDecoration(
                                                    hintText: 'Select State',
                                                    focusedBorder: OutlineInputBorder(
                                                      borderSide: const BorderSide(
                                                        color: AppColors.transparent,
                                                      ),
                                                      borderRadius: BorderRadius.circular(
                                                        AppTheme.defaultRadius,
                                                      ),
                                                    ),
                                                    enabledBorder: OutlineInputBorder(
                                                      borderSide: const BorderSide(
                                                        color: AppColors.transparent,
                                                      ),
                                                      borderRadius: BorderRadius.circular(
                                                        AppTheme.defaultRadius,
                                                      ),
                                                    ),
                                                    border: OutlineInputBorder(
                                                      borderRadius: BorderRadius.circular(
                                                        AppTheme.defaultRadius,
                                                      ),
                                                    ),
                                                    hintText: 'Select State',
                                                    contentPadding: const EdgeInsets.all(15),
                                                    hintStyle: context.textTheme.titleMedium?.copyWith(
                                                      fontWeight: AppFontWeight.regular,
                                                    ),
                                                    filled: true,
                                                    fillColor: AppColors.white,
                                                  ),
                                                ),
                                                onChanged: (value) {
                                                  controller.selectedState = value;
                                                  cityStateController.selectedState = value;
                                                },
                                                compareFn: (StateData? item, StateData? selectedItem) => item == selectedItem,
                                              ),
`

**Comment by Dhruvvachheta1304** [comment]
Hey devs,
as you can see in below code there's a `hintText` in `dropdownSearchDecoration` but in case you want to show the hintText in the searchBox of dropdown then first you have to use  `PopupPropsMultiSelection.menu` in which you can find the `searchFieldProps` which may help you to solve your current issues.

```javascript
                                              DropdownSearch<StateData?>(
                                                itemAsString: (StateData? item) => item?.name ?? '',
                                                validator: (StateData? data) {
                                                  if (data == null) {
                                                    return 'Please select state';
                                                  } else {
                                                    return null;
                                                  }
                                                },
                                                popupProps: PopupPropsMultiSelection.menu(
                                                  fit: FlexFit.loose,
                                                  searchFieldProps: TextFieldProps(
                                                    decoration: InputDecoration(
                                                      hintText: 'Search Your State Here',
                                                      border: OutlineInputBorder(
                                                        borderRadius: BorderRadius.circular(
                                                          AppTheme.defaultRadius,
                                                        ),
                                                      ),
                                                      focusedBorder: OutlineInputBorder(
                                                        borderRadius: BorderRadius.circular(
                                                          AppTheme.defaultRadius,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  showSelectedItems: true,
                                                  isFilterOnline: true,
                                                  showSearchBox: true,
                                                ),
                                                items: cityStateController.stateList ?? [],
                                                dropdownDecoratorProps: DropDownDecoratorProps(
                                                  baseStyle: context.textTheme.titleMedium,
                                                  dropdownSearchDecoration: InputDecoration(
                                                    hintText: 'Select State',
                                                    focusedBorder: OutlineInputBorder(
                                                      borderSide: const BorderSide(
                                                        color: AppColors.transparent,
                                                      ),
                                                      borderRadius: BorderRadius.circular(
                                                        AppTheme.defaultRadius,
                                                      ),
                                                    ),
                                                    enabledBorder: OutlineInputBorder(
                                                      borderSide: const BorderSide(
                                                        color: AppColors.transparent,
                                                      ),
                                                      borderRadius: BorderRadius.circular(
                                                        AppTheme.defaultRadius,
                                                      ),
                                                    ),
                                                    border: OutlineInputBorder(
                                                      borderRadius: BorderRadius.circular(
                                                        AppTheme.defaultRadius,
                                                      ),
                                                    ),
                                                    hintText: 'Select State',
                                                    contentPadding: const EdgeInsets.all(15),
                                                    hintStyle: context.textTheme.titleMedium?.copyWith(
                                                      fontWeight: AppFontWeight.regular,
                                                    ),
                                                    filled: true,
                                                    fillColor: AppColors.white,
                                                  ),
                                                ),
                                                onChanged: (value) {
                                                  controller.selectedState = value;
                                                  cityStateController.selectedState = value;
                                                },
                                                compareFn: (StateData? item, StateData? selectedItem) => item == selectedItem,
                                              )
    ```

**Comment by salim-lachdhaf** [comment]
Thanx @Dhruvvachheta1304 
As mentioned up, if you want to show the hint in the dropdown use `dropdownDecoration` 
And for the search area you can use `searchFieldProps` property of `popupProps`
