### ISSUE TITLE
Menu is hiding the text field.

### ISSUE THREAD

**Issue by ronytesler** [salim-lachdhaf/searchable_dropdown#587]
**Describe the bug**
Menu is hiding the text field.
![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/9344207/96e72f03-27e7-45a5-8adb-bbd7565c41b6)

**To Reproduce**
Click the text box

**Expected behavior**
The menu is below the field and goes down almost to the bottom of the screen:
![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/9344207/f5060c0f-3885-4fb3-8564-cd6cefc30111)

Made this by setting 
```
popupProps: PopupProps.menu(
                                    fit: FlexFit.loose,

                                    constraints:
                                        const BoxConstraints(maxHeight: 300),
```
But that doesn't work if the screen height changes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 114.0.5735.134

**Additional context**
  dropdown_search: ^5.0.6

**Comment by salim-lachdhaf** [comment]
this is a normal behavior, the system is automatically (not the library) pushing the menu up if there is no space in bottom.

you can for example have the same behavior in Android for AutoCompleteTextView.
