### ISSUE TITLE
How to search from dropdown and select item from dropdown using keyboard

### ISSUE THREAD

**Issue by tkumark** [salim-lachdhaf/searchable_dropdown#590]
In flutter how to create a dropdown with search option. I am creating a desktop app. The user will be navigating the fields in the form using keyboard tab. When user reaches the dropdown field user should be able to type to search and select from dropdown.

Any suggestion or sample code using searchable_dropdown would be helpful. I went through sample none seem to be keyboad friendly.

**Comment by salim-lachdhaf** [comment]
issue not reproductible in the next version v6.0.0-pre. this version will be release in the next days.

to search from dropdown, you have just use `Tab` and `space` (tested on widows).
`Tab` to navigate between widgets and `space` to click
