### ISSUE TITLE
Search functionality doesnt work in release mode

### ISSUE THREAD

**Issue by aggeloskoutanis** [salim-lachdhaf/searchable_dropdown#591]
**Describe the bug**
I have create a dropdown with offline search functionality. When my app is built with --debug flag the search functionality works good. When the app is build with --release flag, then while entering some text in the search box I always get 'No data found.'. Any suggestions?

**Smartphone (please complete the following information):**
 - Device: iPhone 12, pixel 4a
 - OS: Android 13

**Comment by RootSoft** [comment]
I think it's related to: https://github.com/salim-lachdhaf/searchable_dropdown/blob/86d7b59cb3c5146f159c08eb097091cda4193ccd/lib/src/widgets/selection_widget.dart#L301

Your best bet would be to implement the `filterFn`:

```
filterFn: (currency, filter) {
              return currency.name.toLowerCase().contains(filter.toLowerCase());
            },
```

**Comment by aggeloskoutanis** [comment]
Hey @RootSoft , thanks a lot for your reply. It turns out I don't need to implement the `filterFn`. It's sufficient to `@override` the `toString` method of the model I use in the dropdown. 

In the line of code that you attached, the toString method is used to compare between the filter. I guess when I don't implement the toString, the code doesn't know which value exactly to compare with the filter. So, implementing toString solves this problem.

Despite that, I have no clue why this was working without implementing the toString in debug mode, but it didn't work in release mode.

thanks again for your reply,

Happy coding

**Comment by RootSoft** [comment]
I wouldn't rely on the `toString` method for comparison. 
The reason is probably that due to obfuscation (in release mode) that the `toString()` method gets scrambled.
