### ISSUE TITLE
How can i change the color of the checkbox ?

### ISSUE THREAD

**Issue by rulefahd** [salim-lachdhaf/searchable_dropdown#592]
how can i change the color on checked for the checkbox ?

**Comment by sabari7320** [comment]
use this  popupSelectionWidget: (context, item, isSelected) {
        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 5, horizontal: 16),
          child: Row(
            children: [
              SizedBox(
                width: 24, // Adjust as needed
                height: 24, // Adjust as needed
                child: Checkbox(
                  value: isSelected,
                  onChanged: (value) {
                    if (widget.onChanged != null) {
                      List<T> selectedItems = _selectedItems.toList();
                      if (value ?? false) {
                        selectedItems.add(item);
                      } else {
                        selectedItems.remove(item);
                      }
                      setState(() {
                        _selectedItems = selectedItems;
                      });
                      widget.onChanged!(selectedItems);
                    }
                  },
                  checkColor: Colors.white, // Change checkbox color here
                  activeColor: kBlueGrey, // Change checkbox fill color here
                ),
              ),

            ],
          ),
        );
      },
