### ISSUE TITLE
Dropdown too long

### ISSUE THREAD

**Issue by denxorz** [salim-lachdhaf/searchable_dropdown#593]
**Describe the bug**
When you only have a few items in the dropdown, the list shown is a lot longer compared with the options available.

code:
```
DropdownSearch<bool>(
          selectedItem: _opt,
          itemAsString: (bool u) => u ? 'yes' : 'no',
          items: const [false, true],
          onChanged: (data) => setState(() => _opt = data),
        ),
```

**To Reproduce**
1. Use code above with version 5.0.6
2. Click the dropdown

**Expected behavior**
I expect the dropdown to be as long as the number of items available.

**Screenshots**
![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/2905592/4a87f522-88b7-4136-aeff-4195c840390d)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T / Fairphone 3
 - OS: Android 13

**Additional context**
- na

**Comment by riseuplabs20090176** [comment]
use this:

DropdownSearch<bool>(
          selectedItem: _opt,
          itemAsString: (bool u) => u ? 'yes' : 'no',
          items: const [false, true],
          onChanged: (data) => setState(() => _opt = data),
          popupProps: const PopupProps.menu(
                            fit: FlexFit.loose,
                        ),
        ),

**Comment by denxorz** [comment]
Hello @riseuplabs20090176 , your example works nicely. Thanks.

Is this intended behavior, or will this be the default behavior after a fix?

**Comment by salim-lachdhaf** [comment]
this is for now the default behavior were we fixed the height. and the user could change fit depending on his data lenght.

**Comment by denxorz** [comment]
Okay @salim-lachdhaf , thanks for the info and the great product.
Dennis
