### ISSUE TITLE
Selected items overflow Multiselection Dropdown 

### ISSUE THREAD

**Issue by madhubansahani** [salim-lachdhaf/searchable_dropdown#594]
<img width="731" alt="Screenshot 2023-09-05 at 2 30 39 PM" src="https://github.com/salim-lachdhaf/searchable_dropdown/assets/107603778/fecb470f-776c-4a4c-9b89-b5baa5b49d9a">

**Comment by madhubansahani** [comment]
Facing this issue please resolve

**Comment by madhubansahani** [comment]
please solve

**Comment by salim-lachdhaf** [comment]
this issue is fixed in the next version v6.0.0-pre that will be released in the next days.

Stay tuned ;)
