### ISSUE TITLE
bottom sheet enters the system navigation bar area

### ISSUE THREAD

**Issue by kazuiains** [salim-lachdhaf/searchable_dropdown#595]
**Describe the bug**
if we set it to
   SystemChrome. setEnabledSystemUIMode(
     SystemUiMode.edgeToEdge,
     overlays: [SystemUiOverlay. top],
   );
all popups cross the system navigation bar boundary. please enter SafeArea on all popups.

**To Reproduce**
1. setting to SystemChrome. setEnabledSystemUIMode(
     SystemUiMode.edgeToEdge,
     overlays: [SystemUiOverlay. top],
   );
2. all type dropdown. 
3. and show it.

**Expected behavior**
bottom sheets and other types do not cross the line. does not enter the system navigation bar area.

**Screenshots**
<img width="2048" alt="Screenshot 2023-09-06 at 11 55 42" src="https://github.com/salim-lachdhaf/searchable_dropdown/assets/38340245/63a19348-be05-4512-8b71-3eccc106a6ae">

**Comment by salim-lachdhaf** [comment]
I don't think it's an issue, you just set `SystemUiMode.edgeToEdge` so the system will use full screen.

this is the launcher of Android 15 ;)

![image](https://github.com/user-attachments/assets/96ba23b3-856e-40cc-a9f0-9cc6a7470704)


ModalBottomSheet as example is has useSafeArea property which is not respected here.

i found a Flutter issue [here](https://github.com/flutter/flutter/issues/64274) for Android devices.

**however, if you want to bypass the edge to edge  just use `containerBuilder` property of `popupProps` like this will solve your problem :**


```

containerBuilder: (context, popupWidget) {
     return Container(
           padding: EdgeInsets.only(bottom: 50),
           child: popupWidget,
     );
},

```
