### ISSUE TITLE
No search possible

### ISSUE THREAD

**Issue by alexdess** [salim-lachdhaf/searchable_dropdown#596]
Hello,

First of all, thank you for making the plugin available. However, I can't get it to work. Under MacOs, the search never works. Am I doing something wrong in my simple example below?

**To Reproduce**
    final dropdown = DropdownSearch<ClientDataModel>(
      popupProps: PopupProps.menu(),
      itemAsString: (e) => "${e.name} ${e.firstname} (${e.zipcode} ${e.locality})",
      filterFn: (item, filter) => item.name.toLowerCase().contains(filter.toLowerCase()),
        dropdownDecoratorProps: DropDownDecoratorProps(
          dropdownSearchDecoration: InputDecoration(labelText: "Client", hintText: "Choix du client"),
        ),
        selectedItem: _selectedValue,
        items: dataItems,
        onChanged: ((value) {
          if (value != null) {
            onChange(value);
          }
        }));

**Expected behavior**
Once in the dropdown, when I click on a key on the keyboard, I'd like the search to be carried out in some way. At the moment, I get a sound feedback from the OS telling me that I'm not in a text field.

**Desktop (please complete the following information):**
 - OS: Mac OS VENTURA 13.4.1

**Comment by salim-lachdhaf** [comment]
you should open the popup and select search field then you can start typing.
