### ISSUE TITLE
Expose SelectionWidget so that it can be used Independent of the `DropdownButton`.

### ISSUE THREAD

**Issue by asadamatic** [salim-lachdhaf/searchable_dropdown#597]
**Usecase**

I have a usecase where I want to display a dialog, bottom, or menu consisting of a searchable list of items, but I do not need a `Dropdown` button. 

**Solution**

It would be very helpful if `SelectionWidget` is exported and made suitable to be used independently of the `DropdownButton` .

**Comment by salim-lachdhaf** [comment]
nice idea, noted to be done in the next version.

**Comment by salim-lachdhaf** [comment]
added `DropdownSearchSelectionin ` the next version v6.0.0-pre that will be released in next days
