### ISSUE TITLE
How to add clear button after select items

### ISSUE THREAD

**Issue by MuhammadFaisalIchal** [salim-lachdhaf/searchable_dropdown#598]
I install dropdown_search version 5.0.6, but the clear button is not displayed by default.
I tried to add it by adding `clearButtonProps` property but still, the clear button didn't showed.

How to add this function?
Because i saw earlier video, they were default packed with clear button after you select an item..

**Comment by salim-lachdhaf** [comment]
try this `clearButtonProps: ClearButtonProps(isVisible: true),`

**Comment by MuhammadFaisalIchal** [comment]
Yeah i already did that, and it works, thanks..
But how to clear the selected item? I saw a property named `onPressed()`, i try to implement it and the press listener worked.

But again, how to clear the selected item?

**Comment by salim-lachdhaf** [comment]
you don't have to ovveride `onPressed` if you want only clear them item. The plugin will do it for you.

If you want clear the item and do otherThings ..., in that case you can ovveride `onPressed` and clear the selected item programmatically like here https://github.com/salim-lachdhaf/searchable_dropdown/blob/86d7b59cb3c5146f159c08eb097091cda4193ccd/example/lib/main.dart#L513C19-L513C39 and add you logic

**Comment by MuhammadFaisalIchal** [comment]
Thanks! 😁

**Comment by MuhammadFaisalIchal** [comment]
Thanks!!
