### ISSUE TITLE
When showSelectedItem: true it would be nice if selected item is scrolled into view when select dialog opens.

### ISSUE THREAD

**Issue by slavap** [salim-lachdhaf/searchable_dropdown#6]
Unfortunately ListView does not have scroll into index functionality.
The possible workaround is https://stackoverflow.com/a/58435822
it works for fixed height items, so for most of the dropdown cases should be fine.
At least it should be possible to pass ScrollController as parameter to DropdownSearch.

**Comment by joo** [comment]
Need scrolled into selected item.
