### ISSUE TITLE
Adding dynamic data to the items list

### ISSUE THREAD

**Issue by Alqader** [salim-lachdhaf/searchable_dropdown#60]
I'm trying to add data that I'm receiving from Websocket  to items list. Does the package supports adding data dynamically to  items list or is there a work around ?

Thanks in advance.

**Comment by salim-lachdhaf** [comment]
Do you mean that you have asyc and sync data, if yes , the response is YES.

You can add your items to items and pass the future that returns items from the websocket to onFind .
There an example like this in the plugin example.

Otherwises, please explain more

**Comment by Alqader** [comment]
Correct, what I meant is async data, but the issue is that I'm storing the items then calling them in (items: ), because the items isn't stored in a database.

The best I could reach is that the DropdownSearch refreshes every time I press it(by notifyListeners()), but doesn't load items async during searching.

I'm moderate in flutter, so If I missed a method, please let me know.

**Comment by salim-lachdhaf** [comment]
so you mean that your item from the socket change over time ? it is a stream ?

**Comment by Alqader** [comment]
Yeah, I'm receiving items (let's say strings) from a socket as a stream.

**Comment by salim-lachdhaf** [comment]
In that case i will suggest two solution:
1- add global for the searchable dropdown (see plugin example) and set items like this:
`globalKey.currentState.widget.items = yourData`.
Note here that `yourData` is all received data until that point.
Then call `setState`.

2- create a variable to store received data and assign that variable to your searchable dropdown like this : `items: yourVar`
And each time you receive data put all the data to `yourVar` and call `setState`.

Hope this is clear and could help you
