### ISSUE TITLE
Height of multiSelection

### ISSUE THREAD

**Issue by czaefferer** [salim-lachdhaf/searchable_dropdown#602]
**Describe the bug**
After having selected entries from a multiSelection, each entry is output to a Container with a fixed height of 32. With a high text-zoom text will not be centered anymore, and with output consisting of more than one line, text will get cut off.

**To Reproduce**
Use the .multiSelection example on an Android device where the text scaling is set to 2x.

**Expected behavior**
The high should be dynamic to the content. Removing the fixed height of 32 (or making if configurable with `null`being allowed) would achieve that: https://github.com/salim-lachdhaf/searchable_dropdown/blob/0db798a07a222435950c024abdbf8f8926798211/lib/dropdown_search.dart#L299

**Screenshots**
Example with one line with 2x text zoom: 
![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/47598945/8c6aad68-845b-4acb-af5a-b8cbf786f064)
Example with text spread across two lines with 2x text zoom:
![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/47598945/d0c8f4ae-48fb-4c1a-85b8-2c8651a044cf)
Output of one line example with the fixed height of 32 removed:
![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/47598945/4746bd1f-f43c-4db7-a6c1-60bb29958786)
Output of two lines example with the fixed height of 32 removed:
![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/47598945/250bfe69-79bf-41ba-815c-b057797e31bb)

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab A8
 - OS: Android 
 - Version 13

**Comment by salim-lachdhaf** [comment]
fixed in 6.0.1, it will be released today
