### ISSUE TITLE
DropdownSearch not scrolling to initial item when opened.

### ISSUE THREAD

**Issue by a7mdragab** [salim-lachdhaf/searchable_dropdown#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

^10.1.0

### Platforms

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 3.14.0-0.2.pre, on Microsoft Windows [Version 10.0.22621.2428], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.1)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.84.0)
[√] Connected device (4 available)

Hello,
I want the DropdownSearch to scroll to initial item when opened.
This widget opens every time from the start.

### **Minimal code example**

```
        DropdownSearch<int>(
            key: UniqueKey(),
            name: 'DropdownSearch',
            items: List.generate(100, (index) => index),
            selectedItem: 50,
            compareFn: (a, b) => a == b,
          ),
```

### **Current Behavior**
This widget opens every time from the start.

### **Expected Behavior**
I want the DropdownSearch to scroll to initial item when opened.

### **Steps To Reproduce**

Just use this widget

### **Additional information**

![image](https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/assets/30768001/f1ea0250-8f88-470d-a8c4-89efd9c84b32)

**Comment by salim-lachdhaf** [comment]
Yes, the library is not scrolling to the selected item.
The question is: why do we need to scroll to the selected item if it's already visible? 

Note that you can have a list where the selected item is not included.

**Comment by a7mdragab** [comment]
> Yes, the library is not scrolling to the selected item. The question is: why do we need to scroll to the selected item if it's already visible?
> 
> Note that you can have a list where the selected item is not included.

Sorry for being late.
But it is not always visible like this

**
![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/30768001/e0f430ef-50a7-4513-a685-5b70baa702e9)
**
