### ISSUE TITLE
Validator not work

### ISSUE THREAD

**Issue by TheoRevFdz** [salim-lachdhaf/searchable_dropdown#61]

**Comment by TheoRevFdz** [comment]
implement the validation but it doesn't work, it doesn't show the validation message.

**Comment by slavap** [comment]
@TheoRevFdz it works just fine, check attached demo project, try to clear City field.
[dd_bug.zip](https://github.com/salim-lachdhaf/searchable_dropdown/files/5498359/dd_bug.zip)

**Comment by salim-lachdhaf** [comment]
As said @slavap  it works just fine. could you please past your code here ?

**Comment by salim-lachdhaf** [comment]
No response. Closed
