### ISSUE TITLE
Difficulty implementing infinite scroll on widget popup

### ISSUE THREAD

**Issue by fauzanfadallah** [salim-lachdhaf/searchable_dropdown#611]
I get a problem when i want to add infinite scroll to apply pagination on a list of items, I've tried adding a listener to the scrollcontroller but the list of items doesn't load, is there a way I don't know? If not, could you add a feature to reload the list of items while the popup is open?

**Comment by 53huzefa-zeenwala** [comment]
i am facing the same issue, did anyone get the solution.

**Comment by salim-lachdhaf** [comment]
this feature is coming soon.

**Comment by ElecSmurf** [comment]
Hi Salim, any news on this feature?

**Comment by salim-lachdhaf** [comment]
The infiniteScroll is completely implimented and much more , will be available in the v6.0.0-pre that will be release in the next days.

Stay tuned ;)
