### ISSUE TITLE
Dropdown width fit to content

### ISSUE THREAD

**Issue by negulici-r-barnabas** [salim-lachdhaf/searchable_dropdown#612]
Is there a way to increase the width of the dropdown? I noticed that I can set the height via the PopupProps.menu using fit.loose but I am having difficulty with the width. My main issue is that the items are being wrapped to two lines if one of them is longer, I need them to fit but I don't know how to make the width of the dropdown (only the dropdown) larger. Does someone know how can I make the dropdown width larger to fit the content within? I also tried to use FittedBox in itemBuilder which works but the issue there is makes the text font size smaller (scales down the item to fit).
![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/109497789/284b2d0b-05be-4836-aa39-32045cd00e48)

**Comment by knpaing** [comment]
I think you can override the constraints of the PopupProps.menu property.

**Comment by dhanesh12twice** [comment]
constraints will work only when PositionCallback in menuProps in not null
