### ISSUE TITLE
Try adding space between searchbox and popup menu

### ISSUE THREAD

**Issue by anonimeact** [salim-lachdhaf/searchable_dropdown#613]
Hi, i try to add space between the searchbox and popup menu by add custom positionCalback like this, and not working.
```dart
return RelativeRect.fromSize(
      Rect.fromPoints(
        popupButtonObject.localToGlobal(popupButtonObject.size.bottomLeft(Offset(0, 20)), ancestor: overlay),
        popupButtonObject.localToGlobal(popupButtonObject.size.bottomRight(Offset.zero), ancestor: overlay),
      ),
      Size(overlay.size.width, overlay.size.height),
    );
``` 
but when i try changing **20** with negative value (e.g: **-20**), the popupmenu go up,
Is there any suggestion regarding my confusion?

**Comment by salim-lachdhaf** [comment]
Could you please provide a reproducible example ?

**Comment by zeeshanahmad0201** [comment]
You need to add the same value on both points. Please see the following
```
return RelativeRect.fromSize(
    Rect.fromPoints(
      popupButtonObject.localToGlobal(popupButtonObject.size.bottomLeft(const Offset(0, 20)), ancestor: overlay),
      popupButtonObject.localToGlobal(popupButtonObject.size.bottomRight(const Offset(0, 20)), ancestor: overlay),
    ),
    Size(overlay.size.width, overlay.size.height),
  );
```

**Comment by salim-lachdhaf** [comment]
`margin` is a  new property added to the menuPopup.
Added in the next version 6.0.0-pre that will be released in the next days.

Stay tuned ;)

**Comment by salim-lachdhaf** [comment]
@zeeshanahmad0201 thx.
@anonimeact for now the only solution is to use `position` property
