### ISSUE TITLE
I think you can add text in validationWidgetBuilder as we can change th OK test of ElevatedButton

### ISSUE THREAD

**Issue by mazab99** [salim-lachdhaf/searchable_dropdown#615]

**Comment by mazab99** [comment]
and also add function

**Comment by KaiExa** [comment]
Can try edit here

`
validationWidgetBuilder: (context, items) {
          return ElevatedButton(
            onPressed: () {
              _popupCustomValidationKey.currentState?.popupOnValidate();
            },
            child: Text('TEST'),
          );
        },
`

![Uploading Screenshot 2023-12-13 at 19.05.41.png…]()

**Comment by salim-lachdhaf** [comment]
here an example : https://github.com/salim-lachdhaf/searchable_dropdown/blob/0db798a07a222435950c024abdbf8f8926798211/example/lib/main.dart#L107
