### ISSUE TITLE
Weird Focus behavior

### ISSUE THREAD

**Issue by busslina** [salim-lachdhaf/searchable_dropdown#616]
When focus back to my app, it ignores my primary focus (_TabContentState) which is a FocusScope and set its parent as primary focus (_SystemTabBodyState), also a FocusScope.

I'm using `PopupProps.menu`.

Any help with that?

https://github.com/salim-lachdhaf/searchable_dropdown/assets/73592852/bb3fcaf3-bd0d-4fa3-9fb6-b305791c3ecc

**Comment by salim-lachdhaf** [comment]
thank you for reporting that, i tried to reproduce that with the last version v6.0.0 but without success, could please check if you still have the issue ?

**Comment by salim-lachdhaf** [comment]
no reply
