### ISSUE TITLE
Option to remove search delay

### ISSUE THREAD

**Issue by joranmulderij** [salim-lachdhaf/searchable_dropdown#617]
Would it be possible to add an option that can be used to remove the search delay?
Would be really nice.

Thanks in advance.

**Comment by GameOnAnil** [comment]
@joranmulderij  This is already available. You can do
```
DropdownSearch(
     popupProps: PopupProps.menu(searchDelay: Duration()),
 );
```

**Comment by joranmulderij** [comment]
Ah yes I found that later and forgot to close the issue. Maybe consider making it the default?
