### ISSUE TITLE
Height of Button breaks.

### ISSUE THREAD

**Issue by SzymonDziak** [salim-lachdhaf/searchable_dropdown#628]
**Describe the bug**
There is no clear way to adjust the button height without breaking the selected item & hint text.

**Screenshots**
<img width="223" alt="Screenshot 2024-02-15 at 4 16 38 AM" src="https://github.com/salim-lachdhaf/searchable_dropdown/assets/7705226/babf0cf9-5324-43e8-9bc9-1d5bff23fd01">

**Comment by salim-lachdhaf** [comment]
have you a simple to reproduce the issue ?

**Comment by SzymonDziak** [comment]
The dropdown widget does not include a height parameter. To provide a reproduction, are you looking for the widget to be wrapped with a SizedBox that specifies a height field? Simply add a SizedBox and set the height to less than 50px.

**Comment by salim-lachdhaf** [comment]
No there is no need to specify a height.

Please past a reproduce example to make things clearer

**Comment by 1284115201** [comment]
I also had the same problem

**Comment by SzymonDziak** [comment]
How fucking lazy are you?  @salim-lachdhaf

**Comment by SzymonDziak** [comment]
I gave you a clear fucking reproduction. Get your shit together and stop asking for some dumbass fucking examples.
