### ISSUE TITLE
PopupPropsMultiSelection.modalBottomSheet : How to  move up ( change position ) bottom button ?

### ISSUE THREAD

**Issue by app-chain-hagio** [salim-lachdhaf/searchable_dropdown#629]
Hello. Thank you, good flutter library.
so,I want to move modalBottomSheet button to move up.
please let me know
![IMG_0576](https://github.com/salim-lachdhaf/searchable_dropdown/assets/46232359/8a0a4170-d321-49cd-b8ca-16da1501a688)

**Comment by salim-lachdhaf** [comment]
to play with multiSelection validation button you can use `validationWidgetBuilder`.

here an example : https://github.com/salim-lachdhaf/searchable_dropdown/blob/0db798a07a222435950c024abdbf8f8926798211/example/lib/main.dart#L107

**Comment by app-chain-hagio** [comment]
Thank you!
