### ISSUE TITLE
关于dropdownBuilder

### ISSUE THREAD

**Issue by hu70258tao** [salim-lachdhaf/searchable_dropdown#63]
我在dropdownBuilder里返回了一个Center-Text,并且没有使用ClearButton和DropDownButton,但是Center看起来很假.

**Comment by hu70258tao** [comment]
Do you know chinese ? i return a Center-Text in dropdownBuilder,but i does not work,always have a bloc in right.

**Comment by salim-lachdhaf** [comment]
no i don't, could you please past your code for the searchableDropdown

**Comment by salim-lachdhaf** [comment]
No response.
