### ISSUE TITLE
Customize search field in popup

### ISSUE THREAD

**Issue by potikorn** [salim-lachdhaf/searchable_dropdown#631]
I have to customize search field in popup dropdown list item.
<img width=400 src=https://github.com/salim-lachdhaf/searchable_dropdown/assets/18239662/9767b212-a899-4bba-b782-bf4b897b1680 />

I need something like searchFieldBuilder for fully customize. for example
```dart 
  DropdownSearch(
    searchFieldBuilder: (context) {} // whatever need props like other builder
    // ...rest props
  )
```

Alternative way
or at least make it more flexible to custom width height container wrapper text field it gonna be great to customize its own style

Thanks in advance 🙏

**Comment by salim-lachdhaf** [comment]
yes you can do it using `searchFieldProps` like here https://github.com/salim-lachdhaf/searchable_dropdown/blob/0db798a07a222435950c024abdbf8f8926798211/example/lib/main.dart#L395

**Comment by anwar-makhous** [comment]
@salim-lachdhaf 
how about if I want to change the height of this field for example? is that possible currently?

**Comment by nimashahahmadian** [comment]
I want to get user input text and query the search from databse how to get search onchange
