### ISSUE TITLE
how to chnage mulitiselected chip color

### ISSUE THREAD

**Issue by alyabbasi93** [salim-lachdhaf/searchable_dropdown#632]
how to chnage mulitiselected chip color

**Comment by mellowcello77** [comment]
I think the question is relating to this chip color, can't seem to find a way to edit it:

<img width="865" alt="Screenshot 2024-09-17 at 11 15 59" src="https://github.com/user-attachments/assets/de5e881e-e97d-4965-a13f-1bf0f8a54a3d">
