### ISSUE TITLE
Unwanted space at the end when the dropdown button is disabled.

### ISSUE THREAD

**Issue by nirmal-kc** [salim-lachdhaf/searchable_dropdown#634]
I am working on a scenario where I am trying to create a text dropdown without the dropdown button. The button has two values, ['gm', 
kg']. However, there is unwanted space to the right where the dropdown button previously existed. How to remove this? Below is the widget example.

`Container(
                width: 40,
                height: 40,
                color: Colors.amber,
                child: DropdownSearch<String>(
                  selectedItem: 'gm',
                  items: ['gm','kg'],
                  dropdownButtonProps: DropdownButtonProps(
                    isVisible: false,
                    icon: SizedBox.shrink(),
                    constraints: BoxConstraints(
                      maxHeight: 0,
                      maxWidth: 0,
                    ),
                  ),
                  dropdownDecoratorProps: DropDownDecoratorProps(
                    dropdownSearchDecoration: InputDecoration(
                      contentPadding: EdgeInsets.zero,
                      border: InputBorder.none,
                    ),
                  ),
                  popupProps: PopupProps.menu(),
                ),
              )`

![image](https://github.com/salim-lachdhaf/searchable_dropdown/assets/72131680/ad9e52dc-1536-4464-b782-bffca0af83ef)

**Comment by salim-lachdhaf** [comment]
a new version v6.0.0-pre will be release in the next days contains a possibility of using `dropdown` on non text widgets.
