### ISSUE TITLE
Items in GridView or Wrap

### ISSUE THREAD

**Issue by ench0** [salim-lachdhaf/searchable_dropdown#635]
**Is your feature request related to a problem? Please describe.**
I am trying to have the items in a GridView or Wrap, so I can display items as Chip. Single selection.

**Describe the solution you'd like**
Implement containerBuilder and itemBuilder to facilitate these features, or (easier for the user) have listViewProps option to wrap items or have them in multiple columns.

**Describe alternatives you've considered**
As above, containerBuilder returns widget of the entire item widgets; I tried generating the list from my main data source, but that generates non-clickable list (or at least I do not know how to assign onclick behaviour for such custom list).

**Additional context**
No additional context.

**Comment by salim-lachdhaf** [comment]
in your cas you have to use interceptCallBacks the property of popup.

attention, if you set it to true, the callbacks (onTap, onLongClick...) should be handled by you.

check in examples pages.

**Comment by shahmirzali49** [comment]
@salim-lachdhaf Can you give example how can we use GridView or Wrap widget? because where is the relation `interceptCallBacks: true ` with Custom layout (grid or wrap) ?
