### ISSUE TITLE
Cannot click button inside item (itemBuilder)

### ISSUE THREAD

**Issue by aPinix** [salim-lachdhaf/searchable_dropdown#636]
**Describe the bug**
If I have a widget structure as an item in the itemBuilder and have anything clickable, I cannot click it inside since it only triggers the click on the item row.

**To Reproduce**
1. Use An ElevatedButton() in the DropdownSearch itemBuilder param
2. Click on the ElevatedButton
3. It doesn't trigger the elevated button
4. It triggers the whole item click selection

**Expected behavior**
It would be great if I could have some interactions inside each item

**Screenshots**
![CleanShot 2024-04-19 at 23 44 48@2x](https://github.com/salim-lachdhaf/searchable_dropdown/assets/698523/b65d7e5c-4a13-489d-8f7b-183c166506be)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone/Android real device, iPhone/Android Simulators or Browser
 - OS: macOS Sonoma 14.4.1

**Comment by salim-lachdhaf** [comment]
in your cas you have to use `interceptCallBacks` the property of popup.

attention, if you set it to true,  the callbacks (onTap, onLongClick...) should be handled by you.

check in examples pages.
