### ISSUE TITLE
what are the options we have to clear selecteditems in the multiselection(in my case i have reset  button  when i press those data not disappear)

### ISSUE THREAD

**Issue by sabari7320** [salim-lachdhaf/searchable_dropdown#638]
![Screenshot_20240425-162449](https://github.com/salim-lachdhaf/searchable_dropdown/assets/94843546/7249a63a-9834-487c-bc69-0e427d07dba5)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sabari7320** [comment]
I regret for asking this question  because most of things already have in example (i think many doesn't get guidence like comments) that's why  their raising repeated questions. ok fine  i found  solution  problem of mine is:                                                         
steps:
1) paste this   final _multiKey = GlobalKey<DropdownSearchState<String>>();
2.) pass the multikey
3.)and  _multiKey.currentState?.clear();
this would be help  for who stuggling to remove all items in multiselection

**Comment by kashiflab** [comment]
> I regret for asking this question because most of things already have in example (i think many doesn't get guidence like comments) that's why their raising repeated questions. ok fine i found solution problem of mine is: steps:
> 
> 1. paste this   final _multiKey = GlobalKey<DropdownSearchState>();
>    2.) pass the multikey
>    3.)and  _multiKey.currentState?.clear();
>    this would be help  for who stuggling to remove all items in multiselection

It works 🙌
