### ISSUE TITLE
How to swap the arrow icon when menu is opened?

### ISSUE THREAD

**Issue by khaven** [salim-lachdhaf/searchable_dropdown#640]
![Capture](https://github.com/salim-lachdhaf/searchable_dropdown/assets/16809913/31191568-50d5-46b3-8f2d-fde6d215e6ff)

Hi,
How to swap the arrow icon to up and down arrow icon when menu is opened. I did not find any example code for this.

**Comment by salim-lachdhaf** [comment]
for now the arrow not changing. it's nice request i will see how to added it in next versions.
