### ISSUE TITLE
Please add an option to round the corners of the splash of dropdownButton.

### ISSUE THREAD

**Issue by khaven** [salim-lachdhaf/searchable_dropdown#642]

**Comment by khaven** [comment]
![Capture](https://github.com/salim-lachdhaf/searchable_dropdown/assets/16809913/ea0e1cb0-1a5c-46d8-8044-3cacd402c52b)
Hi,
Maybe you could put this `InkWell` on top of the `_formField()` using a `Stack` and add an option to round the corners of the `InkWell` using `ClipRRect`? currently I've found no option to round the corners of the splash of the `InkWell` to match the corners of the `_formField()`.

**Comment by salim-lachdhaf** [comment]
`ClickProps` are added in the next version 6.0.0-pre that will be released in the next days.

Stay tuned ;)
