### ISSUE TITLE
i want selected item in the dropdown(which item index i have selected i want to know because i have so many same value  names)

### ISSUE THREAD

**Issue by sabari7320** [salim-lachdhaf/searchable_dropdown#643]

**Comment by salim-lachdhaf** [comment]
if your item are primitive types then you can not to get the correct index, and i don't see in this case you have duplicated items.

if not, you can get the index of selected item in `onChanged` callback by calling for example `indexWhere((item) item.id==selectedItem.id )` . where id property is the unique identifier for your entity.

PS: if your are in first case (your items are primitives), generate a new list from your origin list in such that your new object has two properties , your value, and an index (index in original list).
