### ISSUE TITLE
Validate without close PopUp dialog

### ISSUE THREAD

**Issue by diegorkalschne** [salim-lachdhaf/searchable_dropdown#646]
Is there any way to validate the list of selected items in .multiSelection() when "onDismissed()" is called?
I want the selected items to be validated even if the user just closes PoupUp, without clicking the "Ok" button.

Programmatically, I found these two methods only:
```dart
key.currentState?.popupValidate([]);
key.currentState?.popupOnValidate();
```

In this case, it would just be not having the "closePopup()" function internally in validation.

**Comment by salim-lachdhaf** [comment]
sadly this functionnality doesn't exist, closing popup is  part of item validation.
