### ISSUE TITLE
How to change the text color of selected item?

### ISSUE THREAD

**Issue by Saibaba-Alapati** [salim-lachdhaf/searchable_dropdown#65]
<img width="669" alt="Screenshot 2020-11-09 at 10 27 17 PM" src="https://user-images.githubusercontent.com/70468046/98571621-bb912a80-22da-11eb-8591-739878a9f99d.png">

**Comment by salim-lachdhaf** [comment]
You can customize `dropdownBuilder`.

Just a note that could help: why you do not use dark theme ! Like this everything will be handled by the theme.
