### ISSUE TITLE
How to use additionalPopupWidth? 

### ISSUE THREAD

**Issue by mrchuis** [salim-lachdhaf/searchable_dropdown#654]
I need the dropdown to be wider than the parent widget. 
I read https://github.com/salim-lachdhaf/searchable_dropdown/pull/623/files 
but don't see additionalPopupWidth in PopupPropsMultiSelection.menu (dropdown_search: ^5.0.6 )

**Comment by salim-lachdhaf** [comment]
This will be possible with the version 6.0.0-pre that will be released in the next days. Just set `constraints` property of `popupProps`

Stay tuned ;)
