### ISSUE TITLE
hint text is not showing

### ISSUE THREAD

**Issue by sivabhagavathiraja** [salim-lachdhaf/searchable_dropdown#656]
dropdownDecoratorProps: DropDownDecoratorProps(
        dropdownSearchDecoration: InputDecoration(
          labelText: "Menu mode",
          hintText: "country in menu mode",))

**Comment by salim-lachdhaf** [comment]
It's not a bug.
You can test on a `textField` and you will get the same behavior.

Ideally in Flutter you cannot do this as both `hintText` and `labelText` behave in two different ways. `labelText` is shown as `hintText` as long as the user does not focus on it. As soon as the user clicks on the `TextField,` the `labelText` animates to a specific position whereas a `hintText` remains visible until the user types something.

So using labelText and hintText together, does not make any sense as the `TextField` will wipe off the hintText while animating the label.

As solution you can use `floatingLabelBehavior: FloatingLabelBehavior`
