### ISSUE TITLE
How to change the text color in dropdown items

### ISSUE THREAD

**Issue by AmarchandK** [salim-lachdhaf/searchable_dropdown#658]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by InShad7** [comment]
provide this
   
    itemBuilder: (context, item, isSelected) {
          return ListTile(
            title: Text(
              item,
              style: GoogleFonts.roboto(
                fontSize: 16.sp,
                fontWeight: FontWeight.w400,
                color: isSelected ? blue3 : black,
              ),
            ),
          );
        },
        
      
     in PopupProps.menu()

**Comment by salim-lachdhaf** [comment]
@InShad7  thnx
