### ISSUE TITLE
InkWell hover shape don't follow TextField border shape

### ISSUE THREAD

**Issue by Dartaan** [salim-lachdhaf/searchable_dropdown#659]
**Describe the bug**
InkWell hover shape don't follow TextField border shape.

**To Reproduce**
Customize TextField border shape via Theme setting or dropdownSearchDecoration.
Example: 

```dart
DropdownSearch(
      selectedItem: 'selected',
      items: const ['1', '2', '3'],
      dropdownDecoratorProps: const DropDownDecoratorProps(
        dropdownSearchDecoration: InputDecoration(
          isDense: true,
          labelText: 'label',
          border: OutlineInputBorder(
            borderSide: BorderSide.none,
            borderRadius: BorderRadius.all(Radius.circular(50)),
          ),
        ),
      ),
    );
```

**Expected behavior**
InkWell hover follow TextField border shape

**Screenshots**
actual
<img width="382" alt="image" src="https://github.com/user-attachments/assets/dd643fe0-49c3-4d16-86e7-76b42e75d4f2">

expected
<img width="378" alt="image" src="https://github.com/user-attachments/assets/d4716b31-0d15-47cf-9275-531ac4e9f272">

**Desktop (please complete the following information):**
 - OS: web
 - Browser: chrome
 - Version: 126.0.6478.127 (Official Build) (arm64)

**Additional context**
Problem line - [dropdown_search.dart:282](https://github.com/salim-lachdhaf/searchable_dropdown/blob/0db798a07a222435950c024abdbf8f8926798211/lib/dropdown_search.dart#L282)

Possible solution:
```dart
return ValueListenableBuilder<List<T?>>(
      valueListenable: _selectedItemsNotifier,
      builder: (context, data, wt) {
        final customBorder =
            widget.dropdownDecoratorProps?.dropdownSearchDecoration?.border ??
                Theme.of(context).inputDecorationTheme.border;
        return IgnorePointer(
          ignoring: !widget.enabled,
          child: InkWell(
            customBorder: customBorder,
            onTap: () => _selectSearchMode(),
            child: _formField(),
          ),
        );
      },
    );
```

**Comment by Dartaan** [comment]
https://github.com/salim-lachdhaf/searchable_dropdown/pull/660

**Comment by salim-lachdhaf** [comment]
`ClickProps` are added in the next version 6.0.0-pre that will be released in the next days.

Stay tuned ;)
