### ISSUE TITLE
Some questions regarding custom theming

### ISSUE THREAD

**Issue by cannibal-kush** [salim-lachdhaf/searchable_dropdown#66]
Hi there! Apologies for the rudimentary question.

I'm attempting to customize the color of the on-hover highlight in the popup dialog one gets when opening the searchable dropdown.

I attempted to wrap the items inside of popupItemBuilder, as well as the entire widget, with a custom Theme, but this had no effect. I believe this is because, most likely, the popup dialog is a new route and therefore inherits the app's theme.

Is there some way to achieve my desired effect of changing the color of the on-hover effect without changing my app's entire top-level theme?

TIA

**Comment by salim-lachdhaf** [comment]
If i well understood your question is that you want to customize the color of the items on the popup in onHover event.

If yes, think your solution is correct and it's the best way, just maybe you have to apply theme as theme.copy or theme.merge ....
