### ISSUE TITLE
[Question] How to align popup to end of Search field

### ISSUE THREAD

**Issue by Trung15010802** [salim-lachdhaf/searchable_dropdown#661]
I want align popup to right/end of TextFied. How can i  achive this?
![image](https://github.com/user-attachments/assets/c03dbfee-4d94-4f54-8b6c-5d658ae4e51e)

**Comment by salim-lachdhaf** [comment]
a new feature will be release in the next pre version v6.0.0-pre contains new propoerty `align` for `menuProp` .
You have just to use `align: Align.end`

Stay tuned ;)
