### ISSUE TITLE
i have fixed the example to work on flutter 3.22.2 and tested on android 34, ios and web

### ISSUE THREAD

**Issue by sk92129** [salim-lachdhaf/searchable_dropdown#662]
**Describe the bug**
Please fix the examples to work with flutter 3.22 x
I already fixed it but cannot push to a remote branch.  How do I push a remote branch and then create a PR?  Then you can decide if you want to merge the PR.

**To Reproduce**
1.) flutter pub get 
this fails because it is using old flutter.dart version

**Expected behavior**
I expect the example to work on the latest flutter sdk

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by salim-lachdhaf** [comment]
examples are updated, a new release v6.0.0-pre will be published in the next days .
