### ISSUE TITLE
onChange called while selecting the same option

### ISSUE THREAD

**Issue by Suryanshomar7240** [salim-lachdhaf/searchable_dropdown#667]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by salim-lachdhaf** [comment]
yes, onChange is called each time you select on item, whetever it's the same as old selected item or not.
onChange is the same as onSelected or onClicked.

However i see your point, will think to add `onItemSelected `, `Onchanged `(where OnChanged will be called only for new selected items)
