### ISSUE TITLE
Multiselection triggers didChange due to different reference to widget.selectedItems 

### ISSUE THREAD

**Issue by naghamsaade** [salim-lachdhaf/searchable_dropdown#668]
In the initState method:
@override
  void initState() {
    super.initState();
    _selectedItemsNotifier.value =
        isMultiSelectionMode ? List.from(widget.selectedItems) : _itemToList(widget.selectedItem);
  }
List.from(widget.selectedItems) will generate a new list. 
Hence,  _selectedItemsNotifier.value will have a different reference than the previous one.
So in this code:
Widget _formFieldMultiSelection() {
    return FormField<List<T>>(
      enabled: widget.enabled,
      onSaved: widget.onSavedMultiSelection,
      validator: widget.validatorMultiSelection,
      autovalidateMode: widget.autoValidateMode,
      initialValue: widget.selectedItems,
      builder: (FormFieldState<List<T>> state) {
        if (state.value != getSelectedItems) {
          WidgetsBinding.instance.addPostFrameCallback((_) {
            state.didChange(getSelectedItems);
          });
        }
        return ValueListenableBuilder<bool>(
            valueListenable: _isFocused,
            builder: (context, isFocused, w) {
              return InputDecorator(
                baseStyle: widget.dropdownDecoratorProps.baseStyle,
                textAlign: widget.dropdownDecoratorProps.textAlign,
                textAlignVertical: widget.dropdownDecoratorProps.textAlignVertical,
                isEmpty: getSelectedItems.isEmpty && widget.dropdownBuilderMultiSelection == null,
                isFocused: isFocused,
                decoration: _manageDropdownDecoration(state),
                child: _defaultSelectedItemWidget(),
              );
            });
      },
    );
  }
  
the if check of  if (state.value != getSelectedItems) will return true.
We should use !listEquals, used in didUpdateWidget method.

**Comment by salim-lachdhaf** [comment]
thx for issue description, the issue corrected in next version v6.0.0-pre that will be released in the next days
