### ISSUE TITLE
Add and select a new item on the go.

### ISSUE THREAD

**Issue by Vitaly-V** [salim-lachdhaf/searchable_dropdown#67]
Hello! Thank you for the great package!

I'm using the "DropdownSearch" with "onFind" and "isFilteredOnline: true" to call my API and it works awesome. 
But, I'd like to have the ability to add and select the current search string as a new item if it's not in the search results. 
E.g. autocomplete search as we have on google.
Could you give me a piece of advice on how to do it?

**Comment by salim-lachdhaf** [comment]
To do that we can follow three steps:
1) get typed text in searched box, here we will uses `emptyBuilder` or `searchBoxController` to get the text.

2) set that text as selected item, here there is only one solution, add a `GlobalKey` for the searchableDropdown and add inside `emptyBuilder` : `sdKey.currentState.setSelectedItem(your text)`

3) to add that text as an item to your list you have to declare a global `List` and insert that item inside and assign searchableDropdown `items` to that list.

Full example
```

DropdownSearch<String>
                key: _myKey,
                emptyBuilder:(context, String query){
                       return RaisedButton(
                      onPressed: () {
                        _myKey.currentState
                            .changeSelectedItem(query);
                          setState((){
                                 _myCustomItems.add(query);
                           });
                      },
                      child: Text('add and set as selected item'));
                },
                items:_myCustomItems,
                onFind: (String filter) => getData(filter),
                showSearchBox: true,
              ),
```

Check plugin examples for more options ...

**Comment by Vitaly-V** [comment]
Perfect! Thank you!

**Comment by daianaboia** [comment]
I tried this solution but for me query seems to be always null. How can i get the value I type in the searchbox?
