### ISSUE TITLE
Remove DropDown Icon

### ISSUE THREAD

**Issue by rahulinfibrain** [salim-lachdhaf/searchable_dropdown#670]
if user can add show dropdown  icon then show dropdown 
if can not added show dropdown then can not show dropdown button auto matically remove DropdownButtonProps size

now icon visibility working proper but space can not remove

**Comment by salim-lachdhaf** [comment]
please explain more

**Comment by salim-lachdhaf** [comment]
I think i understood your need.

in the new version v6.0.0-pre if `dropdownButton` et `clearButton` are both invisible, the suffix is set to null instead of empty `Row`

The new version will be released in the next days.

**Comment by PKReejesh** [comment]
Can set

`DropDownDecoratorProps(
decoration:InputDecoration(
            contentPadding: const EdgeInsets.fromLTRB(0, 8, 0, 8),
            suffixIconConstraints: const BoxConstraints(
                minWidth: 0,maxWidth: 0,
            ),)`
