### ISSUE TITLE
Label text is always on top

### ISSUE THREAD

**Issue by sunshine-ga** [salim-lachdhaf/searchable_dropdown#674]
_**Is your feature request related to a problem? Please describe.**_
Label is always on top, even if field is empty (nothing selected).

_**Describe the solution you'd like**_
Label should fill field as it is for TextField when it is empty, and when item is seleced then should go up.

_**Additional context**_
![DropdownSearch label](https://github.com/user-attachments/assets/aef607c6-5d58-41a8-a672-b18d0651fdad)

**Comment by salim-lachdhaf** [comment]
could you paste a simple example for the issue ?

**Comment by sunshine-ga** [comment]
Sorry 🙈 It is my fault.... 🤦🏻‍♀️ for selected item I had empty string instead of null... Topic closed.
