### ISSUE TITLE
Exception on version 6.0.0

### ISSUE THREAD

**Issue by virdosdo** [salim-lachdhaf/searchable_dropdown#675]
**Describe the bug**
Exception has occurred.
_AssertionError ('package:dropdown_search/dropdown_search.dart': Failed assertion: line 188 pos 16: 'T == String || T == int || T == double || compareFn != null': is not true.)

**To Reproduce**
On loading the form with the DropdownSearch widget

**Expected behavior**
The search dropdown display with the elements

**Screenshots**
Attached screen
![error_dropdown](https://github.com/user-attachments/assets/56d33264-f122-4ef7-abf2-219f2bbb79c7)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser [e.g. chrome, safari] flutter 3.24.2 -  app compiled in debug on windows

**Smartphone (please complete the following information):**

**Additional context**
I use a special model, with id and name structure for items. This worked fine before the package update to 6.0.0.

**Comment by salim-lachdhaf** [comment]
i's not a bug, it's just a way to force users to specify their model `DropdownSearch<MyModel>` or `DropdownSearch<MyModel>.multiSelection` if they uses custom models

**Comment by virdosdo** [comment]
Excelent!
I solved it with: compareFn: (item1, item2) => item1.id == item2.id
Sorry for the inconvenience, I didn't know that the compareFn statement was required.
Thank you so much
