### ISSUE TITLE
Add keyboard support for dropdown list

### ISSUE THREAD

**Issue by sunshine-ga** [salim-lachdhaf/searchable_dropdown#676]
**Is your feature request related to a problem? Please describe.**
It will be nice to add keyboard support for widget. It will be helpful for desktop applications.

**Describe the solution you'd like**
- firstly to set focus on search field after opening dropdown
- then handle up and down keys to move on list
- Enter/Tab for confirm selection

**Alternatives**
I don't know if it is possible to manually handle keyboard actions outside of DropdownSearch?

**Comment by salim-lachdhaf** [comment]
To search from dropdown, you have just use `Tab` and `space` (tested on widows).
Tab to navigate between widgets and `space` to click
