### ISSUE TITLE
Remove deprecated HitTestBehavior prop from CustomScrollView

### ISSUE THREAD

**Issue by cmaccarone** [salim-lachdhaf/searchable_dropdown#677]
**Describe the bug**
Failed to build iOS app
Error (Xcode):
../../../../.pub-cache/hosted/pub.dev/dropdown_search-6.0.0/lib/src/widgets/custom_scroll_view.dart:21:7:
Error: No named parameter with the name 'hitTestBehavior'.

Could not build the application for the simulator.
Error launching application on iPhone 15 Plus.

**To Reproduce**
Build the widget with Flutter >= 3.22.2

Flutter Doctor:
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.6.1 23G93 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/calebmaccarone/fvm/versions/3.22.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

**Expected behavior**
I was not able to build the widget without removing the deprecated hitTestBehavior from the widget.

**Screenshots**
<img width="754" alt="Screenshot 2024-09-19 at 7 45 28 AM" src="https://github.com/user-attachments/assets/d06a7d92-555e-462c-84c4-4cce645dffe3">

**Desktop (please complete the following information):**
 - OS: Sonoma 14.6.1

**Comment by cmaccarone** [comment]
@salim-lachdhaf  can I submit a PR to fix this? This package wont work for me on latest flutter because of this.

**Comment by salim-lachdhaf** [comment]
it's not deprecated, your Flutter version is not uptodate that's all ;)

this is mine for example which is higher then your version
```
[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [version 10.0.22631.4169], locale fr-FR)
    • Flutter version 3.24.2 on channel stable at D:\SDK\Flutter_lastest
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (2 weeks ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2
```

**Comment by cmaccarone** [comment]
haha omg thanks
