### ISSUE TITLE
Use flutter bloc handle state to search or loading...

### ISSUE THREAD

**Issue by MrLongg71** [salim-lachdhaf/searchable_dropdown#680]
**Is your feature request related to a problem? Please describe.**
How to use flutter_bloc to handle state loading, success in showing loading, loading bottom when loading paging or re-render list, etc?
I listened to the success state to call `updatePopupState()` but the state did not re-render new items b/c `items` function did not trigger again.

`items: (f, cs) async {
        if ((f ?? '').isNotNullOrEmpty) {
          print('=== onSearch $f ${cs?.skip}');
          widget.onSearch?.call(f);
        }
        // await Future.delayed(Duration(seconds: 2));
        return  _items;
}`

**Comment by MrLongg71** [comment]
<img width="643" alt="image" src="https://github.com/user-attachments/assets/be877c8e-a9ce-4d2f-b91c-d56f5d2cb5bc">

**Comment by salim-lachdhaf** [comment]
i'm not a `bloc` fan, so dadly i can't help you in this subject.
some note from the pasted code:

- `f` is not `nullable` so you don't have to use  `(f ?? '')` neither `.isNotNullOrEmpty` `.isEmpty` will do the job
- you marked `items` as `async,` however you are not waiting for anything (maybe you shoud add `await widget.onSearch.call(f)` ?)
- what's `_items` ?

**Comment by MrLongg71** [comment]
> i'm not a `bloc` fan, so sadly i can't help you in this subject. some note from the pasted code:
> 
> * `f` is not `nullable` so you don't have to use  `(f ?? '')` neither `.isNotNullOrEmpty` `.isEmpty` will do the job
> * you marked `items` as `async,` however you are not waiting for anything (maybe you shoud add `await widget.onSearch.call(f)` ?)
> * what's `_items` ?

Thanks for your feedback.
Let me try.
