### ISSUE TITLE
6.0.1 Error hitTestBehavior: scrollProps.hitTestBehavior, 

### ISSUE THREAD

**Issue by tiltmaster** [salim-lachdhaf/searchable_dropdown#686]
So I have found this plugin that seemed promising to what i wanted, sadly, upon getting the latest version i was encountered with a error, downgrading to 6.0.0 results in the same, running flutter clean did not fix the issue as well.

See attached Image:

![ffs](https://github.com/user-attachments/assets/cdee5f68-2643-4602-9326-68a1a67fed76)

am I missing something?

**Comment by salim-lachdhaf** [comment]
Just update your flutter version using `flutter upgrade ` cmd.

**Comment by salim-lachdhaf** [comment]
Please don't hesitate to star the repo and the lib if it's useful for you.
