### ISSUE TITLE
asyncItems run once(Web)

### ISSUE THREAD

**Issue by ErsinMandaci** [salim-lachdhaf/searchable_dropdown#688]
asyncItems only works when I click first. How do I do this, according to the query I entered, I want to continuously send requests to the service and fill the searchDropdown?

**Comment by salim-lachdhaf** [comment]
if you are using a version < 6.0.0 , use `isFilterOnline = False` in `popupProps`

**Comment by ErsinMandaci** [comment]
Thank you for the short turnaround time. Resolved.

**Comment by salim-lachdhaf** [comment]
Your issue has been closed. If we were helpful don't forget to star the repo and the package [here](https://pub.dev/packages/dropdown_search).

**Comment by salim-lachdhaf** [comment]
@nathielileal you have just to use `cacheItems  = true` instead

please don't hesitate to star the repo if it's useful for you.
