### ISSUE TITLE
App breaks in channel beta - No named parameter shadowThemeOnly

### ISSUE THREAD

**Issue by Theunodb** [salim-lachdhaf/searchable_dropdown#69]
Getting this error when trying to run the app in beta flutter channel:

```
    ../../../.pub-cache/hosted/pub.dartlang.org/dropdown_search-0.4.6/lib/src/popupMenu.dart:611:32: Error: No named parameter with the name 'shadowThemeOnly'.
          theme: Theme.of(context, shadowThemeOnly: true),
```

As an interim fix i removed the extra part until the fix has been implemented:

In the popupMenu.dart line 611 change this
```
theme: Theme.of(context, shadowThemeOnly: true),
```
to this:
```
theme: Theme.of(context),
```

**Comment by salim-lachdhaf** [comment]
thank you for rapporting that, we already added this changes in the next version.
