### ISSUE TITLE
On error request data again

### ISSUE THREAD

**Issue by Vitaly-V** [salim-lachdhaf/searchable_dropdown#70]
Hello!

I'm using "onFind" and I'd like to have the ability to request data again if an error occurred during the latest request.
I assume that "errorBuilder" can be used, but how to call "onFind" from there?

Thanks in advance!

**Comment by salim-lachdhaf** [comment]
I suggest to call build method using the globalkey for the searchable dropdown inside the errorBuilder

**Comment by Vitaly-V** [comment]
@salim-lachdhaf do you mean something like this?
```dart
         errorBuilder: (BuildContext context, String message, dynamic errorMessage) {
              return Center(
                child: FloatingActionButton(
                  child: const Icon(
                    Icons.refresh,
                    color: Colors.white,
                  ),
                  onPressed: () => _dsKey.currentState.build(context),
                ),
              );
          },
```
If so,  it doesn't work for me.

Thank you!

**Comment by salim-lachdhaf** [comment]
In fact in your case, onFind (filterOnline true) will be called each time you change text inside the searchBox, why the need for extra effort ?

**Comment by Vitaly-V** [comment]
I was thinking that a user could be typing and get an error e.g. "no network connection" and I suppose that he will stop typing and will be frustrated. That is why I'd like to provide him with additional "refresh" action.

**Comment by salim-lachdhaf** [comment]
Ok i see, you can play on the given solution , you can remove the last char or any other idea like:
```
String originalText = searchBoxController.text ;
searchBoxController.text ='###';
searchBoxController.text =originalText;
```

**Comment by Vitaly-V** [comment]
```dart
onPressed: () => _controller.text = _controller.text.substring(0, _controller.text.length - 1),
```
Updating the controller value was one of the first things I tried. This code updates the text in the search field but doesn't call the "onFind" method.
Thank you for your help and time. I appreciate it!
I'll try to figure out, and if I succeed, I'll share my solution here.

**Comment by salim-lachdhaf** [comment]
No, changing text will re call `onFind` if the `isFiltredOnline = true`, try and tell me, i do not use subtring to prevent error if text is empty !

```
String originalText = searchBoxController.text ;
searchBoxController.text ='###';
searchBoxController.text =originalText;
```

**Comment by Vitaly-V** [comment]
On the GIF below you can see the behavior. I put such a huge delay on purpose to show how it works.
It seems that "onFind" starts working only if I start typing and don't react on the _controller update.

```dart
onPressed: () async {
      final String originalText = _controller.text;
      _controller.text = '#############';
      await Future.delayed(const Duration(milliseconds: 1000), () => _controller.text = originalText);
}),
```

![IMG-0127TRIM](https://user-images.githubusercontent.com/4039270/99850000-3bde4800-2b85-11eb-9ec1-17a84e17066d.gif)

**Comment by salim-lachdhaf** [comment]
That weired, did you tried just call setState instead for that solution for now ?

**Comment by Vitaly-V** [comment]
Yes, I did.

**Comment by salim-lachdhaf** [comment]
It seems the controller not calling the onChange method of the searchBox which is weired, i have to check that and manage that in the next version.

Let me know for any idea

**Comment by rizkitroy** [comment]
helo salim ,

I use this dropdown_search, 
i used this library enough normally, but when i want to set change set selected item, i can't , not make changes in dropdown , i already setstate,
can u help how to set seleted item in dropdownsearch

`
new Container(
              padding: EdgeInsets.all(5),
              child: isloading==true ? Center(child: CircularProgressIndicator(),) : DropdownSearch<String>(
                  validator: (v) => v == null ? "required field" : null,
                  hint: "Choose",
                  mode: Mode.MENU,
                  showSelectedItem: true,
                  showSearchBox:true,
                  items: list,
                  label: "Choose",
                  
                  // showClearButton: true,
                  onChanged: (value){
                     //print(value); 
                     selected=value;
                     setState(() {
                       valitem="All";  
                     });
                     
                  },
                  selectedItem: selected,
                  
                ),
            ),
            Divider(),
            new Container(
              padding: EdgeInsets.all(5),
              child: new SizedBox(
                width: double.infinity,
                height: 20,
                child: new RaisedButton(
                    padding: EdgeInsets.all(2),
                    color: Colors.grey[400],
                    shape: new RoundedRectangleBorder(
                      borderRadius: new BorderRadius.circular(2.0),
                    ),
                    child: Text(
                      "OR",
                      style: TextStyle(color: Colors.white, fontSize: 10),
                    ),
                    onPressed: () {
                    }),
              ),
            ),
            new Container(
              padding: EdgeInsets.fromLTRB(5, 0, 5, 0),
              child: new DropdownButtonHideUnderline(
                
                child: new DropdownButton(
                  hint: Text("All"),
                  
                  value: valitem,
                  items: dataSpc.map((item) {
                    return new DropdownMenuItem(
                      child: new Text(
                        item['item'],
                        style: TextStyle(fontSize: 14),
                      ),
                      value: item['item'],
                    );
                  }).toList(),
                  onChanged: (_value) => {
                    setState(() {
                      valitem = _value.toString();
                      selected="all";
                    })
                  },
                
                ),
              ),
            )

`

Thanks for your help

**Comment by salim-lachdhaf** [comment]
you can set selected item programmatically without need to use setState.
see here https://github.com/salim-lachdhaf/searchable_dropdown/issues/75

like this : `_ddKey.currentState.changeSelectedItem(selected);`

there is an example in plugin's examples to this case.
make sure that you are using the last version.
