### ISSUE TITLE
AutoValidateMode is not defined 

### ISSUE THREAD

**Issue by kibuh** [salim-lachdhaf/searchable_dropdown#71]
I get this error when I import and run the library
../lib/dropdown_search.dart:116:9: Error: Type 'AutovalidateMode' not found.
  final AutovalidateMode autoValidateMode;
        ^^^^^^^^^^^^^^^^

**Comment by kibuh** [comment]
I fixed the error and I will making a pull request

**Comment by kibuh** [comment]
[#72 ](https://github.com/salim-lachdhaf/searchable_dropdown/pull/72) solves the issue, awaiting for a merge.

**Comment by salim-lachdhaf** [comment]
This not a bug , it a breaking change since version v0.4.5 [changelog](https://pub.dev/packages/dropdown_search/changelog#045---20201021).

Please make sure that your are using last plugin version and last stable flutter sdk.
