### ISSUE TITLE
Severe border corruption after first dropdown usage in Flutter Web 1.24.0-10.2.pre (beta channel)

### ISSUE THREAD

**Issue by slavap** [salim-lachdhaf/searchable_dropdown#74]
It was ok in 1.23, but in 1.24 started to produce screen garbage.
Affects any form widget after first dropdown usage (even textfields).
Corruption occurs only with default renderer, if --dart-define=FLUTTER_WEB_USE_SKIA=true then works fine.

![image](https://user-images.githubusercontent.com/4129763/99918943-2d9c4300-2ccf-11eb-9b58-f7a81d3f11f5.png)

[dd_bug.zip](https://github.com/salim-lachdhaf/searchable_dropdown/files/5580504/dd_bug.zip)

**Comment by salim-lachdhaf** [comment]
Is this only for this plugin or for any other widget ?

**Comment by slavap** [comment]
@salim-lachdhaf Only this one, see attached reproducible case.

**Comment by salim-lachdhaf** [comment]
And if you remove the dropdownSearch and replace with another textField, it gone ?

**Comment by slavap** [comment]
@salim-lachdhaf Yes, removing dropdown cures the problem.

**Comment by slavap** [comment]
@salim-lachdhaf any luck with figuring it out?

**Comment by salim-lachdhaf** [comment]
Sadly i did not found enough time to check it , but sure for 98% that is not related to the plugin it self. There another widget (flutter widget) used in the plugin causing problem. And it causes problem even outside the plugin itself.
https://github.com/flutter/flutter/issues/70980#issuecomment-733819157

**Comment by salim-lachdhaf** [comment]
After checking and user experience, this issue is related to flutter not the plugin.
Please chek this : https://github.com/flutter/flutter/issues/70980#issuecomment-733819157
