### ISSUE TITLE
Cannot clear the selected value outside the searchable_down (For example on clicking a Raised button)

### ISSUE THREAD

**Issue by mrazaimtiaz** [salim-lachdhaf/searchable_dropdown#75]

**Comment by mrazaimtiaz** [comment]
Actually searchable_dropdown provided a value argument. but its not using that. instead its using its own inner functions.
please reply to this. your comments are highly appreciated

**Comment by slavap** [comment]
@mrazaimtiaz 
What about: _ddKey.currentState.changeSelectedItem(null) ?

**Comment by salim-lachdhaf** [comment]
@mrazaimtiaz since the version 0.4.6 you can do that as mentioned @slavap . You can find more useful examples in plugin examples page.

**Comment by marko-mlinarevic** [comment]
I cannot pass null anymore, and empty string doesn't clear it

**Comment by slavap** [comment]
@marko-mlinarevic 
GlobalKey<DropdownSearchState<T?>> key = ...

Add ? to your type.

**Comment by marko-mlinarevic** [comment]
thanks
