### ISSUE TITLE
The dropdownBuilder does not use new selectedItem on setState()

### ISSUE THREAD

**Issue by JoshuaSardinha** [salim-lachdhaf/searchable_dropdown#79]
I am using the DropdownSearch to build a location selection with Countries, States, and Cities. There is one Dropdown for each.

The states of the selected country, the selected country_state, and the selected city are in the outer widget. When a new country is selected, the selected country_state should be reset to a standard "no state" placeholder, since that previously selected state does not belong to the newly selected country.

However, when the widget tree is rebuilt with the newly selected country_state (the placeholder), the dropdownBuilder method receives, as input, the old selected country_state, even if the DropdownSearch is rebuilt with the selectedItem as the newly selected country_state.

As a bonus, I also believe the 'dropdownBuilder' and 'popupItemBuilder' are reversed, at least in the 'Mode.BOTTOM_SHEET'. The 'readme' states that the 'dropdownBuilder' customizes the list of items UI, but it actually is customizing the selected item UI. On the other hand, the 'readme' also states that the 'popupItemBuilder' customizes the selected item, but it actually customizes the items on the list.

Thank you!

**Comment by salim-lachdhaf** [comment]
To set a new selectedItem you don't have to use setState , we created a method more efficient to handle that.
You can use globalKey to set a new selectedItem programmatically (set to null if you want to clear it).
Example : 
```
_globalKey.currentState
                            .changeSelectedItem("Blabla");
```
You can find more examples in plugin example folder.

For the note, we will fix that in the next release , thank you
