### ISSUE TITLE
How to disable item in list?

### ISSUE THREAD

**Issue by leanhro2812** [salim-lachdhaf/searchable_dropdown#8]
I want when I open Dropdown, the disabled items will be gray and will not be selectable?

**Comment by salim-lachdhaf** [comment]
Here you have to customize `popupItemBuilder` for something like this:
```

class User{
    String name;
    bool enabled;
}

DropdownSearch<User>(
  label: "Name",
  onFind: (String filter) => getData(filter),//or items if you are working offline
  itemAsString: (User u) => u.name,
  onChanged: (User data) => print(data),
  popupItemBuilder: _popupItemBuilderExample,
),

Widget _popupItemBuilderExample(BuildContext context, User item, bool isSelected) {
    return ListTile(
          enabled: item.enabled,
          title: Text(item.name),
    );
}
```

**Comment by leanhro2812** [comment]
> Here you have to customize `popupItemBuilder` for something like this:
> 
> ```
> 
> class User{
>     String name;
>     bool enabled;
> }
> 
> DropdownSearch<User>(
>   label: "Name",
>   onFind: (String filter) => getData(filter),//or items if you are working offline
>   itemAsString: (User u) => u.name,
>   onChanged: (User data) => print(data),
>   popupItemBuilder: _popupItemBuilderExample,
> ),
> 
> Widget _popupItemBuilderExample(BuildContext context, User item, bool isSelected) {
>     return ListTile(
>           enabled: item.enabled,
>           title: Text(item.name),
>     );
> }
> ```

Thanks for your answer.
But  disabling only works on UI
They are still clickable as usual :(

**Comment by salim-lachdhaf** [comment]
Use `IgnorePointer `Widget:

```
return IgnorePointer(
     ignoring: !item.enabled,
     child: ListTile(
          enabled: item.enabled,
          title: Text(item.name),
    ),
);
```

**Comment by leanhro2812** [comment]
> Use `IgnorePointer `Widget:
> 
> ```
> return IgnorePointer(
>      ignoring: !item.enabled,
>      child: ListTile(
>           enabled: item.enabled,
>           title: Text(item.name),
>     ),
> );
> ```

Tks . salim-lachdhaf
But it still doesn't work as expected,
I tried that way before you suggested :(

**Comment by salim-lachdhaf** [comment]
that's right, because the custom `popupItemBuilder` is inside `InkWell`.

 ```
return InkWell(
    child: widget.itemBuilder(
    context,
  .....
),
```

i will add that as new feature, so the item popupItemBuilder  will take a new parameter `enabled`

**Comment by leanhro2812** [comment]
Thank you for your support
I really need this feature right now
It will be very happy if you update it as soon as possible
one more time thank you very much :)

**Comment by salim-lachdhaf** [comment]
check for updated version 0.4.2, here how to use :

```
DropdownSearch<String>(
                hint: "Select a country",
                showSelectedItem: true,
                items: ["Brazil", "Italia", "Tunisia", 'Canada'],
                label: "Country",
                showClearButton: true,
                onChanged: print,
                popupItemDisabled: (String s) => s.startsWith('C'), //disable canada
                selectedItem: "Tunisia",
              ),
```

**Comment by leanhro2812** [comment]
Yup! Thank you very much :)
