### ISSUE TITLE
Error: Type 'AutovalidateMode' not found.

### ISSUE THREAD

**Issue by RaviGaruda** [salim-lachdhaf/searchable_dropdown#80]
Compiler message:

/C:/Sdk/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-0.4.8/lib/dropdown_search.dart:116:9: Error: Type 'AutovalidateMode' not found.

  final AutovalidateMode autoValidateMode;

**Comment by RaviGaruda** [comment]
even i'm using latest version  ^0.4.8 but still got this error

**Comment by Kiplangatdan** [comment]
I am getting the same error. (See attached screenshot)
![image](https://user-images.githubusercontent.com/4799405/101461989-aeed0a00-394c-11eb-95cc-a18fdad8b2c5.png)

**Comment by Kiplangatdan** [comment]
Issue solved by upgrading to the latest stable version of flutter: `1.22.4`

**Comment by salim-lachdhaf** [comment]
Yes, as @Kiplangatdan said , `autovalidateMode` is a flutter class, and it is availble only in the lastest versions, please make sure that your updating your flutter sdk
