### ISSUE TITLE
 Problem with DropdownSearch using TabBarView

### ISSUE THREAD

**Issue by cmregazzo** [salim-lachdhaf/searchable_dropdown#82]
Good afternoon,

I'm using DropdownSearch on my APP, which I'm using TAB's through TabBarView.

When switching TAB, and going back to the previous TAB, the information that was selected in DropdownSearch "disappears".

I select the information in DropdownSearch again, changing TAB, when I go back to TAB where DropdownSearch is, the information just disappeared.

Follows video demonstrating the problem.

https://www.loom.com/share/b87eb59f87de4ec29a1bd8e0e1687bce?sharedAppSource=personal_library

What am I doing wrong?

Thank you very much and congratulations for the work.

**Comment by salim-lachdhaf** [comment]
Yes you missed to keep the state when switching between tabs, it's not the problem of the plugin.

Follow this links
https://github.com/flutter/flutter/issues/19116

Or 
https://stackoverflow.com/questions/49087703/preserving-state-between-tab-view-pages
