### ISSUE TITLE
feature request: showDropdownButton and textalign

### ISSUE THREAD

**Issue by dmoeyers** [salim-lachdhaf/searchable_dropdown#83]
Hello,

first of all: great package, I love it!

Would you consider adding some extra styling options?
- a showDropdownButton just like the showClearButton so we can disable the dropdown button all together
- possibility to also specify the textalign of the dropdown. This can be down with the dropdownbuilder currently, but it would make the code cleaner

Many thanks for considering!

**Comment by salim-lachdhaf** [comment]
What is the need to add showDropdownButton and you have possibility to custom it as you want , so you can make it a Visibilty widget ?

I prefer to keep dropDownBuilder to keep things generic and prevent a loot of parameters

**Comment by dmoeyers** [comment]
Thank you for your feedback and I understand your reasoning regarding the dropDownBuilder.

For the showDropdownButton: this has to do with layout. I would like center the text in the dropdown.  But because the iconButton for the dropdownbutton is always there, the text is offset from the center. I tried your suggestion with the Visibility widget, but it's still the same because of the iconButton being still present...

See the screenshot below:
- on the left your normal widget with a Visibility widget
- on the right with your code adapted to not show the iconButton
![Screenshot_20201210-232010](https://user-images.githubusercontent.com/22577819/101836904-80368580-3b3e-11eb-8b43-508e77c605d4.jpg)

**Comment by salim-lachdhaf** [comment]
Your need makes ux very bad, how the user will know it is even a dropdown !

**Comment by dmoeyers** [comment]
They don't need to know, they will see it right away when they click the
text.
It's similar as the datepickers where you have a textfield. You click the
textfield and the datepicker opens.
Here you click the textfield and you have a popup where you can select a
value (it's not even a real dropdown like on the web where the dropdown is
connected to the textfield...)

Op do 10 dec. 2020 om 23:40 schreef Salim Lachdhaf <notifications@github.com

**Comment by salim-lachdhaf** [comment]
This feature will be availabe in the next version
