### ISSUE TITLE
Menu doesn't adjust on screen rotation or form location changes

### ISSUE THREAD

**Issue by danjenson** [salim-lachdhaf/searchable_dropdown#84]
There are two situations in which the menu does not reset when the underlying form changes.

1. Screen rotation:
![Screenshot_20201224-005340.jpg](https://user-images.githubusercontent.com/4793438/103076755-51c79a00-4583-11eb-9e9d-0bfba2837580.jpg)
![Screenshot_20201224-005357.jpg](https://user-images.githubusercontent.com/4793438/103076770-58561180-4583-11eb-87d9-cbef2c43fba8.jpg)

2. Adjustment of form due to keyboard retraction:

![Screenshot_20201224-005408.jpg](https://user-images.githubusercontent.com/4793438/103076797-60ae4c80-4583-11eb-8af5-340046c8a66f.jpg)
![Screenshot_20201224-005413.jpg](https://user-images.githubusercontent.com/4793438/103076801-62781000-4583-11eb-931b-ca32d33179a4.jpg)

**Comment by vasilich6107** [comment]
@danjenson @salim-lachdhaf 
I'm not sure that this has an easy fix

I tried the flutter sample 
https://api.flutter.dev/flutter/material/DropdownButton-class.html

it has the same bugs

**Comment by ChanakaDev** [comment]
@danjenson How do you customized the dropdown box color?

**Comment by salim-lachdhaf** [comment]
bug will be corrected in the next version v4.0.0
