### ISSUE TITLE
How to - Change icon/color of the down icon trailing on the dropdown field?

### ISSUE THREAD

**Issue by Z3rolive** [salim-lachdhaf/searchable_dropdown#85]
Is there any way to replace or change down icon trailing on the dropdown field? I am having trouble changing the color of icon on the dropdown trailing and I cannot rely on theme because I am trying to use it on the appbar.

**Comment by salim-lachdhaf** [comment]
you can use 'dropDownButton' to override the whole widget of icon , like that you could customize it as you want ;)
