### ISSUE TITLE
How to change the value of selected item ?

### ISSUE THREAD

**Issue by PjoterKacprzak** [salim-lachdhaf/searchable_dropdown#87]
is it possible to switch language like i am trying in the video ?
in "default" dropdown menu, there is property "value", which does the job.

https://user-images.githubusercontent.com/48458857/103480002-e034ea80-4dd1-11eb-96bf-e569d743c7a3.mp4

**Comment by salim-lachdhaf** [comment]
to select default value (initiale Value) , you can use `selectedItem`.
to change the selected value programmatically you can follow this anwser:
https://github.com/salim-lachdhaf/searchable_dropdown/issues/75

you can find also more examples in plugin examples source code similar to you case.
