### ISSUE TITLE
[Help] Why my filter is not working?

### ISSUE THREAD

**Issue by fabiojansenbr** [salim-lachdhaf/searchable_dropdown#9]
Hi, im trying to filter itens from an api, but when i search, always return null.

Im using a :

```
DropdownSearch<Estados>(
                mode: Mode.DIALOG,
                popupItemBuilder: _customPopupItemBuilderExample,
                maxHeight: 300,
                label: "Escolha Estado",
                onFind: (String filter) => getData(filter),
                onChanged: print,
                showSearchBox: true,
                searchBoxDecoration: InputDecoration(
                  border: OutlineInputBorder(),
                  contentPadding: EdgeInsets.fromLTRB(12, 12, 8, 0),
                  labelText: "Busque Estado",
                ),
                popupTitle: Container(
                  height: 50,
                  decoration: BoxDecoration(
                    color: Theme.of(context).primaryColorDark,
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(20),
                      topRight: Radius.circular(20),
                    ),
                  ),
                  child: Center(
                    child: Text(
                      'Estados',
                      style: TextStyle(
                        fontSize: 24,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
                popupShape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(24),
                    topRight: Radius.circular(24),
                  ),
                ),
              ),
              Divider(),
```
An when i click on the Dropdown, the items from API are loaded. Im using:

```
Future<List<Estados>> getData(filter) async {
    final headers = {
      'contentType': 'application/json',
      'X-Parse-Application-Id': '',
      'X-Parse-REST-API-Key': ''
    };

    var response = await Dio().get(
      "https://hxxxx/classes/Estadoscidadesbrasil_StateProvince/",
      options: Options(headers: headers),
    );

    var models = Estados.fromJsonList(response.data['results']);
    return models;
  }
```

My api dont have any way to filter on the URL.

How can i filter?

**Comment by salim-lachdhaf** [comment]
Because here you did not neither ovverided `toString` or specify `itemAsString` for the `Estados` object (https://pub.dev/packages/dropdown_search#attention).

For custom filtrer you can use `filterFn` for more details check plugin examples .

Let me know if it works for you.

**Comment by leanhro2812** [comment]
Hi Fab ..
You can use isFilteredOnline: true, (current version 0.4.2)
then the "filter"  in your getData(filter) function will is"keyword" as changes from the search field.
Would you use it to request the API with something like this:
"https: // hxxxx / classes / Estadoscidadesbrasil_StateProvince? keyword = $ filter",

**Comment by leanhro2812** [comment]
Hi Fab ..
You can use isFilteredOnline: true, (current version 0.4.2)
then the "filter" in your getData(filter) function will is"keyword" as changes from the search field.
Would you use it to request the API with something like this:
"https: //hxxxx/classes/Estadoscidadesbrasil_StateProvince?keyword=$filter"

DropdownSearch(
    isFilteredOnline: true,
    onFind: (String filter) => getData(filter)
}

Future<List> getData(filter) async {
    final headers = {
        'contentType': 'application/json',
        'X-Parse-Application-Id': '',
        'X-Parse-REST-API-Key': ''
   };

  var response = await Dio().get(
     "https://hxxxx/classes/Estadoscidadesbrasil_StateProvince?keyword=$filter",
      options: Options(headers: headers),
    );

  var models = Estados.fromJsonList(response.data['results']);
  return models;
}

**Comment by salim-lachdhaf** [comment]
Yes that's correct but he say that his api has no filter, so he is force to filter localy and no need for `isFilteredOnline` to prevent loading data each time after entring you keyword.

You have a tone of possiblity to filter:
 **_Filter online_**:
 Just enable `isFilteredOnline` (don't forget to pass the keyword to your API)

-**_Local filter:_**
If you are working with models not Strings, you have to ovverride `toString` or use a custom toString function by calling `itemAsString` and the filter will be applied on `itemAsString` ,  if you want to filter forther more on other attribute that are not defined in `itemAsString` you can use `filterFn` to define your custom filter.

-**_filter online and localy_**
Using both filter togther

**Comment by leanhro2812** [comment]
Yes, if his api dont have any way to filter on the URL.
then I think he should save his data into a variable and use that variable with: items: data 
^_^
I am in the same situation as him.
I can use :
items: widget.data
But I don't use items and I've used onFind with:
Future<List> getData(filter) async {
    return widget.data;
}
Do not forget : itemAsString: (item) => itemAsString(item),
Both ways work well
so I can be more active at inputting available data or get online

**Comment by salim-lachdhaf** [comment]
You don't have to save your data into variable (if you don't need them somewhere else), because if not `isFilterOnlie` then the plugin by itself load the data once and do not reload data from api in searching.
Another thing, you can use online and offline items together , `items` and `onFind`

**Comment by leanhro2812** [comment]
> Another thing, you can use online and offline items together , items and onFind

nếu items và onFind đều là có dữ liệu nhưng có cùng cấu trúc thì khi tiến hành tìm kiếm thì dữ liệu được tìm thấy là gì ?
Có phải là của cả items và onFind ?

**Comment by leanhro2812** [comment]
> Another thing, you can use online and offline items together , items and onFind

If items and onFind are both has data but have the same structure, when searching, what is the found data?
Is it for in both items and onFind?

**Comment by salim-lachdhaf** [comment]
It SHOULD online and offline data are the same model type.

If it's the case, they will be merged into a single list (behind the scene) and nothing changes , justjustas as you are using just `items` or `onFind`, by searching you will get your result from that merged list whatever it is origin :)

This is an example from the dropdownSearch example:
https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart

```
///merge online and offline data in the same list and set custom max Height
              DropdownSearch<UserModel>(
                items: [
                  UserModel(name: "Offline name1", id: "999"),
                  UserModel(name: "Offline name2", id: "0101")
                ],
                maxHeight: 300,
                onFind: (String filter) => getData(filter),
                label: "choose a user",
                onChanged: print,
                showSearchBox: true,
              ),
```

**Comment by fabiojansenbr** [comment]
> Because here you did not neither ovverided `toString` or specify `itemAsString` for the `Estados` object (https://pub.dev/packages/dropdown_search#attention).
> 
> For custom filtrer you can use `filterFn` (optional) for more details check plugin examples .
> 
> Let me know if it works for you.

Thanks, works like expected. My fault to not read the instructions carefully. Thanks
