### ISSUE TITLE
The filter parameter of onFind is always empty

### ISSUE THREAD

**Issue by meysammahfouzi** [salim-lachdhaf/searchable_dropdown#91]
Why is the `filter` parameter of `onFind` always empty? I noticed that when `showSearchBox` is set to `true`, the search functionality works automatically on the data returned by `onFind`. Then I don't understand the usage of the `filter` parameter and why it's always empty.

**Comment by salim-lachdhaf** [comment]
it's not alawys empty unless you did not change the text in the searchBox.

you can ovveride the onFind function (see plugin examples) based on the search keyword.

like `onFind:(String keyword)=> myCustomFilter(keyword)`
