### ISSUE TITLE
How to dynamically clear the dropdown

### ISSUE THREAD

**Issue by artoniaz** [salim-lachdhaf/searchable_dropdown#92]
Hey, 

I'm having issue with having the dropdown cleard dynamically. 
I need it to be dynamic, dependend on other fields. My second issue is that when the values change label doesn't clear despite getting null as selectedItem. 

Hope you have soulution for this.

**Comment by salim-lachdhaf** [comment]
1- you can follow this anwser https://github.com/salim-lachdhaf/searchable_dropdown/issues/87 , however you can use a globalKey and manage your selectedItem (check plugin last examples)

2- you can use `dropdownBuilderSupportsNullItem`
```
 ///If true, the dropdownBuilder will continue the uses of material behavior
  ///This will be useful if you want to handle a custom UI only if the item !=null
```
