### ISSUE TITLE
Rendering bug with new flutter versions

### ISSUE THREAD

**Issue by Omar-Abdalqader** [salim-lachdhaf/searchable_dropdown#95]
The dropdown menu has rendering issue with new flutter versions, I have tested the library with 2 flutter versions:

1. v 1.22.1: it works well with this version.
2. v 1.24.0-10.2.pre: it has the bug. Below you can find a screenshot of the issue and the flutter doctor of this version.

> [√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
>     • Flutter version 1.24.0-10.2.pre at C:\src\flutter
>     • Framework revision 022b333a08 (8 weeks ago), 2020-11-18 11:35:09 -0800
>     • Engine revision 07c1eed46b
>     • Dart version 2.12.0 (build 2.12.0-29.10.beta)
> 
> [X] Android toolchain - develop for Android devices
>     X Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.
> 
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
> 
> [√] VS Code (version 1.52.1)
>     • VS Code at C:\Users\abdalqaderom\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.18.1
> 
> [√] Connected device (3 available)
>     • Web Server (web) • web-server • web-javascript • Flutter Tools
>     • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.66
>     • Edge (web)       • edge       • web-javascript • Microsoft Edge 87.0.664.66
> 
> ! Doctor found issues in 2 categories.

<br/><br/>

![104439562-82eb2700-5591-11eb-91ae-3e0b66d68568](https://user-images.githubusercontent.com/77385236/104444339-f2641500-5597-11eb-95ac-b4bac45bbe30.png)

**Comment by salim-lachdhaf** [comment]
Yes , that's correct, but it's related to Flutter issue itself. 
check this https://github.com/salim-lachdhaf/searchable_dropdown/issues/74
