### ISSUE TITLE
set default select item

### ISSUE THREAD

**Issue by YouSour** [salim-lachdhaf/searchable_dropdown#96]
hi , i'm using SearchableDropdown (flutter_form_builder package) everything work perfectly , but i got a small problem on my **Edit Form** i want to set a default select item but i don't know how to set it . data list i get from my backend service look like this

**Data :**  

`[
{'label':'Apple', value: 00001},
{'label':'Book', value: 00002}
]`

**Backend Method**  
```
class GlobalLookUpList{
List<dynamic> _locationOpts;
  Future<List<dynamic>> locationOpts(
      {@required Map<String, dynamic> options}) async {
    print(options);
    _locationOpts =
        await meteor.call('microfis.selectOpts.locationVillage', [options]);
    return _locationOpts;
  }
}
```

**Edit from**

```
  FormBuilderSearchableDropdown(
                            mode: Mode.DIALOG,
                            name: "location",
                            decoration: fbTextFieldStyle(labelText: "Location"),
                            hint: 'Select Location',
                            validator: FormBuilderValidators.compose([
                              FormBuilderValidators.required(context),
                            ]),
                            items: [],
                            isFilteredOnline: true,
                            onFind: (String filter) =>
                                GlobalLookUpList().locationOpts(options: {
                              'searchText': filter,
                              'values': [],
                              'params': {'branchId': '001'}
                            }),
                            itemAsString: ((u) {
                              return "${u['label']}";
                            }),
                            onChanged: (data) {
                              print(data);
                            },
                          ),
```
can you show me how to set it ? 
thank in advance :)

**Comment by salim-lachdhaf** [comment]
you can use `selectedItem`

**Comment by YouSour** [comment]
@salim-lachdhaf do have any example code pls ?

**Comment by salim-lachdhaf** [comment]
is your data format always has the same format ?
label : String
value : int 
?

**Comment by YouSour** [comment]
@salim-lachdhaf  yeah

**Comment by YouSour** [comment]
here the flow what i want
![flow](https://user-images.githubusercontent.com/9318106/104739893-db7d1880-5779-11eb-9d79-97778d858907.jpg)

**Comment by salim-lachdhaf** [comment]
-in managing data base are you using a plugin or package like moor, floor , hive ... or just sqflite ? 
-what is the format of your data returned from the database ?

**Comment by YouSour** [comment]
my backend is mongodb  and i'm using dart_meteor package to get call method from my backend , my data format return array of object @salim-lachdhaf

**Comment by YouSour** [comment]
@salim-lachdhaf  searchable_dropdown can return like this ? i think it might works for me 
`items :  items: GlobalLookUpList().getLocationOpts
                              .map((location) => DropdownMenuItem(
                                    value: location['value'],
                                    child: Text("${location['label']}"),
                                  ))
                              .toList()
    );`

**Comment by salim-lachdhaf** [comment]
`items` should have `sync` data, for `async` data you have to use `onFind`

**Comment by salim-lachdhaf** [comment]
> my backend is mongodb and i'm using dart_meteor package to get call method from my backend , my data format return array of objects @salim-lachdhaf

what is that object ? is it a map or another thing

**Comment by YouSour** [comment]
@salim-lachdhaf object = map

**Comment by salim-lachdhaf** [comment]
to set a default item, simply you can do like this for example:
`selectedItem: {'label':'Apple', value: 00001}`

**Comment by YouSour** [comment]
@salim-lachdhaf after a few days i stuck with this problem now it works, selectedItem isn't work for me but initialValue it works perfectly with FutureBuilder , thank you so much for your time 😄
